### ISSUE TITLE
distinct package name space

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [kamon-io/Kamon#105]
probably would be less confusing to move

`akka.instrumentation` -> `akka.kamon.instrumentation`

to separate what akka project will deliver by default from the kamon proper.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
