### ISSUE TITLE
Remove logback.xml from kamon-bundle

### ISSUE THREAD

**Issue by PavelPenkov** [kamon-io/Kamon#1081]
For whatever reason, kamon-bundle contains logback.xml so logback warns about multiple configuration files when starting 
`WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/app/lib/io.kamon.kamon-bundle_2.13-2.3.1.jar!/logback.xml]`

**Comment by ivantopo** [comment]
Thanks for reporting it @PavelPenkov. The file was there by mistake, probably leftover from testing :facepalm:
