### ISSUE TITLE
Connecting to InfluxDB 2 - authentication

### ISSUE THREAD

**Issue by bcreaney** [kamon-io/Kamon#1107]
Hi. Trying to connect to InfluxDB 2 using Kamon and having this error `Metrics POST to InfluxDB failed with status code [401], response body: {"code":"unauthorized","message":"unauthorized access"}`

Looking at Kamon documentation, it says that authentication is optional and if enabled uses user/password, however InfluxDB 2 requires a non optional full access/admin token.

**Comment by ivantopo** [comment]
Hey @bcreaney, seems like we will need to implement a tiny change in the reporter to support token authentication as described [here](https://docs.influxdata.com/influxdb/v2.1/api-guide/api_intro/#authentication). Seems like a tiny effort so I'll try to get it out right away.

**Comment by ivantopo** [comment]
It was a simple one, indeed :smile: 

#1110 is up now. If all goes fine it should be merged and released by Friday (I'm trying to release every Friday with whatever we have ready to be merged)

**Comment by bcreaney** [comment]
@ivantopo thanks for the fast resolution. This is great!
