### ISSUE TITLE
W3C span with OpenTelemetry, incorrect parent span ID. 

### ISSUE THREAD

**Issue by tmilner** [kamon-io/Kamon#1126]
I've been trying to setup up tracing using the W3S format and Open Telemetry. I have a weird issue where the instrumented akka server spans are not linked to the client span that called it and instead has a parent span ID that does not exist. 

In my efforts to debug this I have tried setting join-remote-parents-with-same-span-id to yes, which is not expected to be used for this, and then found that calls from non-kamon clients were correctly linked to the akka server span. However it also meant that calls from Kamon akka clients are have the corresponding server spans linked one layer too high  (IE to the parent span of the client span). 

I've spent some time looking at the code but haven't yet identified any obvious bugs or reconfiguration. To demonstrate this I created a fake traceparent value, and called an instrumented API. The corresponding traces that were collected by otel listed a parent span ID that was not the span ID in the traceparent header. 

The relevant config we are using is:
```
trace {
    span-metrics: yes
    join-remote-parents-with-same-span-id: no
    identifier-scheme = "double"
    sampler: "adaptive"
  }

  instrumentation {
    http-server.default {
      tracing {
        response-headers {
          trace-id = "none"
          span-id = none
          headers-generator = //Custome trace response header 
        }
        operations {
          name-generator = // Customer name generator
        }
      }
    }
  }

  propagation.http.default {
    entries {
      incoming {
        span = "w3c"
      }
      outgoing {
        span = "w3c"
      }
    }
  }
```

Does anyone have any ideas of what could be causing this? Or areas I could investigate?

**Comment by tmilner** [comment]
I just realised that I am on a version that contains a now reverted change to the W3C headers where it used the parent span. I suspect this is the reason so I will upgrade and close if fixed.

**Comment by tmilner** [comment]
On the latest version everything works as expected and I do not need join-remote-parents-with-same-span-id

**Comment by ivantopo** [comment]
Thanks for sharing that @tmilner!
