### ISSUE TITLE
Cannot cancel registration on module [akka.io.pinned-dispatcher] because the module was not added properly

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#1132]
This issue happens when you have more than one actor system on the same JVM since Kamon 2.3.0. The problems is that we introduced a new kind of periodic collector module used for things like thread pools and they are "keyed" by the dispatcher name, but several dispatchers have the same name across different actor systems. 

We probably should add the actor system name as a prefix to the dispatcher names, like `systemName/dispatcherName` in the registration and it should all work out, but need to figure out whether that would break any generated metric tags.

**Comment by khalidAlfozan** [comment]
Hey @ivantopo, could you please confirm if this is related to: https://github.com/kamon-io/Kamon/issues/1068 ?

**Comment by ivantopo** [comment]
Not sure, but going to comment over there :wave:
