### ISSUE TITLE
NewRelic - Histogram & Percentiles

### ISSUE THREAD

**Issue by ncanibano** [kamon-io/Kamon#114]
Hi Kamon Team!

We think that histogram and percentiles features are really useful and we missed that in our spray+kamon webapps. Are these features taken into account to be released in next milestones?

Thanks!

![kamon_newrelic_missing_histogram](https://cloud.githubusercontent.com/assets/6556066/4994992/8673a060-699c-11e4-9e12-788f95bdb012.png)

![kamon_newrelic_missing_percentiles](https://cloud.githubusercontent.com/assets/6556066/4995000/8d80e6ce-699c-11e4-8b41-f5cede569382.png)

**Comment by tovbinm** [comment]
Cool! Are you planning to release these features any time soon?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
