### ISSUE TITLE
Can not get span Info[2.5.0]

### ISSUE THREAD

**Issue by mofei100** [kamon-io/Kamon#1144]
Hi,when I use the version 2.5.0,and enable grpc trace.
But In akka-http endpoint, span info dropped.I think it is a bug.

```
"io.kamon" %% "kamon-bundle" % "2.5.0",
"io.kamon" %% "kamon-jaeger" % "2.5.0",
"io.kamon" %% "kamon-status-page" % "2.5.0",
```

```
Kamon.currentSpan() //is empty
``` 

My project link is:https://github.com/mofei100/akka-monitor-demo
branch is:feature_init_demo

please help me,thanks

**Comment by mofei100** [comment]
When using akka-grpc,http2 is enable.
kamon only instrument http2Ext.
When use http2,tracing is work.
curl --http2 http://localhost:8080/users2

**Comment by ivantopo** [comment]
Hey @mofei100,

Just wanted to link a few things here: 
  - https://github.com/kamon-io/Kamon/issues/940
  - https://github.com/kamon-io/Kamon/pull/1094

I'm aware that our Akka HTTP instrumentation only works with HTTP1 OR HTTP2, but when both are available only HTTP2 will work. I'll try to fix that asap. Thanks for sharing!
