### ISSUE TITLE
Ability to filter metrics exposed in prometheus EP

### ISSUE THREAD

**Issue by sebarys** [kamon-io/Kamon#1146]
Hello,

Is it possible to filter metrics that will be exposed by prometheus reporter?
E.g. I would like to blacklist some of the collected metrics so they won't be returned in Prometheus metrics endpoint response

Regards

**Comment by ivantopo** [comment]
Hey @sebarys, I thought we already had this implemented but nope. I just pushed #1146 to fix it. Should be out in the next release, probably later this week!

**Comment by sebarys** [comment]
Great, thanks for quick response! :)

**Comment by sebarys** [comment]
@ivantopo could you provide example how I can use it?
I'm struggling with figuring out how provide filter that will be recognised by metrics reporter
