### ISSUE TITLE
NewRelic - Missing metrics by host

### ISSUE THREAD

**Issue by ncanibano** [kamon-io/Kamon#115]
Hi Kamon Team!

Metrics splitted by host are not shown at the "table of host" NewRelic view.

Apdex, Response Time & Throughput are not shown at all, while Error Rate is showing a not accurate number:

![kamon_newrelic_missing_metrics_by_host](https://cloud.githubusercontent.com/assets/6556066/4995265/6959ff4a-699e-11e4-9902-540c43bb7e5f.png)

Thanks in advance.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
