### ISSUE TITLE
Log the packets sent to StatsD and Datadog

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#117]
It would be nice to provide some sort of debug mode where we log everything that we flush to StatsD/Datadog in order to ease troubleshooting and help people understand exactly what we are sending.

**Comment by awasilyev** [comment]
you can use netcat:
nc -u -l 8125

**Comment by evbo** [comment]
@awasilyev It is possible to successfully send statsD metrics through netcat that may not otherwise be successfully communicated through Kamon.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
