### ISSUE TITLE
using runWithContextTag doesn't seem to work across akka http directives

### ISSUE THREAD

**Issue by davellas** [kamon-io/Kamon#1200]
I am using Kamon 2.5.1 with kamon-bundle, sbt-kanela-runner 2.0.14, akka-http 10.2 (reproduces also with 10.1.x), scala 2.13.6

If I take the hello world from akka-http, and try to use and propagate Kamon Context, the context will be cleared as soon as I encounter an akka directive:

```
/*
 * Copyright (C) 2020-2021 Lightbend Inc. <https://www.lightbend.com>
 */

package docs.http.scaladsl

import akka.actor.typed.ActorSystem
import akka.actor.typed.scaladsl.Behaviors
import akka.http.scaladsl.Http
import akka.http.scaladsl.model._
import akka.http.scaladsl.server.Directives._
import scala.io.StdIn

object HttpServerRoutingMinimal {

  def main(args: Array[String]): Unit = {
    Kamon.init()

    implicit val system = ActorSystem(Behaviors.empty, "my-system")
    // needed for the future flatMap/onComplete in the end
    implicit val executionContext = system.executionContext // I tried also instrument it with ExecutorInstrumentation.instrumentExecutionContext, but it logs an error and I don't think it's necessary, right?

    val route =
      path("hello") {
          Kamon.runWithContextTag("testTag", "test") {
            // here Kamon.currentContext() will have the tag
            get {
                // here Kamon.currentContext() won't have the tag
                complete(HttpEntity(ContentTypes.`text/html(UTF-8)`, "<h1>Say hello to akka-http</h1>"))
             }
         }
      }

    val bindingFuture = Http().newServerAt("localhost", 8080).bind(route)

    println(s"Server now online. Please navigate to http://localhost:8080/hello\nPress RETURN to stop...")
    StdIn.readLine() // let it run until user presses return
    bindingFuture
      .flatMap(_.unbind()) // trigger unbinding from the port
      .onComplete(_ => system.terminate()) // and shutdown when done
  }
}
```
The tags get propagated correctly across different threads and/or futures, but if I cross an akka-http directive of any kind is seem to get lost.
Also runWithContext and runWithContextEntry doesn't seem to work.
However if I use the storeContext API it seems to work.
Is this expected or is it supposed to work?

I see that many directives do stuff with requestContext and executionContext underneath, so I am guessing something goes wrong there?
Any help or information would be appreciated.

**Comment by davellas** [comment]
Correction: using storeContext API allows me to see the tag in the nested directive, but if I call scope.close() afterwards I don't see the tag.

**Comment by davellas** [comment]
I think I figured it out: I need to put the runWithContext inside a directive:

```
def withTag(key: String, value: String): Directive0 =
    Directive { inner => ctx =>
      Kamon.runWithContextTag(key, value) {
        inner(())(ctx)
      }
    }
```

**Comment by ivantopo** [comment]
Hey @davellas, great that you figured out! That is indeed the right way to go. For reference, there is also an `operationName` directive that comes with the Akka HTTP instrumentation: https://github.com/kamon-io/Kamon/blob/master/instrumentation/kamon-akka-http/src/main/scala/kamon/instrumentation/akka/http/TracingDirectives.scala#L30
