### ISSUE TITLE
Can't record big values on `http.server.connection.lifetime`

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#1201]
One of our users is getting this error with long-lived HTTP connections (web sockets):

```
Failed to record value [7774197398489] on [http.server.connection.lifetime,{port=9000,component=play.server.akka-http,interface=0.0.0.0}] because the value is outside of the configured range. The recorded value was adjusted to the highest trackable value [3600000000000]
```

By default our histograms can cover up to 1h latencies and in this case, a connection was alive for over 2 hours at the time it closed. If it was a more commonly used metric I would suggest increasing the range in the metric but in this case we are not sure of how big this number can get as it could go all the way to days. I think we could:
  - Increase the lower discernible value for this metric so we can pack a much higher bound in the range while keeping the same memory footprint
  - Use a lower precision histogram for this metric, with recorded values up to 10% away from the originally recorded value. This can massively increase range and probably reduce footprint.

Whatever we decide, it should be the default for this metric so nobody faces the same issue in the future!

**Comment by ivantopo** [comment]
I did some quick tests and these settings are kind of nice defaults:

```
kamon.metric.factory.custom-settings {
  "http.server.connection.lifetime" {
    lowest-discernible-value = 1000000
    highest-trackable-value = 6E14
  }
}
```

It makes the metric cover the range from 1ms to 7 days, with 1% precision, and it even uses ~30% less memory than the default histogram! This will probably become the new default for the metric :muscle:

**Comment by Dichotomia** [comment]
Same problem here on multiple applications.
