### ISSUE TITLE
Kafka instrumentation is not using w3c for context propagation

### ISSUE THREAD

**Issue by Symbianx** [kamon-io/Kamon#1235]
Hello,
We're using Kamon to instrument our akka services and it works really well! 
Because we use different languages across all the projects we decided to go with W3C trace-context for context propagation.

This works really great on Kamon with HTTP:
```
kamon.propagation.http.default.entries {
  incoming {
    span = "w3c"
  }
  outgoing {
    span = "w3c"
  }
}
```

However, we can't find a way to use the trace-context headers in kafka messages. Is there a config we can set for it? 

If it's not available but wanted, I could make a PR for it.

**Comment by Symbianx** [comment]
Thanks for the quick response @ivantopo!

We've been instrumenting java, python and node apps with the opentelemetry packages and they don't make a distinction between http or kafka. The same propagation method is used for both protocols, which by default is W3C.

I don't know what all other vendors are doing but [NewRelic seems to be adopting the OpenTelemetry](https://newrelic.com/blog/how-to-relic/distributed-tracing-with-kafka) standards as well.

**Comment by duxet** [comment]
> Do you know if it is a common practice to use the w3c format in Kafka (or in general, message brokers)? If so, we could definitely look at adding a setting for this.

I've been looking into this recently and yes, official OT Java instrumentation uses existing TextMapPropagator to inject trace context into Kafka record headers: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/kafka/kafka-clients/kafka-clients-common/library/src/main/java/io/opentelemetry/instrumentation/kafka/internal/KafkaPropagation.java#L53

**Comment by ivantopo** [comment]
Thanks for the feedback folks!

@Symbianx going back to this:

> If it's not available but wanted, I could make a PR for it.

I can say it is definitely not available, and wanted. Would love to see that PR!

**Comment by Symbianx** [comment]
@ivantopo started a PR but I'm having issues with compiling the project. Any tips would be handy.
