### ISSUE TITLE
kamon support for netty library

### ISSUE THREAD

**Issue by spotsantosh** [kamon-io/Kamon#1239]
Would like to know if kamon supports monitoring of socket connections using netty library, or if there are any plans to include support in future releases.

**Comment by ivantopo** [comment]
Hey @spotsantosh!

Are you referring to HTTP servers built on top of netty or lower-level sockets? If it is HTTP servers, there is already some work in progress for supporting Netty via https://github.com/kamon-io/Kamon/pull/1113, but I'm not of any timeline for it as the PR is missing a bit of work.

If you are actually referring to sockets then no, definitely no plans to support it. You can still use Kamon to instrument things by hand, though. Feel free to ask again if you have specific questions about how to do manual instrumentation. Cheers!
