### ISSUE TITLE
kamon actor name space

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [kamon-io/Kamon#125]
RE:
![image](https://cloud.githubusercontent.com/assets/1622151/5285205/e2b366fe-7adf-11e4-9900-5561d8896249.png)

I suggest all kamon actors use consistent name space, such as `kamon-*`

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
