### ISSUE TITLE
Kafka instrumentation. Add supporting for different context type propagation

### ISSUE THREAD

**Issue by yarosman** [kamon-io/Kamon#1284]
Now, there is support only two propagation types: `kctx, w3c`.
And you can't define your custom implementation in any way.

We have services in different languages and we use B3 type format for context propagation in Kafka too.
Therefore it would be great to add a new `b3` type propagator and the possibility to define `fqcn`(fully qualified class name) propagator which extends `KafkaPropagator` and can use propagators from `kamon.trace.SpanPropagation._`
```
# Decides which specification to use for context propagation. By default, uses the `kctx` header for
# compatibility with older versions.
# Possible values:
#   - w3c - requires kamon.trace.identifier-scheme = double
#   - kctx
#   - b3 //TODO:
#   - fcqn //TODO:
kamon.instrumentation.kafka.propagator = "kctx"
```

**Comment by hughsimpson** [comment]
@yarosman Since custom Kafka propgators are now supported, I'm closing this. If you want to raise a ticket to support a specific implementation, please feel free to do so
