### ISSUE TITLE
automatically call Akka.system() on play apps startup.

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#130]
Currently all the Kamon machinery is started after the first request is received as explained by one of our users [1] (assuming that the user code is not using akka for something else), but we should not wait until the first request to get Kamon running since we are potentially failing to report system metrics until the first request arrives. 

[1] https://groups.google.com/forum/#!topic/kamon-user/o-OmN30A7eI

**Comment by dpsoft** [comment]
with #162 there is no longer necessary.
