### ISSUE TITLE
Old kanela-agent which does not support JDK 21

### ISSUE THREAD

**Issue by rpiotrow** [kamon-io/Kamon#1302]
Current version of kamon-bundle (2.6.5) contains kanela-agent-1.0.17, which still does not support JDK 21. Recent version (1.0.18) already supports that (see https://github.com/kamon-io/kanela/releases/tag/v1.0.18).

**Comment by danischroeter** [comment]
resolved

**Comment by nickrobison** [comment]
@danischroeter could we get a new release of Kamon which includes the Kanela update? Not sure what the normal release schedule is, but I figured I'd ask!

**Comment by danischroeter** [comment]
Hi @nickrobison 
I'm also waiting for a new release like you since afaik only @dpsoft @ivantopo or @hughsimpson can create a release.
But having a release would be greatly appreciated since it's also blocking us. :)
@rpiotrow can you close this issue pls since it's solved...

**Comment by rpiotrow** [comment]
Resolved, but not released yet (it should be available in 2.6.6)
