### ISSUE TITLE
Sbt 1.9.7 upgrade breaks Kamon Play HTTP Prometheus Metrics

### ISSUE THREAD

**Issue by Dichotomia** [kamon-io/Kamon#1308]
Hi,
On all our projects having Play 2.8.20 running on java 17 with Kamon Bundle and Kamon Prometheus 2.6.5.

Scala version is 2.13.12.

Upgrading from sbt 1.9.6 to 1.9.7 => No metrics in Grafana.

Reverting upgrade => Metrics restored.

Best regards

**Comment by Dichotomia** [comment]
The upgrade to sbt-javaagent 0.1.8 seems to fix the problem with sbt 1.9.7. https://github.com/sbt/sbt-javaagent/releases/tag/v0.1.8

**Comment by ivantopo** [comment]
Awesome! Thanks for sharing the fix @Dichotomia :wave: 

We should probably upgrade our dependency on the sbt-kanela-loader to the latest.
