### ISSUE TITLE
Updating Postgres Driver causes NoSuchFieldError from Kamon JDBC 

### ISSUE THREAD

**Issue by tmilner** [kamon-io/Kamon#1334]
When updating the Postgres driver in our app to 42.7.3 Kamon started crashing the app with a NoSuchFieldError around the `checkConnectionQuery` function. 

I initially raised this issue in Discord here - https://discord.com/channels/866301994074243132/866301994074243135/1225739191527280680

The function was removed from the driver here - https://github.com/pgjdbc/pgjdbc/commit/6ab2fbadc09bbbf42c7c2f9abdc1789c48c8c5b5

**Comment by Dichotomia** [comment]
We can close this issue.
