### ISSUE TITLE
Release 2.7.4 not available on maven central

### ISSUE THREAD

**Issue by Philippus** [kamon-io/Kamon#1363]
Looks like the release process didn't complete successfully: https://github.com/kamon-io/Kamon/actions/runs/10897926702

**Comment by Dichotomia** [comment]
Hello. Any news about this problem?

**Comment by ivantopo** [comment]
Hey @Philippus and @Dichotomia, this was caused by a change in the Sonatype credentials scheme that now required us to use a token instead of the same login as in the web interface. I updated the credentials earlier today, re-ran the release and it went fine. Thanks for reporting!

**Comment by Dichotomia** [comment]
Thanks !
