### ISSUE TITLE
 kamon-system-metrics: context switches metric causes file descriptor leak

### ISSUE THREAD

**Issue by pikazlou** [kamon-io/Kamon#148]
In SystemMetricsCollector.scala we have the following loop
```
val filename = s"/proc/$pid/status"
...
for (line ← Source.fromFile(filename).getLines()) {
```
Source is an infamous scala.io.Source which is known for not closing files after they are used. Running application with context switches metric enabled and using "lsof -p PID" clearly shows growing number of open "/proc/PID/status" files. Eventually this leads to "too many open files" errors.

**Comment by ivantopo** [comment]
@pikazlou thanks for reporting this, we will fix and include in the next release for sure!
