### ISSUE TITLE
fuse source sigar package causes the SystemMetrics extension to crash

### ISSUE THREAD

**Issue by henrymai** [kamon-io/Kamon#154]
Been seeing a bunch of jni related failures from the sigar java binding that is being used by SystemMetrics:
```
# Problematic frame:
# V  [libjvm.so+0x5f5703]  jni_SetLongField+0xb3
```
I was able to locally fix this by building my own sigar and replacing the the fuse source sigar package in my ivy cache so that my scala application picks it up instead of the fuse source one.

**Comment by ivantopo** [comment]
that's weird.. did you try just deleting your sigar artifact from .ivy2 and made sbt download it again before putting your own build there?

**Comment by henrymai** [comment]
In our setup, we always deploy from a fresh slate, so we don't have any old artifacts.

**Comment by dpsoft** [comment]
Hi henrymai,

can you please give us information about your OS and JVM version?.

Cheers,
Diego

**Comment by henrymai** [comment]
Docker host machine os (64 bit):
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic
```

Container running the code using Kamon:
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```
```
# update-java-alternatives -l
java-1.7.0-openjdk-amd64 1071 /usr/lib/jvm/java-1.7.0-openjdk-amd64
```
```
# md5sum org.fusesource.sigar-1.6.4.jar
85d4a580bcd31802064024d33f668e9a  org.fusesource.sigar-1.6.4.jar

The md5sum matches: http://repo1.maven.org/maven2/org/fusesource/sigar/1.6.4/sigar-1.6.4.jar.md5
```

**Comment by henrymai** [comment]
It looks like fusesource sigar has been removed since cd63515b0afa603e317cc63e43a3341783ba3e15, so I think this issue is resolved.
