### ISSUE TITLE
Kamon-newrelic ssl

### ISSUE THREAD

**Issue by saparbek** [kamon-io/Kamon#155]
I am trying to post metrics to NewRelic, however I get the following error: "Expected field 'return_value' in '{"exception":{"message":"Account Security Violation: The agent is not configured to use SSL","error_type":"NewRelic::Agent::ForceDisconnectException"}}'"

Does it mean that Kamon-newrelic does not support SSL at all?

**Comment by ivantopo** [comment]
The `kamon-newrelic` module definitely does not support using SSL as of now, will add support for it.

**Comment by jkbkrk** [comment]
I will also appreciate SSL support in Kamon New Relic module.

**Comment by cheekychops** [comment]
+1

**Comment by cheekychops** [comment]
I have created a patch for this in my fork, if you like it I'll create a PR.

https://github.com/cheekychops/Kamon/commit/7ae2b4c540edce05d0ad8064e5ba5dcecfaab1f1

**Comment by dpsoft** [comment]
@cheekychops yes please!!!

**Comment by ivantopo** [comment]
This issue was fixed by #268.. The snapshot version `0.5.3-ccb049c07fc28d25f389be72a242240fec1881a3` is on its way to our snapshots repo, please test it and report if you find any issues!
