### ISSUE TITLE
Missing web transactions in New Relic

### ISSUE THREAD

**Issue by gmalouf** [kamon-io/Kamon#167]
We've been running the Kamon-Spray-NewRelic integration in production for the last 45 days or so.  I've noticed that our requests-per-minute being reported are an order of magnitude less than what we see being recorded into our database (NOTE: We are definitely getting transactions though we get lengthy spells of 0 transactions/minute where we clearly actually have data flowing).  I do not see errors in our logs, so I'm not sure how the transaction data is so far off.  

I'm unsure if this is a bug in the integration or if Spray settings need to be adjusted.

**Comment by ivantopo** [comment]
Hello Gary, can you please tell us what Kamon version are you using? also please take a look at #112, is it possible that you are experiencing the same issue?

**Comment by gmalouf** [comment]
We are using 0.3.5 of both kamon-newrelic and kamon-spray.  I'm not sure whether or not is it is #112, we see a small subset of our transactions being reported around the :45 of each hour.  
![screen shot 2015-03-16 at 11 55 00 am](https://cloud.githubusercontent.com/assets/982483/6670118/5af3afa4-cbd3-11e4-8e9b-aee6232de353.png)

**Comment by ivantopo** [comment]
That pattern is weird, seem to be reporting exactly every 1 hour. Did you restart the application during the 6 hours period shown there?

**Comment by gmalouf** [comment]
We did not, have not restarted it in a bit over 2 weeks.

**Comment by ivantopo** [comment]
if you go back 2 weeks in your dashboard, was it operating normally during some period of time or was it like this the whole time?

**Comment by gmalouf** [comment]
It started doing this March 7 (~ 9-10 days ago).
![screen shot 2015-03-16 at 12 16 22 pm](https://cloud.githubusercontent.com/assets/982483/6670659/4fdb8620-cbd6-11e4-9f1f-da5fc7c568b0.png)

**Comment by ivantopo** [comment]
I think it might be the same issue as #112 and the New Relic servers might be behaving differently.. can you please try out the snapshots mentioned there?

**Comment by gmalouf** [comment]
Will do, thanks Ivan.

**Comment by gmalouf** [comment]
That definitely got the metrics running again - will keep an eye on them over the next week to see if stuff drops.

**Comment by ivantopo** [comment]
Nice! Looking forward to your confirmation.

**Comment by ivantopo** [comment]
Hey @gmalouf, how did the app behave over time? Please let us know if you need any further assistance or if we can close this issue.

**Comment by gmalouf** [comment]
The snapshots did the trick - no issues over the next several weeks.  We
have since dropped New Relic for the time being in favor of StackDriver due
to non-related issues.

Best,

Gary

**Comment by ivantopo** [comment]
Thanks Gary, will proceed to close this issue then, regards!
