### ISSUE TITLE
Create a Play(2.4) module for manage the lifecycle of kamon

### ISSUE THREAD

**Issue by dpsoft** [kamon-io/Kamon#169]
https://www.playframework.com/documentation/2.3.x/JavaPlugins

**Comment by dpsoft** [comment]
@magro what are your thoughts about the idea of provide other alternative to start kamon in a play application?

**Comment by magro** [comment]
I personally don't like play plugins that much but prefer good old dependency injection. Plugins add another concept that I have to think about e.g. in the context of (unit/integration) tests and therefore increase the complexity.

In play 2.4 AFAIK plugins will become obsolete and be replaced by "normal" DI modules (for runtime DI) or will be instantiated manually if compile time DI is used.

Providing a plugin now for play 2.3 just to start/stop Kamon IMHO does not add much value. For 2.4 you might provide a module, just for convenience (see also "Play libraries" in  https://www.playframework.com/documentation/2.4.x/ScalaDependencyInjection).

**Comment by dpsoft** [comment]
Martin, thanks for the response, I completely agree with you, maybe for play 2.4 we will create a module for convenience.

**Comment by dpsoft** [comment]
related to 56636f31a0ad34e62ff4627a32c28b802e423da2.
