### ISSUE TITLE
kamon-play LoggerLike use case

### ISSUE THREAD

**Issue by richardhundt** [kamon-io/Kamon#171]
What is the purpose of the LoggerLike instrumentation? I was expecting it to record error rates, but it doesn't seem to be. I can't figure out why it is copying stuff to slf4j's MDC. Other than that, I can't see it actually doing anything in the play example app, when I look at the LogReporter output.

**Comment by dpsoft** [comment]
Hi Richard,

the idea behind LoggerLikeInstrumentation is save in the kamon
TraceLocalStorage some useful data and propagate this in the MDC.
This is a thread with an example and also the tests could be useful until
the next release that include full documentation.

Cheers,

Diego

**Comment by dpsoft** [comment]
Hi Richard,

the idea behind LoggerLikeInstrumentation is save in the kamon
TraceLocalStorage some useful data and propagate this in the MDC.
This is a thread
<https://groups.google.com/forum/#!searchin/kamon-user/mdc/kamon-user/19lNsXvxXcM/ACkUh2lIzhIJ>
with an example and also the tests
<https://github.com/kamon-io/Kamon/blob/master/kamon-play/src/test/scala/kamon/play/LoggerLikeInstrumentationSpec.scala>
could be useful until the next release that include full documentation.

Cheers,
