### ISSUE TITLE
Detailed traces for Spray in New Relic

### ISSUE THREAD

**Issue by danielgratzl** [kamon-io/Kamon#175]
The documentation (http://kamon.io/backends/newrelic/) reads "Differentiation between JVM and External Services is coming soon, as well as actor metrics and **detailed traces.**".

Is this something that is currently worked on? If not could you provide a starting point on how to implement this? We are new to Kamon and New Relic but we think it's a very nice combination and would be happy to have detailed traces for the transactions.

**Comment by ivantopo** [comment]
Hello @gh0zt, we currently have something we call simple traces in Kamon and I'm pretty sure that after our long awaited 0.4.0 release we will certainly put some efforts on pushing the simple traces to New Relic. After that we need to work on the grounds to actually support detailed traces within Kamon and later explore if/how we can get that data into New Relic. I'm almost sure that our New Relic module will only get simple traces but let's see what happens with time. 

With regards to how to implement this, I would recommend first reading [this excellent post] from Martin Grotzke explaining how he is using the simple metrics subscriptions and then jump into the kamon-newrelic code to understand how it is currently working. Sadly, New Relic doesn't provide a public API and we are kind of replicating what their node.js and ruby agents do as their code is freely available on Github and we use them as a guide..  so next step should be studying those repos to understand how to push the data... If you feel like putting some efforts on this then let us know and we can provide more guidance but as you might suspect now, getting our data there is not a friendly path and some important efforts are required :(..


[this excellent post]: http://www.inoio.de/blog/2014/12/13/how-to-log-slow-requests-with-play2/

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
