### ISSUE TITLE
Possible memory leak with Kamon

### ISSUE THREAD

**Issue by gsphanikumar** [kamon-io/Kamon#176]
I am using the below versions of akka,spray and kamon with newrelic agent in a scala application.

akka - 2.3.0
spray - 1.3.2
kamon - 0.3.5

When i include kamon as a  runtime dependency, i see the application going out of memory and crashing. I dont think https://github.com/kamon-io/Kamon/issues/119 is the issue here because i am hitting the right url.  If I remove kamon as the  runtime dependency i don't see this issue.

Please find below the memory snapshot. As you can see almost 49% of objects are not reachable but not yet collected. 

![with_kamon](https://cloud.githubusercontent.com/assets/667947/6918633/2467a952-d7ce-11e4-95bc-47c44b53e652.png)

**Below is the memory snapshot without kamon.**

![without_kamon](https://cloud.githubusercontent.com/assets/667947/6918634/2467982c-d7ce-11e4-97db-6dceb9676485.png)

Please let me know if you need any more details

**Comment by ivantopo** [comment]
hello @gsphanikumar, please tell me one thing: are you using the `traceName` directive to correctly name your traces as described in [this post]?, from your screenshot I see that you have 773 `TraceMetricRecorder` instances which probably means that you are not grouping the traces using the  `traceName` directive, please give it a try and keep asking if you need any further help! 

With regards to the "unreachable but not yet collected" objects, according to the [yourkit documentation] what you are seeing is plain and simple garbage that will be cleaned up by the next GC, you should get a much lower number for that metric if you take a dump just after a major GC. I don't think that there is a memory leak here but rather unaware use of too many recorders, sorry that we didn't include info for this in our site yet, we are working on documentation right now and this will certainly be included, looking forward to your comments!

[this post]: https://groups.google.com/d/msg/kamon-user/wCpexpMm5ik/AXuajnKbCxoJ
[yourkit documentation]: https://www.yourkit.com/docs/java/help/reachability.jsp

**Comment by gsphanikumar** [comment]
@ivantopo Thanks for the response. Yes currently we are not grouping the traces.  I will try that and let you know if that helps.

**Comment by gsphanikumar** [comment]
Naming traces with traceName fixes this issue.

**Comment by ivantopo** [comment]
Excellent, thanks for sharing!
