### ISSUE TITLE
4.0.0 pre-release documentation feedback

### ISSUE THREAD

**Issue by jamesmulcahy** [kamon-io/Kamon#180]
Hi Ivan,

While browsing through the documentation you pointed me at, I spotted a couple of things:

- Some of the code snippets in "TraceContext Manipulation" don't render correctly
- The paragraph of text in "TraceContext Manipulation -> Actor Creation" ends abruptly

You may already be aware of these, but I thought I'd mention them anyway.

**Comment by ivantopo** [comment]
thanks for the feedback, James! I'm currently working on the tracing section docs, will let you know when it is ready for you to review again!

**Comment by ivantopo** [comment]
James, we published our latest WIP with regards to documentation at http://master.kamon.io/core/tracing/core-concepts/, please take a look at it!

The code snippets are now rendering nice and the context is complete. Also, the akka-specific content was moved to the Akka Integration section.

**Comment by ivantopo** [comment]
Well, release is out! Closing.
