### ISSUE TITLE
Add steady / oscillating counters to Kamon.

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#185]
We have found over time the need for counters that:
- do not reset back to zero on every tick.
- can be decremented.

Not sure if we should provide this characteristics as configuration settings in a unique counter instrument or as a separate instrument.

**Comment by JozoVilcek** [comment]
Does this account also for counters which can have ```None``` value unless they receive ```Some``` input? Such counter, in case of ```None``` value, would not report anything on tick.

**Comment by ivantopo** [comment]
At the kamon-core level, counters that didn't have any activity would still report what they were configured for (either 0 or their current value), that would help keep all metric backends aware that the counter exists. Now, it is up to a specific metrics backend to decide whether to report or not counters that didn't move in the current tick.

Please let us know if you have a specific issue or use case to consider and we will keep it in mind when working on this issue :).

**Comment by JozoVilcek** [comment]
I was trying to describe my use case [here](https://groups.google.com/forum/#!msg/kamon-user/Ly2VDWohZm0/Ji0O8aJcUtgJ). I agree that this might be a little odd for Kamon, which is more toward "real-time" metrics collection and not for sporadic metrics (counters) occurring at irregular time intervals (e.g. statistics reported by scheduled batch processes).

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
