### ISSUE TITLE
Mailbox sizes question

### ISSUE THREAD

**Issue by rafael** [kamon-io/Kamon#187]
Hi! 

Quick question, is there a configuration setting that needs to be set to report the processing-time, time-in-mailbox and mailbox-size? These metrics don't seem to be getting to statsd in my setup. 

Thanks!

**Comment by ivantopo** [comment]
Hey Rafael, if an actor is catched by Kamon then the metrics will be sent, maybe you need to change the filters to include the actors you want?

**Comment by rafael** [comment]
oh nevermind. They are there lol. I was looking for them inside stats, but they are in timers.

**Comment by ivantopo** [comment]
Nice, keep having fun! :D
