### ISSUE TITLE
respect the configured name generator for Play apps

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#190]
Currently the configured name generator for Play is being used to assign a initial name to traces, but that name is always renamed to follow the "$path.$verb" pattern, rendering the initial name useless. 

Not sure what is the best way to fix this, but we definitely should make sure that creating a custom name generator makes sense and that if nothing else changes the trace name, the name returned by the name generator should stay intact.

**Comment by dpsoft** [comment]
We need start a trace without name because, the complete information of the RequestHeader is available at the moment of filter execution, before that,  there is not tag information in the RequestHeader and is not posible build a complete Trace Name.
