### ISSUE TITLE
Release Kamon 0.4.0

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#191]
Here is a quick list of the pending tasks for the release.

- [x] write the announcement post.
- [x] update the changelog with the tons of changes in 0.4.0. 
- [x] review documentation for the kamon-annotation module.
- [x] review documentation for the MDC support.
- [x] review the documentation on metric backends.
- [x] upgrade the landing and teamblog sections of kamon.io to use the new style.
- [x] create a migration guide for people coming from Kamon 0.3.x/0.2.x.
- [x] merge all changes into the _akka-2.2 branch.
- [x] publish artifacts.
- [x] publish the new site at kamon.io.
- [ ] order pizza and beers, get drunk and sleep a couple days.

**Comment by adrien-aubel** [comment]
:+1:

**Comment by smagnacco** [comment]
You and Diego should start by the last one ;)

2015-05-04 20:10 GMT-03:00 Adrien Aubel <notifications@github.com>:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kamon-io/Kamon/issues/191#issuecomment-98881485>.
>



-- 
------------------------------------------------------------
Ing. Sergio Joel Magnacco
IT - Hoteles - API v3 / Rainman / GHF / OTAI / Feed - Project Leader
*Av. Corrientes N° 746 - piso 9° - C.A.B.A. (C1043AAU)*
<http://www.despegar.com/>
*[image: Seguinos en Twitter!] <http://twitter.com/#!/despegarar> [image:
Seguinos en Facebook!] <http://www.facebook.com/despegar> [image: Seguinos
en YouTube!] <http://www.youtube.com/Despegar>*
*Despegar.com, Inc. *
El mejor precio para tu viaje.

Este mensaje es confidencial y puede contener información amparada por el
secreto profesional.
Si usted ha recibido este e-mail por error, por favor comuníquenoslo
inmediatamente respondiendo a este e-mail y luego eliminándolo de su
sistema.
El contenido de este mensaje no deberá ser copiado ni divulgado a ninguna
persona.

**Comment by ivantopo** [comment]
There wont be mention of trace local storage or MDC support until we fix #196.

**Comment by ivantopo** [comment]
Had bad luck twice with finding pizza, but then got twice the beer :D, closing!
