### ISSUE TITLE
Please provide an RSS feed for the team blog

### ISSUE THREAD

**Issue by agemooij** [kamon-io/Kamon#195]
Hey guys. I'd like to follow your team blog but it doesn't provide an RSS or Atom feed. Could you please provide one?

Thanks,
Age

**Comment by ivantopo** [comment]
Hello Age, nice to see you around :D, we just published a feed on http://kamon.io/teamblog/rss/, would that work for you? In theory, while browsing through the site people should be able to simply subscribe if they have some sort of extension that picks up the `<link>` but for some reason it is not working, looking into that.

**Comment by ivantopo** [comment]
Found the problem, silly location error.. now the feed is up!

**Comment by agemooij** [comment]
Feedly now auto-detects the feed. Thanks! Keep up the good work!
