### ISSUE TITLE
akka-streams module

### ISSUE THREAD

**Issue by dpsoft** [kamon-io/Kamon#206]
This issue should be used for obtain ideas that could be useful as metrics.
- [ ] propagate the TraceContext  over the Stream.
- [ ] measure the time for receive elements in the Flow.

**Comment by tkp1n** [comment]
Is this something you are going to think about implementing in the (near) future?

**Comment by Tenchi2xh** [comment]
I, too, would be really interested in this module 👍

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
