### ISSUE TITLE
potential memory leak

### ISSUE THREAD

**Issue by zileliao** [kamon-io/Kamon#214]
What we use:

spray-can 1.3.2 
akka 2.3.9
new relic 3.13
kamon dependencies:
io.kamon.kamon-core_2.11-0.3.5.jar		io.kamon.kamon-newrelic_2.11-0.3.5.jar
io.kamon.kamon-log-reporter_2.11-0.3.5.jar	io.kamon.kamon-spray_2.11-0.3.5.jar

The following line is commented out from application.conf
  # extensions = ["kamon.newrelic.NewRelic"]

While we do not expect kamon being loaded into runtime, we found a memory leak that caused full GC:

![image](https://cloud.githubusercontent.com/assets/8269704/7993639/932155e8-0ad5-11e5-9fc9-28eba2150caf.png)

**Comment by nilsga** [comment]
We are seeing some similar behaviour. A large amount (3 gig) of `long[]` arrays with histogram values. Have you been able to investigate this further, @ivantopo?

**Comment by ivantopo** [comment]
hey guys! are you using the `traceName` directive or any other means of correctly assigning a proper name to the traces automatically generated by the kamon-spray module?.. if you don't do so and your URLs contain variable values then you can fill up the help with meaningless per-url trace metric recorders!

We changed the behavior to assign "UnnamedTrace" as the default trace name in Kamon 0.4.0, precisely to avoid this kind of errors and you can see how to properly assign trace names in [the docs](http://kamon.io/integrations/web-and-http-toolkits/spray/)!

Please let me know if this actually is the issue you are having or if otherwise you can share a dump for us to look closer.

**Comment by ivantopo** [comment]
Hello @zileliao, did you solve this issue by using the `traceName` directive? If you decide to upgrade to Kamon 0.4.0 please note that there is a related issue that causes a different type of leak, as described in #213. 

Hope you find that info useful.

**Comment by zileliao** [comment]
Thanks Ivan. I will set up a test in our staging environment and post back the finding.



On Jul 20, 2015, at 6:00 PM, Ivan Topolnjak <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @zileliao<https://github.com/zileliao>, did you solve this issue by using the traceName directive? If you decide to upgrade to Kamon 0.4.0 please note that there is a related issue that causes a different type of leak, as described in #213<https://github.com/kamon-io/Kamon/issues/213>.

Hope you find that info useful.

**Comment by zileliao** [comment]
I gave 0.4.0 a quick try. I think it resolved the memory leak problem and I will close this issue.

I tried 2 things:
1. override DefaultNameGenerator to match certain path route with variables into fix route so that
PUT: /v2/user/${userId}/identity becomes PUT: /v2/user/identity. Inserting a traceName into each route is undesirable

2. Able to see kamon-log-report collecting metrics:
```
|    Trace: PUT: /v2/user/identity                                                                 |
|    Count: 1                                                                                      |
|                                                                                                  |
|  Elapsed Time (nanoseconds):                                                                     |
|    Min: 1451229184   50th Perc: 1451229184     90th Perc: 1451229184     95th Perc: 1451229184   |
|                      99th Perc: 1451229184   99.9th Perc: 1451229184           Max: 1451229184   |
```

but newrelic collector sent 0's 
```
[INFO] [07/22/2015 12:05:43.642] [kamon-akka.actor.default-dispatcher-3] [akka://kamon/user/newrelic-agent] Configuring New Relic reporters to use runID: [1982293762] and collector: [collector-163.newrelic.com]

[1982293762, 1437581138, 1437581198, [
	[{
		"name": "Apdex"
	}, [0, 0.0, 0.0, 1.0, 1.0, 0.0]],
	[{
		"name": "WebTransaction"
	}, [0, 0.0, 0.0, 0.0, 0.0, 0.0]],
	[{
		"name": "WebTransactionTotalTime"
	}, [0, 0.0, 0.0, 0.0, 0.0, 0.0]],
	[{
		"name": "External\/all"
	}, [0, 0.0, 0.0, 0.0, 0.0, 0.0]],
	[{
		"name": "HttpDispatcher"
	}, [0, 0.0, 0.0, 0.0, 0.0, 0.0]],
	[{
		"name": "External\/allWeb"
	}, [0, 0.0, 0.0, 0.0, 0.0, 0.0]]
]]
```

Is there anything else I need to specify? See my settings below:

```
kamon {
  spray {
    name-generator = com.bamnetworks.services.kamon.MappedNameGenerator
  }

  newrelic {
    app-name = "myservice"
    license-key = "mylicensekey"
  }
}
```

Thanks!
