### ISSUE TITLE
kamon.io stops reporting to statsD

### ISSUE THREAD

**Issue by LukaszMarchewka** [kamon-io/Kamon#219]
Hi, I have created simple web application in play framework and a I have used kamon.io to count number of requests. Next i have configured to send that data to statsD. Everything works fine for normal load. But if I start generating too much requests ( traffic bigger than application is able to handle), kamon.io stop sending data to statsD, and log that error:

[INFO] [05/27/2015 17:16:22.817] [kamon-akka.actor.default-dispatcher-2] [akka://kamon/system/IO-UDP-FF/selectors/$a/0] Message [akka.io.Udp$Send] from Actor[akka://kamon/deadLetters] to Actor[akka://kamon/system/IO-UDP-FF/selectors/$a/0#-1615202930] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

LogReporter works fine.

akka - 2.3.9 and 2.3.11
kamon.io - 0.4.0

**Comment by bekiroguz** [comment]
Hi Lukazs,
could you be able to find a way to fix/workaround this issue in your case? It seems this bug report has no popularity but I also face a similar problem.
- Bekir

**Comment by LukaszMarchewka** [comment]
Hi Bekir,
It is probably bug in akka, I have reported the same bug there: https://github.com/akka/akka/issues/17748 but without solution too.

I have fixed it by running statsD on local machine instead of on remote. I don't know if it's good solution but after that I haven't seen it any more.

**Comment by ornicar** [comment]
I'm experiencing the same issue when sending UDP data to influxDB. This was logged:

```
[INFO] [01/07/2017 13:30:31.064] [kamon-akka.actor.default-dispatcher-4] [akka://kamon/system/IO-UDP-FF/selectors/$a/0] Message [akka.io.Udp$Send] from Actor[akka://kamon/user/influxdb-metrics-sender/$a#-1197210686] to Actor[akka://kamon/system/IO-UDP-FF/selectors/$a/0#180681148] was not delivered. [1] dead letters encountered.
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
