### ISSUE TITLE
Trace data reported to new relic does not include host information

### ISSUE THREAD

**Issue by leachbj** [kamon-io/Kamon#221]
When multiple instances of an application are running and reporting to new relic the new relic views allow to display the various reports per JVM.  With Kamon however the data is only available as an aggregate across all JVMS and the per JVM view shows no results.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
