### ISSUE TITLE
No data for Actor metrics

### ISSUE THREAD

**Issue by ksnagendran** [kamon-io/Kamon#222]
Hi All,
I integrated kamon with a Java Play framework application and when i run the application there is no data for the actor metrics graph but i can see the trace graph and system metrics graph.

I checked the logs and it always shows zero for processing time, time in mail box and mail box size.

This is my code:

build.sbt

"io.kamon" %% "kamon-core" % "0.4.0",
"io.kamon" %% "kamon-akka" % "0.4.0",
"io.kamon" %% "kamon-play" % "0.4.0",
"io.kamon" %% "kamon-statsd" % "0.4.0",
"io.kamon" %% "kamon-log-reporter" % "0.4.0",
"io.kamon" %% "kamon-system-metrics" % "0.4.0",
"org.aspectj" % "aspectjweaver" % "1.8.6",

kamon settings:

kamon {
  log-reporter {
  }
  metric {
    tick-interval = 1 second
    filters {
        akka-actor {
          includes = ["**/ManagerActor/*/WorkerActor"]
        }
        akka-router {
          includes = ["**"]
        }
        akka-dispatcher {
          includes = ["akka.actor.default-dispatcher"]
        }
      }
  }
 statsd {
    hostname = "192.168.59.103"
    port = 8125
    flush-interval = 1 second
    max-packet-size = 1024 bytes
    subscriptions {
      histogram       = [ "**" ]
      min-max-counter = [ "**" ]
      gauge           = [ "**" ]
      counter         = [ "**" ]
      trace           = [ "**" ]
      trace-segment   = [ "**" ]
      akka-actor      = [ "**" ]
      akka-dispatcher = [ "**" ]
      akka-router     = [ "**" ]
      system-metric   = [ "**" ]
    }
    simple-metric-key-generator {
      application = "MyApp"
    }
  }
  modules {
    kamon-akka {
      auto-start = yes
      requires-aspectj = yes
      extension-id = "kamon.akka.Akka"
    }
  }
}

and i started the kamon as Kamon.start();

**Comment by dpsoft** [comment]
you can provide us an example or your code, that we can run?

**Comment by ksnagendran** [comment]
What kind of example or information you needed, kindly let me know?

**Comment by dpsoft** [comment]
I've lost this part of the previous message :

Actor: test/user/simple-service-actor |
| |
| Processing Time (nanoseconds) Time in Mailbox (nanoseconds) Mailbox Size |
| Msg Count: 0 Msg Count: 0 Min: 0 |
| Min: 0 Min: 0 Avg.: 0.0 |
| 50th Perc: 0 50th Perc: 0 Max: 15 |
| 90th Perc: 0 90th Perc: 0 |
| 95th Perc: 0 95th Perc: 0 |
| 99th Perc: 0 99th Perc: 0 Error Count: 0 |
| 99.9th Perc: 0 99.9th Perc: 0 |
| Max: 0 Max: 0

the simple-service-actor what's is doing? you can simulate a high load and
putting on the receive method a thread.sleep or something like that?

Cheers,

Diego

**Comment by ksnagendran** [comment]
Hi Diego,
This is what happen now, if i filter the metrics like this

includes = ["myAkka/user/MyAkkaManager/MyAkkaWorker"]

i'm getting Processing Time & Time in Mailbox as zero and i can see some numbers on Mailbox Size.

if i change the filter like this

includes = ["myAkka/user/MyAkkaManager/MyAkkaWorker/*"]

i'm getting the values for all three.

**Comment by ksnagendran** [comment]
This is my akka conf

deployment {
			"/MyAkkaManager" {
				router = round-robin-pool
    			resizer {
      				lower-bound = 1
      				upper-bound = 5
      				messages-per-resize = 10
    			}
  			}
  			"/MyAkkaManager/MyAkkaWorker" {
				router = round-robin-pool
    			resizer {
      				lower-bound = 1
      				upper-bound = 5
      				messages-per-resize = 10
    			}
  			}
  		}

**Comment by ivantopo** [comment]
Hello @ksnagendran, I think there might be a little confusion here between actor metrics and router metrics. You asked about actors first, but I see from your config that your are actually deploying routers.. what exactly would you like to measure?

Also, I pushed an update to the docker image that fix the metric patterns to match those of Kamon 0.4.0, please ensure that you pull the latest image and try again!

**Comment by ksnagendran** [comment]
Hi @ivantopo, sorry for the late response.
Actually i'm trying to measure the actor metrics. So you are saying that the above code i shared, is measuring the router metrics?

Do you have any example code for play framework with the latest kamon 0.4.0. Which will be more helpful for the beginners like me.

Regarding docker, I pulled the latest and thanks

**Comment by shadeeka** [comment]
Hi all,
I am getting the same issue no actor metrics coming only the system metrics working
i am using kamon 0.5.1

val kamonVersion = "0.5.1"

 "io.kamon"    %% "kamon-core"           % kamonVersion,
  "io.kamon"    %% "kamon-statsd"         % kamonVersion,
  "io.kamon" %% "kamon-play-23" % kamonVersion,
  "io.kamon"    %% "kamon-log-reporter"   % kamonVersion,
  "io.kamon"    %% "kamon-system-metrics" % kamonVersion,
  "org.aspectj" % "aspectjweaver" % "1.8.1"

can anybody able to resolve this. please help. thank you

**Comment by hepin1989** [comment]
really？I do not have actor metric too with akka 2.4 rc2

**Comment by dpsoft** [comment]
Shadeeka,

how you are running the application? in this manner?

bin/myapp.sh -J-javaagent:/myapp/lib/org.aspectj.aspectjweaver-1.8.5.jar

also i don't see kamon-akka in your dependencies.

which output show the console reporter?

cheers,

Diego

**Comment by dpsoft** [comment]
Hi kerr,

how are you packaging the application? you are using sbt-native-packager?

cheers,

Diego

**Comment by hepin1989** [comment]
@dpsoft  yes,I have add the wave thing to the packge build.sbt,and i have debug the shell output too,I have reported that at the gitter,but seems you are offline that time.
I think everything I configurated ia dine,but it just not work for the actor side.

btw，thanks for the docker image and kamon,works so great。

**Comment by dpsoft** [comment]
kerr,

I will build a simple akka application with kamon and sbt-packager in order
to understand the issue, give me some minutes and i will be back with
something.

**Comment by dpsoft** [comment]
Kerr,

I' ve attached a simple akka example that contains kamon and sbt-native
packager and I could make it work in the following manner:

1. running  sbt stage
2. using the script generated ./ping-pong-example
*-J-javaagent:path-to-aspectjweaver.jar*
3. you should see something like this output indicating that the actor
metrics are running.


+-----------------------------------------------------------------------------------------------------------------------------------------+
|
                                                                |
|    Actor: kamon/user/metrics
                                                    |
|
                                                                |
|   Processing Time (nanoseconds)      Time in Mailbox (nanoseconds)
  Mailbox Size           |
|                          Msg Count: 8                          Msg Count:
8                        Min: 0               |
|                                  Min: 23168
 Min: 2146304                 Avg.: 0.0            |
|                      50th Perc: 25216                      50th Perc:
12845056                 Max: 8              |
|                       90th Perc: 10944512                   90th Perc:
13107200                                     |
|                       95th Perc: 10944512                   95th Perc:
13107200                                     |
|                  99th Perc: 10944512                   99th Perc:
13107200               Error Count: 0        |
|                    99.9th Perc: 10944512                 99.9th Perc:
13107200                                     |
|                                Max: 10944512                         Max:
13107200                                     |
|
                                                                |
+----------------------------------------------------------------------------------------------------------------------------------------+

I hope you help, and sorry for the late response.

Cheers,

Diego

**Comment by shadeeka** [comment]
Sorry for the late reply,
 as dpsoft said i have missed the kamon-akk in my dependencies. now i have added it. but still its same.
and for the aspectj i have added sbt-aspectj-runner in here
 https://github.com/kamon-io/sbt-aspectj-runner/tree/master/examples/kamon-play/project
It seems aspectj is running ok. and the output i got as follows. still no akka actor logs. I got only followings

![logs](https://cloud.githubusercontent.com/assets/6366358/10036403/fbdb9616-61c4-11e5-8101-2cac9dfb02d8.png)


Thanks for the help

**Comment by dpsoft** [comment]
@shadeeka how are you runnin the application? using aspectj-runner:run?

**Comment by shadeeka** [comment]
Yes.
I am using   " activator aspectj-runner:run" command to run my application.

**Comment by dpsoft** [comment]
You can share the application.conf?. Are you using play 2.4 or 2.3?

**Comment by shadeeka** [comment]
I am using play 2.3
Here is the application.conf

# This is the main configuration file for the application.

application.secret="YylNKRoqT@8VgtF[m3sX@fkn/=g4PM9nNTLkRC[KtJ_kLJX8_Gul_91K`j2S2>I>"
application.langs="en"
jvm.memory= "-Xmx2g -Xms1g"
logger.root=ERROR

# Logger used by the framework:
logger.play=INFO

# Logger provided to your application:
logger.application=DEBUG

redis.uri="redis://127.0.0.1:6379"

# Root logger:
logger.root=ERROR

# Logger used by the framework:
logger.play=INFO

ehcacheplugin=disabled

# Uncomment this for the most verbose Akka debugging:
akka {
  loglevel = "DEBUG"
  actor {
    debug {
      receive = on
      autoreceive = on
      lifecycle = on
    }
  }
  extensions = ["kamon.metric.Metrics","kamon.statsd.StatsD", "kamon.system.SystemMetrics", "kamon.logreporter.LogReporter"]
}
# Kamon Metrics
# ~~~~~~~~~~~~~~

kamon {

  metrics {
    tick-interval = 5 second
    akka-actor {
      includes = ["**/UserActor/*/SessionActor"]
    }
    akka-router {
      includes = ["**"]
    }
    akka-dispatcher {
      includes = ["akka.actor.default-dispatcher"]
    }
  }

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  statsd {
    # Hostname and port in which your StatsD is running. Remember that StatsD packets are sent using UDP and
    # setting unreachable hosts and/or not open ports wont be warned by the Kamon, your data wont go anywhere.
    hostname = "192.168.99.100"
    port = 8125

    # Interval between metrics data flushes to StatsD. It's value must be equal or greater than the
    # kamon.metrics.tick-interval setting.
    flush-interval = 10 second

    # Max packet size for UDP metrics data sent to StatsD.
    max-packet-size = 1024 bytes

    # Subscription patterns used to select which metrics will be pushed to StatsD. Note that first, metrics
    # collection for your desired entities must be activated under the kamon.metrics.filters settings.
    includes {
      actor = ["*"]
      trace = ["*"]
      dispatcher = ["*"]
    }
    subscriptions {
      histogram = [ "**" ]
      min-max-counter = [ "**" ]
      gauge = [ "**" ]
      counter = [ "**" ]
      trace = [ "**" ]
      trace-segment = [ "**" ]
      akka-actor = [ "**" ]
      akka-dispatcher = [ "**" ]
      akka-router = [ "**" ]
      system-metric = [ "**" ]
    }
    simple-metric-key-generator {
      # Application prefix for all metrics pushed to StatsD. The default namespacing scheme for metrics follows
      # this pattern:
      # application.host.entity.entity-name.metric-name
       application = "sense.fdi"
    }
    play {
      include-trace-token-header = true
      trace-token-header-name = "X-Trace-Token"
    }

    modules {
      kamon-statsd.auto-start = no
      kamon-log-reporter.auto-start = yes
      kamon-system-metrics.auto-start = no
      kamon-akka {
        auto-start = yes
        requires-aspectj = yes
        extension-id = "kamon.akka.Akka"
      }
    }
  }
}

Thanks

**Comment by dpsoft** [comment]
@shadeeka 
```
extensions = ["kamon.metric.Metrics","kamon.statsd.StatsD", "kamon.system.SystemMetrics", "kamon.logreporter.LogReporter"]
```
the extensions block is not  necessary from kamon 0.4.x.

kamon {
   ` metric.filters `{
     tick-interval = 5 second
     akka-actor {
     includes = ["**"]
    }
    akka-router {
      includes = ["**"]
    }
    akka-dispatcher {
      includes = ["akka.actor.default-dispatcher"]
    }
  }

pay attention in the highlighted line.(more info in the [docs])

[docs]: http://kamon.io/integrations/akka/actor-router-and-dispatcher-metrics/

**Comment by shadeeka** [comment]
got it .. will try without extensions
 thanks @dpsoft

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
