### ISSUE TITLE
Akka 2.4 support

### ISSUE THREAD

**Issue by kailuowang** [kamon-io/Kamon#224]
Akka reverted the ActorPath trait -> class change
https://github.com/akka/akka/commit/cef397d149a012f0696d2d8a1b757f52107881b3
so the current kamon-core_akka-2.4 % 0.4.1-35bb09838d1b0a2a1e36cd68c2db158b728a2981 is not compatible with Akka-2.4-M2
0.4.0, on the other hand is compatible with 2.4-M2

**Comment by ivantopo** [comment]
hey @kailuowang! You mean that plain Kamon 0.4.0 as currently available in public repos is compatible with 2.4-M2 without any sort of weird issues? great news! :D

**Comment by kailuowang** [comment]
Sorry I was totally unclear. I haven't verified that 2.4-M2 and 0.4.0 has no weird issue yet. This issue is more about the current snapshot of kamon-core_akka-2.4 is incompatible with Akka-2.4-M2. I will report kamon 0.4.0 working with Akka 2.4-M2 issues if I found any.

**Comment by mwz** [comment]
Hi @kailuowang, have you found any issues with 0.4.0 and 2.4-M2 so far?

**Comment by kailuowang** [comment]
No, haven't noticed any.

**Comment by raboof** [comment]
Kamon 0.5.2 (and master) still list akka 2.3 as the dependency - are you intending to upgrade?

**Comment by ivantopo** [comment]
Yes of course we plan to upgrade! as far as we know, akka-actor works just fine with the current Kamon version, but there are some issues related to akka-remote that we need to take care of before upgrading.

**Comment by agemooij** [comment]
Hi guys. Any update on this issue? 

We would like to use Kamon with Akka 2.4 and Spray 1.3.3, which already has an outdated dependency on Akka 2.3.x which our build replaces with a 2.4 dependency. So for now we would already be very happy with a list of known problems when running Kamon against Akka 2.4 so we can base our decisions on that.

**Comment by raboof** [comment]
I see the kamon-java8 branch at https://github.com/kamon-io/Kamon/tree/kamon-java8 is now on akka 2.4.1 - cool!

This issue is now closed - where can I track the status of this branch? Do we expect it in a release some time?

**Comment by dpsoft** [comment]
hey @agemooij  @kailuowang  @mwz @raboof! 0.6.0 will come out soon we are working on some changes in the akka instrumentation that is more like a huge rewrite once these changes are done we will publish snapshots for people to try it out and make sure it works nice and then publish, we also have bugfixes and improvements, the statsd module has been practically rewritten, new fluentd module, jmx module, kamon-autoweave(allow attach the AspectJ loadtime weaving agent to a JVM after it has started), Akka 2.4 support, new documentation... stay tuned for updates on that ;)

**Comment by agemooij** [comment]
@dpsoft thanks for the update!

**Side question inspired by the 0.6.0 news**: we are just starting work on a Prometheus exporter. Prometheus likes to pull metrics instead of having them pushed so we're exposing a Spray `/metrics` route and we're caching tick snapshots internally until Prometheus comes calling again. Any interest in making such a thing part of Kamon or is this better kept outside as a contrib module?

**Comment by dpsoft** [comment]
@agemooij sorry for the late response, I think that the exporter is more related with Prometheus than with kamon and maybe is  better kept outside as a contrib module. but @ivantopo WDYT?

BTW: the repo is private?

**Comment by ivantopo** [comment]
I also think that keeping separate! We could definitely host it under the kamon-io organization and include it's documentation on our website, that would be awesome! but definitely as a separate project. 

As a side note, I have been thinking a lot about even taking most of the core modules out into their own repositories! Each module evolves differently and trying to carry everything into a single train can be both good and bad.. for example, we have a few awesome contributions from @jozic in the kamon-statsd module, but there are some other changes the we want to include in kamon-akka before releasing 0.6.0.. if the modules were independent, all the awesome changes would already be out!... on the other hand, if modules start to have their own version numbering then it can be confusing for the users to know which versions to use for each Kamon version... this is what is is keeping me from doing it.

I think that from now on we should not accept more new modules into the Kamon repo but rather on separate repos under our organization (if the contributor wants, of course) and when we get closer to Kamon 1.0 we will pull modules out of Kamon, but we will see with time!

**Comment by dpsoft** [comment]
@agemooij the extension is this: https://github.com/MonsantoCo/kamon-prometheus

**Comment by agemooij** [comment]
That's not ours, but thanks for pointing out that is has finally gone open source on Github :smile: 

We knew such a thing existed but that epo was private until very recently. We are analyzing it now.
