### ISSUE TITLE
Kamon-Play is not compatible with Play 2.4.x

### ISSUE THREAD

**Issue by hossein761** [kamon-io/Kamon#225]
Kamon-Play uses NingWSPlugin which depends on Play 2.3.8.

**Comment by sunnykaka** [comment]
Look forward the updates.

**Comment by dpsoft** [comment]
@hossein761 @sunnykaka we published kamon 0.4.1-SNAPSHOT with support for Play 2.4.x and we make a example of usage. https://github.com/kamon-io/Kamon/tree/master/kamon-examples/kamon-play-example-2.4.x

**Comment by dpsoft** [comment]
merged to master c80f51c7bb98c1a42c04df11ba40cd301018c839
