### ISSUE TITLE
Kamon akka trace not propogated on ask callback

### ISSUE THREAD

**Issue by sambogoat** [kamon-io/Kamon#226]
The issue i see is fairly fundamental so it may well be related to the versions of Kamon and Akka i'm using.

The problem scenario can be reduced to the example of using the ask pattern given in the docs:
http://kamon.io/integrations/akka/automatic-trace-context-propagation/

For example:
```
val actor = sys.actorOf(Props(new Actor {
    def receive = {
      case "ping" =>
        // print here gives non-empty MetricsOnlyContext
        sender ! "pong"
    }
}))

val fut = Tracer.withNewContext("sample-trace") {
    // print here gives non-empty MetricsOnlyContext
    actor ? "ping"
  }.mapTo[String]

  fut.map { response =>
    // print here gives EmptyTraceContext
  }
```

Versions:
akka. version: 2.3.11
akka-http version: 1.0-RC4
kamon.version: 0.4.0

Included modules:
kamon-core
kamon-scala
kamon-akka

**Comment by ivantopo** [comment]
hey! quick question, are you running the app from SBT when it fails?

**Comment by sambogoat** [comment]
No I'm running as standalone app from a built jar.

**Comment by ivantopo** [comment]
Looking at your example code, where are you getting `responseFuture` from? is it the same as `val fut = Tracer....` or is it actually another Future?

**Comment by sambogoat** [comment]
Sorry yes my bad. It is the same future as fut. I've edited the ticket to correct this.

**Comment by ivantopo** [comment]
This is embarrassing, but the example is incorrect! It should be like this:

```
val responseFuture = Tracer.withNewContext("sample-trace") {
    (actor ? "Ask Message")
      .mapTo[String]
      .map { response =>
        // The same TraceContext available when asking
        // the actor is available when executing this callback.
      }
  }
```

The instrumentation will capture whatever context is available when the transformations (map, filter, flatmap...) are created and since the `.map(...)` call was being made outside the reach of the `Tracer.withNewContext(...)` block, there was no context to capture!

I'm so sorry for that, I'll update the site accordingly asap!

**Comment by sambogoat** [comment]
No problem - thanks for taking the time to look into this. 

Although, when i invoke the map inside the scope of ```Tracer.withNewContext { ..}``` an empty context is again printed:
 
  ```
Tracer.withNewContext("sample-trace") {
    println(Tracer.currentContext) // kamon.trace.MetricsOnlyContext@7ba5b6a7
    (actor ? "ping").map { _ =>
      println(Tracer.currentContext) // EmptyTraceContext
    }
  }
```

**Comment by ivantopo** [comment]
that can be something else then.. how are you packaging your app and how are you adding the `-javaagent` option with the AspectJ weaver?

**Comment by sambogoat** [comment]
Closing this ticket as the problematic token propagation across to the map closure is only evident when running in Eclipse. Running the example from the cmd line works as expected.

It is strange that token propagation when running in Eclipse is fine for ask pattern and scala future use-cases but not when mapping a future returned from using ask.   

But happy to accept to this not a problem with Kamon.
