### ISSUE TITLE
Ability to specify a HTTP proxy in the kamon-newrelic config

### ISSUE THREAD

**Issue by ausmarton** [kamon-io/Kamon#233]
I have been trying to use `kamon-newrelic`, which seems to work fine on my dev box. However, when I deploy the app to our private cloud, it's unable to connect to collector.newrelic.com; as our infrastructure requires the HTTP request to be routed through an HTTP proxy.

When using NewRelic's java agent, you can set the http proxy config in the `newrelic.yml` as follows:

```
proxy_host: hostname
proxy_port: 8080
proxy_user: username
proxy_password: password
```

`kamon-newrelic` doesn't seem to have a way to configure the HTTP proxy. Is there something I'm missing here?

I can see from [Agent.scala](https://github.com/kamon-io/Kamon/blob/master/kamon-newrelic/src/main/scala/kamon/newrelic/Agent.scala#L113) that there is no support for an HTTP proxy configuration as of now. Is this something that has been considered before?

**Comment by thjaeckle** [comment]
If you start your Java process with the Java HTTP proxy settings, it works (at least for me - here without authentication at the proxy):
```
-Dhttp.proxyHost=my.proxy.com -Dhttp.proxyPort=3128 -javaagent:./aspectj/aspectjweaver.jar
```
Authentication should also be possible (-Dhttp.proxyUser -Dhttp.proxyPassword).
But this is probably only good for testing purposes as you would not want to add the http proxy for your complete Java program, but just for the newrelic communication.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
