### ISSUE TITLE
Play trace name for emulated HEAD requests

### ISSUE THREAD

**Issue by magro** [kamon-io/Kamon#237]
As already stated in [docker-grafana-graphite/#16](https://github.com/kamon-io/docker-grafana-graphite/issues/16#issuecomment-125192083), HEAD requests for that no explicit route is configured are emulated by play by delegating to the related GET request without tagging the request. This is the 2.3.x [`GlobalSettings.onRequestReceived`](https://github.com/playframework/playframework/blob/2.3.x/framework/src/play/src/main/scala/play/api/GlobalSettings.scala#L79) implementation:

```scala
  def onRequestReceived(request: RequestHeader): (RequestHeader, Handler) = {
    val notFoundHandler = Action.async(BodyParsers.parse.empty)(this.onHandlerNotFound)
    val (routedRequest, handler) = onRouteRequest(request) map {
      case handler: RequestTaggingHandler => (handler.tagRequest(request), handler)
      case otherHandler => (request, otherHandler)
    } getOrElse {
      // We automatically permit HEAD requests against any GETs without the need to
      // add an explicit mapping in Routes
      val missingHandler: Handler = request.method match {
        case HttpVerbs.HEAD =>
          new HeadAction(onRouteRequest(request.copy(method = HttpVerbs.GET)).getOrElse(notFoundHandler))
        case _ =>
          notFoundHandler
      }
      (request, missingHandler)
    }

    (routedRequest, doFilter(rh => handler)(routedRequest))
  }
```

One consequence of this is that  `kamon.play.instrumentation.RequestInstrumentation.beforeRouteRequest` seems be called twice (not sure if this is an issue, I don't see any obvious one), another consequence is that the `kamon.play.DefaultNameGenerator` will use the `requestHeader.uri` for the trace name - which may lead to many traces (and in consequence to very high disk usage in graphite).

With play 2.4.x this issue remains, there the request handling is additionally done by [DefaultHttpRequestHandler.handlerForRequest](https://github.com/playframework/playframework/blob/2.4.x/framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala#L111).

**Comment by dpsoft** [comment]
@magro  Maybe overriding the ```onRouteRequest``` in order to find the equivalent GET and in this manner the request should be take the normal flow and must be tagged.
```scala
 override def onRouteRequest(req: RequestHeader) = {
    // Implement transparent HEAD handling.  If no handler is found, and the it's a HEAD requests, looks up a handler
    // for an equivalent GET request, and if found, wraps that in a HeadAction that blocks the response body but
    // sends all the same response headers.
    super.onRouteRequest(req) match {
      case None if req.method == "HEAD" => {
        super.onRouteRequest(req.copy(method = "GET")) match {
          case Some(wrapped: EssentialAction) => Some(new HeadAction(wrapped))
          case other => other
        }
      }
      case other => other
    }
  }
```
this implementation was taken from [here]

[here]: https://github.com/reactivemanifesto/website-manifesto/blob/master/app/Global.scala#L22

**Comment by magro** [comment]
@dpsoft Thanks for the hint! We don't need a quick fix because this is already solved in some other way. Here's the play issue I opened: playframework/playframework/issues/4896

**Comment by dpsoft** [comment]
@magro Awesome! look forward the updates.

**Comment by magro** [comment]
@dpsoft Btw, spray and akka-http set the `request.method` to `GET` for transparent HEAD requests. Not sure how kamon computes the trace name for spray/akka-http, but this might lead to undesired/unexecpted trace names.

**Comment by ivantopo** [comment]
We used to generate names using the http verb and the url but that is just a recipe for bad things... since 0.4.0 we use a default name of `UnnamedTrace` and the user has to change the trace name to whatever they want either using the traceName directive, providing a name generator or manipulating the TraceContext directly. So, this shouldn't be a problem now :).

**Comment by magro** [comment]
Ok, thanks for the hint @ivantopo! Users probably should be aware of transparent HEAD handling and the request method (GET), maybe it's worth mentioning this in the (kamon) documentation (but I don't have a strong opinion here).

**Comment by dpsoft** [comment]
@magro We are thinking in take the same approach to avoid the creation of undesired traces, grouping the traces that doesn't are tagged:  `UntaggedTrace`.

**Comment by magro** [comment]
@dpsoft You mean using UntaggedTraces instead of request method + request uri? Perhaps that's a good idea, the documentation then should explain what might be the cause for this.

**Comment by dpsoft** [comment]
@magro Yes, instead of request method + request uri the trace name would become in   `UntaggedTraces` and of course explain in the documentation which is the cause of this.

**Comment by dpsoft** [comment]
related to #239

**Comment by dpsoft** [comment]
In order to avoid the creation of undesired traces we will grouping the traces that doesn't are tagged as  `UntaggedTraces`.  We must document this behavior, for this we just open a new issue #239
