### ISSUE TITLE
Finagle tracing

### ISSUE THREAD

**Issue by benjumanji** [kamon-io/Kamon#238]
Hi!

I'd really like to use kamon with some of the twitter stack tools. I have taken a quick look at the tracing docs and I think to add finagle tracing info to kamon all I really need to do is find a way to convert finagle trace records into TraceInfo objects, and stick them _somewhere_. I can see how I can subscribe to tracing info, I just don't think there is a hook yet where I can feed trace info into kamon?

Would this be something that you were willing to support?

**Comment by ivantopo** [comment]
Hey Benjamin!

Can you explain in a bit more detail what you want to achieve? I'm not very familiar with Finagle, but as far as I know it's tracing capabilities are aligned with the capabilities of Zipkin which goes beyond what we currently have in Kamon... what we do now can be considered as a very lightweight tracing that lacks many of the things you can get from Finagle/Zipkin, like real distributed tracing and preserving causal relation between segments. 

Improving the tracing capabilities to get to those levels of detail is something we plan to do, but I'm not sure of how long will it take to do so. In the meantime, you can explore the awesome work [these guys] are doing and maybe even give it a try!

If you want to explore integrating Kamon with Finagle yourself I would recommend starting with the very basic stuff like getting some metrics out of it and then build on top of that to get more complex features working. We can certainly provide as much help as we can to build such a module that will certainly be a good thing for the project, but at the moment we don't have the capacity to support such module ourselves. Hope you decide to give it a try and share your work with the community!



[these guys]: https://github.com/ebuzzing/Kamon/tree/zipkin/kamon-zipkin

**Comment by benjumanji** [comment]
So effectively with a finagle client you have a stack of modules, one of these handles tracing. You can insert your own tracer, and the trait is effectively `trait Tracer(trace: Record)`, where `Record` looks something like a `TraceInfo`. So I was thinking, if you have cool plans to make cool reporting / dashboards or whatnot out of your trace info, it would be nice if I could make a finagle tracer that kicked out data into a kamon collector. In theory this should be that hard (he says). I ask basically because zipkin OSS seems to have crumpled a little of late, though I do note this project: http://openzipkin.github.io/zipkin/ has sprung up. I'll have a look at the project you referenced.

**Comment by benjumanji** [comment]
It should be noted that zipkin and tracing in finagle are not the same thing. The zipkin project really covers the collection and display of the tracing, but finagle will merrily allow you to send it's trace records anywhere your heart desires.

**Comment by jtjeferreira** [comment]
Hi @benjumanji 
I would tell you to look at the kamon-spray code, namely the instrumentation and do something similar regarding the creation of the TraceInfo. I guess since you already have a Record you dont need to instrument finagle code with aspectj.

**Comment by benjumanji** [comment]
@jtjeferreira, thanks for the suggestion! That code isn't too helpful because I don't need kamon's tracing infra, finagle manages that already (including chasing the context across threads). I want to make a trace info object directly with timings from finagle, otherwise I would need to essentially double up the work that has already been doing in implementing generic tracing in finagle.

**Comment by benjumanji** [comment]
Really what I want is for the trace module to expose the TraceInfo sink to interested clients.

**Comment by dpsoft** [comment]
@benjumanji I think that i understand that you want is something like :
```scala
Tracer.addTraceInfo(myAwesomeTraceInfo)
```
it is right?

**Comment by benjumanji** [comment]
Yep. Exactly.

**Comment by benjumanji** [comment]
If you'd be open to such a change, I will spend some time figuring out if the trace records and trace info bits really are compatible (right now I have only done some light source browsing), and probably make a PR to expose that in the trace module.

Thoughts?

**Comment by dpsoft** [comment]
@ivantopo  what do you think?

**Comment by adriancole** [comment]
note: there's a new module out there for sending externally defined (zipkin-like) trace data to zipkin. https://travis-ci.org/openzipkin/zipkin-reporter-java This is in use by the [new finagle plugin](https://github.com/openzipkin/zipkin-finagle), but separate so as to not drag in dependencies.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!

**Comment by adriancole** [comment]
if you could wait a week it would be 4 years since last comment!

**Comment by seglo** [comment]
I currently have a native Kamon Finagle client tracing instrumentation that works well. It's presently still baking in a private repo, but it would be wonderful to contribute it upstream as a `kamon-finagle` instrumentation at some point.
