### ISSUE TITLE
Toggling per-process and per-host metrics separately in configuration

### ISSUE THREAD

**Issue by tferi** [kamon-io/Kamon#243]
The system-metrics module provides useful metrics, but if `n` monitored application instances are running on a host, the host metrics are duplicated `n`-fold. It would be nice to allow enabling per-process and per-host metrics separately.

I'd like to keep the per-process metrics enabled in all applications, but collecting and dispatching the rest  in all apps is a waste of CPU cycles and I/O.
I don't know if this fits into your vision about where Kamon should be headed, but it would be a really useful addition for us.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
