### ISSUE TITLE
Improve Kamon tooling for tests, continuation of #202

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#248]
The core of this issue is the problem described in #202, that was already been somehow addressed with 026d7ae4ea90a5de74ecb91f9ebdd297f6987cb2 but still, I'm pretty sure we can do something better. Any feedback and ideas to improve test support should be tracked here.

**Comment by dpsoft** [comment]
related to commit a49f4138630a459ca7bf7309f114cdfcbbda2598

**Comment by lahirug** [comment]
I think it would be nice to comment on 202 how did you fix the issue and how to use kamon with tests. Sorry If I missed something.

**Comment by justinhj** [comment]
Agreed, I don't understand how we can use commit a49f413 to disable Kamon when we don't want it running.

Currently I maintain a Kamon wrapper which has null functions for all the instruments when Kamon is not initialized, but I'd prefer it if that functionality was in the Kamon library itself.
