### ISSUE TITLE
Create a "traditional" StatsD protocol implementation

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#249]
Our current implementation makes use of all the hacks available in the StatsD protocol to pack as much data as possible into the same UDP packet, this is really cool in the sense that it significantly reduces the network bandwidth usage while still reporting all the data we have but when a packet gets lost then the information that reaches StatsD is usually skewed and too inaccurate. I see two possible ways to improve the situation:
- pack less data in each packet, so that a packet lost wont be too bad.
- implement the TCP version and see how it behaves.

Of course, all configurable so that the user can decide what tradeoffs to make.

**Comment by jozic** [comment]
@ivantopo 
could you please check this commit in my repo
https://github.com/jozic/Kamon/commit/1f7816ac59b1b1096e22968cbb202de935be15d0 ?
and tell me if that would be a good/bad way to 
- support custom stasd senders (like the one i was talking in gitter channel)
- help to fix or just fix this issue

it's still WIP and i can add some docs and tests. right now i'm mostly interested in feedback regarding the implementation idea. Especially this part https://github.com/jozic/Kamon/commit/1f7816ac59b1b1096e22968cbb202de935be15d0#diff-29b538342281f6e130c71c8689f86040R62  
thanks

**Comment by jozic** [comment]
@ivantopo have you had a chance to check it out?

**Comment by jozic** [comment]
@ivantopo @dpsoft any progress on this front?

**Comment by dpsoft** [comment]
@jozic sorry for the late response :(. I've reviewed the WIP and I think that the taken approach is right, please go ahead. @ivantopo WDYT?

**Comment by jozic** [comment]
great. thanks @dpsoft 
I will continue moving this direction. Please let me know if something changes.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
