### ISSUE TITLE
Version 0.5.0 Only - kamon/util/GlobPathFilter : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by barnone** [kamon-io/Kamon#250]
Exact same problem as issue #168 that was resolved for 0.4.0 but appearing with with 0.5.0 release only.
If I downgrade to 0.4.0 the problem goes away. 
Using scala 2.11.6 and java 1.7.0_65-b17

**Comment by ivantopo** [comment]
Yeah, sorry about that... it has already been corrected by 1577aa9addb6c79d01f7261915b9e33b0c01fcd9 and 0.5.1 will have artifacts targeting Java 1.6 as we did before... In the meantime, we just published `0.5.1-3f0eaed8f0ac62057a9f515c62540f237cfd6c6e` in our snapshots repository, can you please give it a try and ensure that all is working as expected?

**Comment by barnone** [comment]
Works...thanks!
I'm looking forward to using 0.5.1 as it solves a number of issues we have and we cannot use snapshots for our releases.

**Comment by ivantopo** [comment]
Cool, 0.5.1 will be out this weekend so the wait wont be too long :)
