### ISSUE TITLE
kamon-akka-remote with akka-2.4.0-RC2 has some problem

### ISSUE THREAD

**Issue by andsoneat** [kamon-io/Kamon#257]
I tried to use kamon(0.5.1) with akka-2.4.0-RC2(including cluster-sharding) and experienced some problem.

First node of cluster worked fine. But Other nodes failed to join to cluster with Exception below.

------------------------------------------------------------------------------------------------------------------------------
ERROR akka.actor.ActorSystemImpl - Uncaught error from thread [actor-system-akka.remote.default-remote-dispatcher-8] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    akka/remote/instrumentation/TraceContextAwareWireFormats$AckAndTraceContextAwareEnvelopeContainer$Builder.setAck(Lakka/remote/WireFormats$AcknowledgementInfo$Builder;)Lakka/remote/instrumentation/TraceContextAwareWireFormats$AckAndTraceContextAwareEnvelopeContainer$Builder; @30: invokevirtual
  Reason:
    Type 'akka/remote/WireFormats$AcknowledgementInfo' (current frame, stack[1]) is not assignable to 'com/google/protobuf/GeneratedMessage'
  Current Frame:
    bci: @30
    flags: { }
    locals: { 'akka/remote/instrumentation/TraceContextAwareWireFormats$AckAndTraceContextAwareEnvelopeContainer$Builder', 'akka/remote/WireFormats$AcknowledgementInfo$Builder' }
    stack: { 'com/google/protobuf/SingleFieldBuilder', 'akka/remote/WireFormats$AcknowledgementInfo' }
  Bytecode:
    0x0000000: 2ab4 0014 c700 122a 2bb6 003d b500 0a2a
    0x0000010: b600 3ba7 000f 2ab4 0014 2bb6 003d b600
    0x0000020: 3c57 2a59 b400 1604 80b5 0016 2ab0
  Stackmap Table:
    same_frame(@22)
    same_frame(@34)

	at akka.remote.instrumentation.TraceContextAwareWireFormats$AckAndTraceContextAwareEnvelopeContainer.newBuilder(TraceContextAwareWireFormats.java:319) ~[actor-system.jar:]
	at akka.kamon.instrumentation.RemotingInstrumentation.aroundSerializeRemoteMessage(RemotingInstrumentation.scala:26) ~[actor-system.jar:]
	at akka.remote.transport.AkkaPduProtobufCodec$.constructMessage(AkkaPduCodec.scala:127) ~[actor-system.jar:]
...
..
.
------------------------------------------------------------------------------------------------------------------------------
I removed dependency for kamon-akka-remote and it works fine now.

**Comment by eiennohito** [comment]
One more instance of this problem.

**Comment by onexdrk** [comment]
+1

**Comment by Tolsi** [comment]
+1

**Comment by kailuowang** [comment]
This happens on 2.4.0 RC2, 2.4.0 RC3 and 2.4.0

**Comment by davidduus** [comment]
+1

**Comment by pawelkaczor** [comment]
+1

**Comment by kodemaniak** [comment]
+1
 
The same with the Akka 2.4.0 release and Kamon 0.5.2.

**Comment by nodefactory-bk** [comment]
Also doesn't work with akka 2.4.1, kamon 0.5.2

**Comment by raboof** [comment]
See also #224 and the https://github.com/kamon-io/Kamon/tree/kamon-java8 branch

**Comment by dpsoft** [comment]
related to #224

**Comment by xuweigui** [comment]
It doesn't work for me with akka 2.4.2 with either kamon 0.6.0 or 0.6.1

**Comment by ivantopo** [comment]
hello @xuweigui, please use `kamon-akka-remote_akka-2.4` if you are using Akka 2.4, thanks!
