### ISSUE TITLE
Multiple tags with same name

### ISSUE THREAD

**Issue by macobo** [kamon-io/Kamon#273]
One of the (great) features that datadog has is that a single metric can have a multiple tags with the same key.

Example from: http://docs.datadoghq.com/guides/tagging/#assigning-tags-using-the-configuration-files

``` region:east
region:nw
application:database
database:primary
role:sobotka
```

Can this be added to Kamon?

I'm not sure how to implement this without breaking the API as this would require a `MultiMap` to be used for tags.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
