### ISSUE TITLE
update kamon-newrelic related documentation

### ISSUE THREAD

**Issue by dpsoft** [kamon-io/Kamon#277]

**Comment by dpsoft** [comment]
https://github.com/kamon-io/Kamon/pull/228

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
