### ISSUE TITLE
Bug with Kamon and SPRAY and async/await, Context lost !!!

### ISSUE THREAD

**Issue by tobiaseriksson** [kamon-io/Kamon#285]
The following code results in a lost context/token

``` scala
post {
      path("car") {
        pathEnd {
          respondWithMediaType("application/vnd.api+json") {
            entity(as[String]) { body =>
              val context = Kamon.tracer.newContext("CreateResource-Context",Some("token-777"))
              Tracer.withContext(context) {
                logger.debug(s"Create resource of type 'car'")
                onComplete(
                  async {
                    Tracer.withContext[JValue](context) {
                      logger.debug("Create Resource " + Tracer.currentContext.name + " token " + Tracer.currentContext.token)
                      val res = justASimpleFunction()
                      val reg = await(aCallToAnAsyncFunction())
                      await(generateSomeJsonAsync(reg))
                    }
                  }
                ) { result => complete {
                  result match {
                    case Success(jsonBody) =>
                      new HttpResponse(201)
                        .withEntity(compact(render(jsonBody)))
                    case Failure(fail) =>
                      HttpResponse(500).withEntity("failed")
                  }
                }
                }
              }
            }
          }
        }
      }
    }
```

The output looks like this

``` bash
2015-11-16 16:27:08 *KANMON* [token-777] DEBUG [default-akka.actor.default-dispatcher-2] c.t.p.s.S.HttpServiceActor [SprayAndKamonTest.scala:91] Create resource of type 'car'
2015-11-16 16:27:08 *KANMON* [Tobiass-MacBook-Pro.local-1] DEBUG [ForkJoinPool-3-worker-15] c.t.p.s.S.HttpServiceActor [SprayAndKamonTest.scala:95] Create Resource UnnamedTrace token Tobiass-MacBook-Pro.local-1
```

As can be seen the second logger output does not have the correct KANMON Context and thus this must be a bug.

In fact commenting out the await code and replacing with a JSON object like this will make it work

``` scala
onComplete(
                  async {
                    // Tracer.withContext[JValue](context) {
                    Tracer.withContext(context) {
                      logger.debug("Create Resource " + Tracer.currentContext.name + " token " + Tracer.currentContext.token)
                     /* val res = justASimpleFunction()
                      val reg = await(aCallToAnAsyncFunction())
                      await(generateSomeJsonAsync(reg))
                      */
                     JField("car", List(JField("brand", JString("volvo")), JField("model", JString("V70")), JField("REG", JString("ABC-123"))))
                    }
                  }
                )
```

And as can be seen the output is now correct

``` bash
2015-11-16 16:41:32 *KANMON* [token-777] DEBUG [default-akka.actor.default-dispatcher-5] c.t.p.s.S.HttpServiceActor [SprayAndKamonTest.scala:91] Create resource of type 'car'
2015-11-16 16:41:32 *KANMON* [token-777] DEBUG [ForkJoinPool-3-worker-15] c.t.p.s.S.HttpServiceActor [SprayAndKamonTest.scala:96] Create Resource CreateResource-Context token token-777
```

So why?
Is this a known problem ?
Is it perhaps so that I am making a mistake ?
-Tobias

**Comment by ivantopo** [comment]
Hello Tobias, this certainly is not a known issue. What I find more interesting is that in the first case you are getting both your custom trace and the automatically generated trace from the spray instrumentation... I think that it shouldn't even be necessary to have the nested `Tracer.withContext {...}` that you are using there, as the Future instrumentation should already take care of carrying that for you... I will give it a try and update you, thanks for reporting!

**Comment by ddispaltro** [comment]
Are you using an AsyncAppender in your logback configuration, by chance?

**Comment by tojaish** [comment]
Hi Guys, This issue is happening to us as well in our Application. The Trace Context is not getting propagated. Is there any work going on this front ? or will it be a long time before this gets fixed ? Do  let us know, so that we can plan appropriately. ThnQ.

**Comment by shveik** [comment]
Hey @tobiaseriksson @ivantopo any activity on this issue? we are seeing a similar behavior as @tojaish described. are we using it wrong :) ? thanks!

**Comment by tobiaseriksson** [comment]
Hi
 No we had to work around it, and since then we have not bothered to pick this issue up
Not sure what we did now
-Tobias

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
