### ISSUE TITLE
NewRelic sensitive data

### ISSUE THREAD

**Issue by jsuchenia** [kamon-io/Kamon#286]
There is a missing switch that newrelic is publishing data without sensitive information.
My project is using it and NewRelic sensor is discarding an update from kmon

**Comment by ivantopo** [comment]
Hello there! I don't really understand what the problem is, can you please elaborate a bit more on what is expected to happen and what is happening?

**Comment by matwojcik** [comment]
Hi, I think what @jsuchenia means is HighSecurity mode in newrelic: https://docs.newrelic.com/docs/agents/manage-apm-agents/configuration/high-security-mode

When an account is set to accept high security only, it is unable to connect to newrelic using kamon - AgentShutdownRequiredException is thrown.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
