### ISSUE TITLE
akka-router metrics in LogReporter

### ISSUE THREAD

**Issue by kennethleider** [kamon-io/Kamon#287]
After wondering what I could not get the akk-router filter configured correctly,  I looked through the LogReporter source code, and determined that it is not configured to subscribe to or report on metrics with a category of "akka-router"

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
