### ISSUE TITLE
track-unmatched-entities doesn't work with Akka module

### ISSUE THREAD

**Issue by manub** [kamon-io/Kamon#289]
Steps to reproduce:
- Add `kamon-akka` to your application
- Don't provide `metric.filters`
- Don't override `track-unmatched-entities` (this is set to `yes` by the core `reference.conf`
- Create an `ActorSystem` after starting Kamon
- Check your log-reporter.

The ActorSystem doesn't get monitored, although it seems it should be as unmatched entities should be tracked.

As per conversation with @ivantopo on gitter, track-unmatched-entities should work as intended and should be defaulted as false.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
