### ISSUE TITLE
Class loading metrics should have no unit in kamon-system-metrics

### ISSUE THREAD

**Issue by Tenchi2xh** [kamon-io/Kamon#297]
The class loading metrics are wrongfully reported as being in bytes, but in reality they express a number of classes, so it should be declared as `UnitOfMeaurement.Unknown`

Relevant code: https://github.com/kamon-io/Kamon/blob/master/kamon-system-metrics/src/main/scala/kamon/system/jmx/ClassLoadingMetrics.scala#L31

**Comment by dpsoft** [comment]
@Tenchi2xh thanks for reporting this!!!

**Comment by Tenchi2xh** [comment]
@dpsoft You're welcome!
