### ISSUE TITLE
JRE fatal error when running several apps using kamon simultaneously on ubuntu

### ISSUE THREAD

**Issue by htch** [kamon-io/Kamon#303]
Not sure if it is a bug or just a misconfiguration, and whether it is a bug with kamon or with sigar (maybe). I put together a [test project](https://github.com/htch/kamon_test) for everyone interested to be able to reproduce this issue. You can see versions of scala, akka, kamon and other libraries in the repo, as well as an example of JRE error dump. Interestingly, this bug appears on ubuntu, but not on os x.

    $ uname -a
     Linux 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dpsoft** [comment]
@htch thanks for reporting this isssue, I was able to reproduce de issue in fedora, sounds like an issue with the Sigar library but we need time to research the source.

**Comment by htch** [comment]
The problem was that those apps tried to provision sigar library on the same fs path. In theory it should be easy enough to tell sigar-provisioner to use another path via any one of [these methods](https://github.com/kamon-io/sigar-loader/blob/master/core/src/main/java/kamon/sigar/SigarProvisioner.java#L52), yet somehow none of them worked for me, so I ended up changing home directory for every app (they are run by supervisord, so the default home directory is /), which worked OK.

It's a damn shame it took me so long to figure this out.

**Comment by dpsoft** [comment]
Pavel, thanks for sharing.

Cheers,

Diegol

**Comment by ivantopo** [comment]
hey @htch! There is a little thing to add: the kamon-system-metrics module is using [this config key](https://github.com/kamon-io/Kamon/blob/master/kamon-system-metrics/src/main/resources/reference.conf#L10) to set the folder where the native libraries will be extracted, that's why trying to use the methods provided by sigar-loader are not working, Kamon is using it in a very specific way. Hope it helps!

**Comment by htch** [comment]
@ivantopo thanks, that was really helpful.
