### ISSUE TITLE
Kamon Autoweave - AgentLoader doesn't attach Mac JVM properly

### ISSUE THREAD

**Issue by sergiotudela** [kamon-io/Kamon#307]
Hi guys,

#### Environment 
* OS: `Mac OS El Capitan`
* JRE: `1.8.0_51`
* Kamon Core: `0.6.0-a9d5c5c61f7e5e189bf67baee2b13e21ebbaaf73`
* Kamon Autoweave: `0.6.0-a9d5c5c61f7e5e189bf67baee2b13e21ebbaaf73`

#### Details
https://groups.google.com/d/msg/kamon-user/6z1A9J4gFeo/6Xnyfg_JDQAJ

#### Summary
Basically `AgentLoader` fails when try to attach the `JVM` when the platform is `Mac OS` https://github.com/kamon-io/Kamon/blob/master/kamon-autoweave/src/main/scala/kamon/autoweave/loader/AgentLoader.scala#L147

~~For some reason `BsdVirtualMachine` for `MacOS` doesn't return the public constructors when the `getConstructor` is invoked via reflection, however `getDeclaredConstructors` works properly (constructor class should marked as public then).~~ https://github.com/kamon-io/Kamon/issues/307#issuecomment-173585334

~~I'm going to push the fix on my repo.~~ Done.

**Comment by sergiotudela** [comment]
Can you take a look to my changes? and then PR.

**Comment by dpsoft** [comment]
@sergiotudela awesome!!! please make a PR and sign our [CLA] and we are good to go.



[CLA]:https://docs.google.com/forms/d/1G_IDrBTFzOMwHvhxfKRBwNtpRelSa_MZ6jecH8lpTlc/viewform

**Comment by sergiotudela** [comment]
@dpsoft Signed and PRd.

**Comment by sergiotudela** [comment]
More details about this issue,

`BsdVirtualMachine` class has defined the constructor in this way:

```java
BsdVirtualMachine(AttachProvider var1, String var2) throws AttachNotSupportedException, IOException {
...
}
```

As you can see, the constructor doesn't have the `modifier` (public, protected or private), that means `AgentLoader` can not instance `BsdVirtualMachine`, from http://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html

```
If a class has no modifier (the default, also known as package-private), it is visible only within its own package (packages are named groups of related classes — you will learn about them in a later lesson.)
```

For that reason we have to set the flag, `setAccesible`, to true via reflection.
