### ISSUE TITLE
AspectJ Weaver Missing with sbt-aspectj

### ISSUE THREAD

**Issue by Teots** [kamon-io/Kamon#313]
Hi,

I tried to follow your [Get Started](http://kamon.io/introduction/get-started/) guide in a minimal play application, but I cannot get it to work properly using sbt-aspectj. My example can be found [here](https://github.com/Teots/KamonTest). Whenever I execute `sbt run` I see the `AspectJWeaver Missing` warning. 

Any suggestions what I'm doing wrong?

**Comment by dpsoft** [comment]
@Teots we recommend for run play applications in dev mode use: https://github.com/kamon-io/sbt-aspectj-runner.

**Comment by Teots** [comment]
@dpsoft thx, I tried that already and got it to work in dev mode, but what do you recommend for production mode? 

I would really like to use the `javaOptions in run <++= AspectjKeys.weaverOptions in Aspectj` setting shown in the guide with `sbt-aspectj` to automatically add the `javaagent` parameter to the run script generated by the `sbt dist` command. Is this possible?

**Comment by dpsoft** [comment]
@Teots you can do this:

1. java -cp ".:lib/*" -javaagent:lib/org.aspectj.aspectjweaver-1.8.5.jar `play.core.server.NettyServer` if you have play 2.3.x
2. java -cp ".:lib/*" -javaagent:lib/org.aspectj.aspectjweaver-1.8.5.jar `play.core.server.ProdServerStart` for play 2.4.x
3. if you want add at you generated script by `sbt dist`: `yourGeneratedScript J-javaagent:aspectjweaver-1.8.5.jar`

**Comment by fiadliel** [comment]
Hi, for production mode, I would like to suggest a simple plugin available here: https://github.com/gilt/sbt-aspectjweaver

It is very simple, but should work quite well for setting up the Java agent in your production builds - it adds the appropriate jar file, and updates the start script to use it.
