### ISSUE TITLE
issue with akka metrics

### ISSUE THREAD

**Issue by mrsanuk** [kamon-io/Kamon#314]
Hi, I have issue with akka metrics, 
when I run my apps with ./activator run   nothing work
when ./activator run -Dkamon.auto-start=true -J-javaagent:./org.aspectj.aspectjweaver-1.8.2.jar - App sends only the system metrics and don't changes "application name"

my build file
 "io.kamon" %% "kamon-core" % "0.5.2",
  "io.kamon" %% "kamon-datadog" % "0.5.2",
  "io.kamon" %% "kamon-statsd" % "0.5.2",
  "io.kamon" %% "kamon-log-reporter" % "0.5.2",
  "io.kamon" %% "kamon-system-metrics" % "0.5.2",
  "io.kamon" %% "kamon-akka" % "0.5.2",
  "org.aspectj" % "aspectjweaver" % "1.8.2"
)
routesGenerator := InjectedRoutesGenerator

aspectjSettings

javaOptions <++= AspectjKeys.weaverOptions in Aspectj

fork in run := true

and application.conf
kamon {
  akka {

    ask-pattern-timeout-warning = off
  }
  metric.filters {
    akka-actor {
    includes = [ "**" ]
    excludes = []
    }
    akka-router {
    includes = [ "**"]
    excludes = []
    }
    akka-dispatcher {
    includes = [ "**"]
    excludes = []
    }
  }
  modules {
    kamon-akka {
    requires-aspectj = yes
    }
  }
  datadog {
    hostname = "127.0.0.1"
    port = 8125

    flush-interval = 5 seconds
    max-packet-size = 1024 bytes
    subscriptions {
      histogram = [ "**" ]
      min-max-counter = [ "**" ]
      gauge = [ "**" ]
      counter = [ "**" ]
      trace = [ "**" ]
      trace-segment = [ "**" ]
      akka-actor = [ "**" ]
      akka-dispatcher = [ "**" ]
      akka-router = [ "**" ]
      system-metric = [ "**" ]
      http-server = [ "**" ]
    }
    application-name = "MyApps"  

  }
    modules {
      kamon-datadog {
        requires-aspectj = no
        auto-start = yes
        extension-class = "kamon.datadog.Datadog"
    }
  }
}

I would like collect all metrics
I tryed it on 0.3.4 version and all worked

**Comment by dpsoft** [comment]
@mrsanuk is a play application?

**Comment by mrsanuk** [comment]
yes, it is play application

**Comment by dpsoft** [comment]
@mrsanuk prior to kamon 0.4.0 it was initiated automatically in play applications, but that has changed after that and now you need start kamon manually, take a look: https://github.com/kamon-io/Kamon/blob/master/kamon-examples/kamon-play-example/app/Global.scala#L22
