### ISSUE TITLE
NewRelic - Seems to always deliver appdex as 0?

### ISSUE THREAD

**Issue by renpillay** [kamon-io/Kamon#318]
I've set up traces in my Spray application using Kamon 0.5.2. The information goes to NewRelic without an issue - I can see correct tracenames, timings, etc. However - the appdex value reported in NewRelic is always 0. 

I've configured my my apdexT value as 0.1 in the config file (which should translate to 100ms). I can see several requests in the 80ms range, and my average response time across all requests is about 200 - so it shouldn't be 0.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
