### ISSUE TITLE
Play+Akka

### ISSUE THREAD

**Issue by tierhetze** [kamon-io/Kamon#319]
I know that issue is not new. Foud similar complains in other forums.
I unable to start as play app, or as akka app, when play used with akka.
I'd like to ask is this project in active state and if YES, then when it will be resolved?
I will spend yet one day to find the solution...
Thanks.

**Comment by dpsoft** [comment]
Hi @tierhetze you can try with this snapshot version:```0.6.0-2961cc2fff3f408dbce964ed8ec82998bc864186``` until next release.

**Comment by tierhetze** [comment]
Thanks.
Am 02.03.2016 15:46 schrieb "Diego Parra" <notifications@github.com>:
