### ISSUE TITLE
remotely deployed actors metrics are missing

### ISSUE THREAD

**Issue by UriShohet** [kamon-io/Kamon#326]
Hi,

I have a cluster with a master and 2 slaves, and I couldn't see the metrics of the remotely deployed actors in the Grafana UI. I tried following what @ivantopo said in https://groups.google.com/forum/#!searchin/kamon-user/remote/kamon-user/OhF4opREL_0/m7ky1e80mfsJ but this didn't help, so I tried to change the normalize strategy and then I could finally see the metrics.

Remote actors paths look like
akka.tcp://ActorSystemName@Slavehost1:2551/remote/akka.tcp/ActorSystemName@Masterhost:2551/user/master/myRouter/c10

Before the change the remote actor's metrics didn't get through because
the ':' after the Masterhost and everything that followed it was cut off.
A metric name in grafana would look like
ActorSystemName.slavehost1.akka-actor.ActorSystemName_remote_akka_tcp_ActorSystemNameMasterhostIP,
now it looks like
ActorSystemName.slavehost1.akka-actor.ActorSystemName_remote_akka_tcp_ActorSystemNameMasterhostIP-2551_user_master_myRouter_c4.errors

I've created a [pull request](https://github.com/kamon-io/Kamon/pull/325). Hopefully I didn't miss anything :-)

Kind regards,
Uri

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
