### ISSUE TITLE
error using kamon-akka-remote_akka-2.4 0.6.0 dependency

### ISSUE THREAD

**Issue by UriShohet** [kamon-io/Kamon#328]
Hi,

I'm trying to use the kamon-akka-remote_akka-2.4 0.6.0 dependency in a Gradle project:

compile 'io.kamon:kamon-akka-remote_akka-2.4_2.11:0.6.0'

and I'm getting an error:

Could not find io.kamon:kamon-akka_akka-2.4_2.11:0.6.0.

It seems to me that the POM of kamon-akka-remote_akka-2.4 incorrectly specifies kamon-akka_akka-2.4_2.11 as a dependency, instead of kamon-akka_2.11:

take a look here:

http://search.maven.org/#artifactdetails%7Cio.kamon%7Ckamon-akka-remote_akka-2.4_2.11%7C0.6.0%7Cjar

        <dependency>
            <groupId>io.kamon</groupId>
            <artifactId>kamon-akka_akka-2.4_2.11</artifactId>
            <version>0.6.0</version>
        </dependency>

The workaround is to define the dependency as

```
compile("io.kamon:kamon-akka-remote_akka-2.4_2.11:0.6.0") {
    exclude group:'io.kamon',module:'kamon-akka_akka-2.4_2.11'
}
```

Regards,
Uri

**Comment by Alien2150** [comment]
I think the issue is that a package is completly missing => Its pointing to kamon-akka_akka-2.4 Which only exists for Scala 2.10 with Versio 0.4 => "http://search.maven.org/#search%7Cga%7C1%7Ckamon-akka_akka-2.4"

**Comment by Alien2150** [comment]
Thanks Uri, 

i adopted that fix for SBT:  

 "io.kamon" %% "kamon-akka-remote_akka-2.4" % "0.6.0" exclude("io.kamon", "kamon-akka_akka-2.4_2.11"),

**Comment by dpsoft** [comment]
@UriShohet thanks for sharing!!!
