### ISSUE TITLE
ArrayIndexOutOfBoundsException: value outside of histogram covered range

### ISSUE THREAD

**Issue by matlik** [kamon-io/Kamon#332]
I recieved the following exception:

    java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range. Caused by: java.lang.IndexOutOfBoundsException: index 4614
        at org.HdrHistogram.AbstractHistogram.handleRecordException(AbstractHistogram.java:441)
        at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:433)
        at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:346)
        at kamon.metric.instrument.HdrHistogram.record(Histogram.scala:146)
        at kamon.trace.MetricsOnlyContext.finish(MetricsOnlyContext.scala:56)

Dependencies:

    object Versions {
      val akka = "2.4.2"
      val kamon = "0.6.0"
      val aspectjweaver = "1.8.6" // Should this be 1.8.8 ?
    }
    ...
    "io.kamon" %% "kamon-core" % Versions.kamon,
    "io.kamon" %% "kamon-scala" % Versions.kamon,
    "io.kamon" %% "kamon-akka" % Versions.kamon,
    "io.kamon" %% "kamon-newrelic" % Versions.kamon, 

This application is a long-running ETL that only runs for ~ 70 minutes before crashing due to this error.  We've configured Kamon to time our blocking IO as individual transactions reported to newrelic to help us understand inter-system performance characteristics.

I actually see this as being two bugs.  First is the IndexOutOfBoundsExeption.  Second, and more importantly, I think Kamon should re-evaluate its approach to error handling.  I've been shocked twice by the way Kamon caused my application to simply not work because of its own needs and behaviors (this error and the need to start Kamon at startup, even with dependencies and when testing)  My opinion is Kamon should never cause an application to degrade its service levels, logging its own failures (without spamming) while allowing the application to continue doing what it needs to do.  By its nature, Kamon is an observer of the system, but should go to great lengths to stay out of the applications way even if things go wrong.

**Comment by ivantopo** [comment]
Hey @matlik, thanks for reporting this! We already have this reported in #232 and one of the reasons this fix was delayed is because we will need to make some internal changes in order to fulfill the second item in this comment: https://github.com/kamon-io/Kamon/issues/232#issuecomment-143743541

This definitely needs to be addressed ASAP, I'll take it right away.
