### ISSUE TITLE
Cannot access TraceContext within futures

### ISSUE THREAD

**Issue by el-dom** [kamon-io/Kamon#337]
I'm using scala 2.11.8 and JDK 1.8.0_77 building a minimal project using the example from http://kamon.io/integrations/scala/automatic-trace-context-propagation-with-futures/
This results in an EmptyTraceContext within the Future. Accodring to the documentation the Context should be available within the Future as well.
One can reproduce this by running the attached minimalistic project which includes 
```"io.kamon" %% "kamon-core" % "0.6.0",
  "io.kamon" %% "kamon-scala" % "0.6.0",```
[kamontest.zip](https://github.com/kamon-io/Kamon/files/202644/kamontest.zip)
with 
```sbt -J-javaagent:org.aspectj.aspectjweaver-1.8.7.jar```
I've also tried using the kamon-autoweave module but it makes no difference.

**Comment by dpsoft** [comment]
Hi el-dom,

please try with this:

object KamonTest {
  def main(args: Array[String]) {
    Kamon.start()
    Tracer.withNewContext("sample-trace") {
      println(s"1 ${Tracer.currentContext}")
      // The same TraceContext available here,

      Future {
        // is available here as well.
        "Hello Kamon"

      }.map(_.length)
        .flatMap(len => Future(len.toString))
        .map(s => Tracer.currentContext)
        .map(println)
      // And through all async callbacks, even while
      // they are executed at different threads!
      println(s"2 ${Tracer.currentContext}")
    }
    println(s"KamonTest running Press RETURN to stop...")
    Console.readLine()
    Kamon.shutdown()
  }
}

you need wait to Kamon.shutdown() in order to gracefully close all the
kamon machinary ;).

Cheers,

Diego.

**Comment by markus1189** [comment]
Hi @dpsoft,

I have the same problem as @el-dom.  The output with your proposed change is:

```
[kamontest]> run
[info] Compiling 1 Scala source to /home/markus/repos/gkh/kamontest/target/scala-2.11/classes...
[warn] there was one deprecation warning; re-run with -deprecation for details
[warn] one warning found
[info] Running default.kamontest.KamonTest 
1 kamon.trace.MetricsOnlyContext@186d81a8
2 kamon.trace.MetricsOnlyContext@186d81a8
KamonTest running Press RETURN to stop...
EmptyTraceContext
```

so there still is no `TraceContext` inside the Future.
I tried it with scala `2.11.7` and
```
openjdk version "1.8.0_76"
OpenJDK Runtime Environment (build 1.8.0_76-00)
OpenJDK 64-Bit Server VM (build 25.76-b00, mixed mode)
```

**Comment by dpsoft** [comment]
please in build.sbt put *fork in run := true* that will do the trick ;).

Cheers,

Diego.

**Comment by markus1189** [comment]
Okay that does the trick for me.

**Comment by el-dom** [comment]
Thanks. That's working!
