### ISSUE TITLE
Play's application.conf ignored by Kamon when I load the kamon-akka module

### ISSUE THREAD

**Issue by gaelrenoux** [kamon-io/Kamon#343]
I have a Play application (with Scala). In one controller, I inject the actor system and start a few actors to accomplish background tasks.

I have just set up Kamon (0.6.0) with Statsd, Graphite and Graphana as the back-end. With these modules, everything works fine:
- kamon-core
- kamon-system-metrics
- kamon-scala
- kamon-play-24
- kamon-statsd

I use the aspectj-play-runner plugin and start my application with aspectj-runner:run. The Kamon.start() is in the Global.onStart(Application) method.

However, as soon as I add kamon-akka in my build.sbt, Kamon seems not to be able to read the configurations values in conf/application.conf any more. I have put a debug point in SimpleMetricKeyGenerator (when it reads "kamon.statsd.simple-metric-key-generator"):
- without kamon-akka, the values in configSettings are those coming from my configuration ;
- with kamon-akka, the values in configSettings are the defaut values.

Play still has access to the values in conf/application.conf, though.

**Comment by dpsoft** [comment]
@gaelrenoux the kamon-play-24 module have a guice [module] for autostarting, if you are starting kamon in your `Globa.onStart` you need disable the guice module with `play.modules.disable += kamon.play.di.KamonModule`. 
In relation to the configuration issue, sounds like a bug in the `aspectj-runner` plugin and I need some time to investigate. 

you can try with  `aspectj-runner:run -Dconfig.resource=application.conf



[module]: https://github.com/kamon-io/Kamon/blob/master/kamon-play-2.4.x/src/main/resources/reference.conf#L34

**Comment by gaelrenoux** [comment]
Thanks for the advice, I removed the Kamon.start and Kamon.stop.

I got some time to look a bit more into it, I uploaded a samle application [here](https://github.com/gaelrenoux/Kamon-issue-343). It works fine as is. But uncomment kamon-akka in build.sbt, and you have a problem on startup where it doesn't find application.conf.

I tried the following but it didn't help :
aspectj-runner:run -Dconfig.resource=application.conf
aspectj-runner:run -Dconfig.resource=conf/application.conf
aspectj-runner:run -Dconfig.resource=/full/path/to/conf/application.conf

**Comment by ozgunatacan** [comment]
This is probably related:
https://github.com/kamon-io/sbt-aspectj-runner/issues/5

**Comment by dpsoft** [comment]
@gaelrenoux sorry for the late response ;(, but If you run the example with ```aspectj-runner:run -Dconfig.file=conf/application.conf``` and everything is ok. 
I think that the issue is related to kamon and play DEV mode but I need more time to research.
