### ISSUE TITLE
Support SPM custom metrics

### ISSUE THREAD

**Issue by RadoBuransky** [kamon-io/Kamon#350]
I'd like to be able to send data points to SPM:
https://sematext.atlassian.net/wiki/display/PUBSPM/Custom+Metrics

**Comment by dpsoft** [comment]
@otisg  @qkoshelev ping!!!

**Comment by otisg** [comment]
@RadoBuransky & @dpsoft we'll start working on this next week.
How are you creating custom metrics that you'd like to send to SPM, @RadoBuransky ?
Using functionality described on http://kamon.io/core/metrics/core-concepts/ and http://kamon.io/core/metrics/recording-metrics/ ?

**Comment by RadoBuransky** [comment]
@otisg Too late, I removed Kamon from the project. But great news that you've started working on it.

**Comment by qkoshelev** [comment]
We support custom metrics now. Here is Demo example: https://apps.sematext.com/spm-reports/mainPage.do?selectedApplication=11336&r=akkaCustomMetricsReportPage&stickyFiltersOff=false To start sending metrics to SPM server `kamon.spm.subscriptions {...}` should be updated with: 

```
histogram       = [ "**" ]
min-max-counter = [ "**" ]
gauge           = [ "**" ]
counter         = [ "**" ] 
```

values.

**Comment by dpsoft** [comment]
related to https://github.com/kamon-io/Kamon/pull/387
