### ISSUE TITLE
Unable to find class 'akka.event.Logging.LogEvent'

### ISSUE THREAD

**Issue by fjcano-stratio** [kamon-io/Kamon#358]
Hello, 

It is regarding to issue https://github.com/kamon-io/Kamon/issues/183

I have tried with:

```
/usr/bin/java -Duser.dir=/opt/sds/XXXXX -Dlogger.file=/opt/sds/XXXXX/conf/logger/develop.logger.xml -Djava.security.policy=/opt/sds/XXXXX/conf/java.policy -Dconfig.file=/opt/sds/XXXXX/conf/XXXXX.conf -verbose:class -javaagent:/opt/sds/XXXXX/repo/org/aspectj/aspectjweaver/1.8.9/aspectjweaver-1.8.9.jar -classpath /opt/sds/XXXXX/conf:/opt/sds/XXXXX/lib/* -Dapp.name=run -Dapp.pid=8967 -Dapp.repo=/opt/sds/XXXXX/repo -Dapp.home=/opt/sds/XXXXX -Dbasedir=/opt/sds/XXXXX play.core.server.NettyServer
```

But, we are getting the error (the classes look like loaded (verbose class java arg)):

```
[Loaded akka.event.Logging$LogEvent from file:/opt/sds/XXXXX/lib/akka-akka-actor_2.11-2.3.13.jar]
...
[Loaded akka.event.Logging$LogEvent$class from file:/opt/sds/XXXXX/lib/akka-akka-actor_2.11-2.3.13.jar]
...
ERROR | 25-05-2016 11:25:18,419 | org.aspectj.weaver.bcel.BcelWorld | Unable to find class 'akka.event.Logging.LogEvent' in repository
java.lang.ClassNotFoundException: akka.event.Logging.LogEvent not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292)
...
```

Akka / Kamon dependencies

```
lib$ l|grep "akka\|kamon"
2.7M May 24 17:17 akka-akka-actor_2.11-2.3.13.jar
3.0M May 24 17:17 akka-akka-http-core-experimental_2.11-2.0.3.jar
2.3M May 24 17:17 akka-akka-http-experimental_2.11-2.0.3.jar
953K May 24 17:17 akka-akka-parsing-experimental_2.11-2.0.3.jar
 16K May 24 17:17 akka-akka-slf4j_2.11-2.3.13.jar
3.8M May 24 17:17 akka-akka-stream-experimental_2.11-2.0.3.jar
 46K May 25 11:01 kamon-akka-remote_2.11-0.6.1.jar
108K May 24 17:17 kamon-kamon-akka_2.11-0.6.1.jar
605K May 24 17:17 kamon-kamon-core_2.11-0.6.1.jar
7.1K May 24 17:17 kamon-kamon-scala_2.11-0.6.1.jar
 24K May 24 17:17 typesafe-ssl-config-akka_2.11-0.1.0.jar
```

Besides, we get:

```
ERROR | 25-05-2016 11:32:19,810 | org.aspectj.weaver.bcel.BcelWorld | Unable to find class 'akka.dispatch.Dispatcher.LazyExecutorServiceDelegate' in repository
java.lang.ClassNotFoundException: akka.dispatch.Dispatcher.LazyExecutorServiceDelegate not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292
...
ERROR | 25-05-2016 11:34:27,108 | org.aspectj.weaver.bcel.BcelWorld | Unable to find class 'scala.concurrent.impl.Future.PromiseCompletingRunnable' in repository
java.lang.ClassNotFoundException: scala.concurrent.impl.Future.PromiseCompletingRunnable not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292)
...
ERROR | 25-05-2016 11:34:36,417 | org.aspectj.weaver.bcel.BcelWorld | Unable to find class 'scala.concurrent.impl.Future.PromiseCompletingRunnable' in repository
java.lang.ClassNotFoundException: scala.concurrent.impl.Future.PromiseCompletingRunnable not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292)
...
```

Any ideas?

Thanks in advance,

**Comment by dpsoft** [comment]
@fjcano-stratio you are running other agent like new relic? I can try with this plugin [sbt-aspectj-runner]. 

[sbt-aspectj-runner]: https://github.com/kamon-io/sbt-aspectj-runner

**Comment by fjcano-stratio** [comment]
Hello @dpsoft ,

No, I have configured a single agent:
```
... -javaagent:/opt/sds/XXXXX/repo/org/aspectj/aspectjweaver/1.8.9/aspectjweaver-1.8.9.jar ...
```

Regarding the sbt-aspectj-runner:
- As far as I can see, it needs to run over sbt, not in a java standalone case:
```
/usr/bin/java -Duser.dir=/opt/sds/XXXXX ...
```
- In my case, I have a restriction for our integration flow => maven (it is a.. I know) and we need to use:

https://github.com/play2-maven-plugin/play2-maven-plugin

Any idea?

Thanks,

**Comment by ArturSoler** [comment]
I'm getting these messages as well (no other agent running apart from aspectj).

**Comment by dpsoft** [comment]
@ArturSoler @fjcano-stratio are using a fat/uber jar?

**Comment by fjcano-stratio** [comment]
Hello @dpsoft ,

No, I am using isolated/separated jars in lib folder:

EG for akka or kamon..:

```
lib$ l|grep "akka\|kamon"
2.7M May 24 17:17 akka-akka-actor_2.11-2.3.13.jar
3.0M May 24 17:17 akka-akka-http-core-experimental_2.11-2.0.3.jar
2.3M May 24 17:17 akka-akka-http-experimental_2.11-2.0.3.jar
953K May 24 17:17 akka-akka-parsing-experimental_2.11-2.0.3.jar
 16K May 24 17:17 akka-akka-slf4j_2.11-2.3.13.jar
3.8M May 24 17:17 akka-akka-stream-experimental_2.11-2.0.3.jar
 46K May 25 11:01 kamon-akka-remote_2.11-0.6.1.jar
108K May 24 17:17 kamon-kamon-akka_2.11-0.6.1.jar
605K May 24 17:17 kamon-kamon-core_2.11-0.6.1.jar
7.1K May 24 17:17 kamon-kamon-scala_2.11-0.6.1.jar
 24K May 24 17:17 typesafe-ssl-config-akka_2.11-0.1.0.jar
```

**Comment by dpsoft** [comment]
@fjcano-stratio can you provide us an simple example in order to reproduce the issue?

**Comment by sbuljat** [comment]
I'm having the same problem while running Docker image with aspectjweaver 1.8.10

For setting java agent I'm using this plugin: addSbtPlugin("com.lightbend.sbt" % "sbt-javaagent" % "0.1.1")

Any ideas how to fix this?

**Comment by ivantopo** [comment]
guys, I was investigating this issue a little but it seems like @sbuljat's and @fjcano-stratio's issues might not have the same root. I tried a simple template from activator, added native packager and sbt-agent, generated a docker image and I did found a different issue when initializing the loggers due to some aspectj issues, that was solved by adding `-Dorg.aspectj.tracing.factory=default`.. you can see that in the template: https://github.com/ivantopo/play-2.5-with-docker/blob/master/build.sbt#L22

It would be great if any of you can help us reproduce the issue and find a proper solution, looking forward to your input, regards!

**Comment by lukoyanov** [comment]
Thanks, @ivantopo! I had the same problem with BcelWorld and ClassNotFoundException when running app in prod mode (created with sbt dist):

`2017-05-08 12:47:52,047 - [ERROR] - from org.aspectj.weaver.bcel.BcelWorld in main
Unable to find class 'scala.concurrent.impl.Future.PromiseCompletingRunnable' in repository
java.lang.ClassNotFoundException: scala.concurrent.impl.Future.PromiseCompletingRunnable not found - unable to determine URL
	at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292)`

Adding `-Dorg.aspectj.tracing.factory=default` solved it

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
