### ISSUE TITLE
Counters not reset to zero

### ISSUE THREAD

**Issue by sunnylbk** [kamon-io/Kamon#359]
When using `kamon-0.6.1` counters to write metrics to influxdb, counters are not reset to zero after every flush interval. `value` keeps on increasing or remains the previous value if counter is not incremented within a particular flush interval. Find attached screenshot for the values collected.

Using the following configuration:

```
kamon {

  metric {

    # Time interval for collecting all metrics and send the snapshots to all subscribed actors.
    tick-interval = 10 seconds

  }

  statsd {

    # Interval between metrics data flushes to StatsD. It's value must be equal or greater than the
    # kamon.metric.tick-interval setting.
    flush-interval = 10 seconds

    # Max packet size for UDP metrics data sent to StatsD.
    max-packet-size = 1024 bytes

    # Subscription patterns used to select which metrics will be pushed to StatsD. Note that first, metrics
    # collection for your desired entities must be activated under the kamon.metrics.filters settings.
    subscriptions {
      histogram       = [ "**" ]
      min-max-counter = [ "**" ]
      gauge           = [ "**" ]
      counter         = [ "**" ]
      trace           = [ "**" ]
      trace-segment   = [ "**" ]
      system-metric   = [ "**" ]
    }

  }

  # modules can be disabled at startup using yes/no arguments.
  modules {
    kamon-system-metrics.auto-start = yes
    kamon-statsd.auto-start = yes
  }

}
```

<img width="295" alt="screen shot 2016-06-05 at 6 45 26 pm" src="https://cloud.githubusercontent.com/assets/3656481/15805647/5016f182-2b4e-11e6-8102-3a8b28920930.png">

**Comment by dpsoft** [comment]
@sunnylbk sorry for the late response, you can try downgrading the ```kamon``` version or check with ```tcpdump``` if the sent values to influx are correct?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
