### ISSUE TITLE
how to use gauge api in java?

### ISSUE THREAD

**Issue by dragontree101** [kamon-io/Kamon#360]
i want to use gauge api in java, but i found gauge method has serval api
i don't know how to use the gauge api

i only want to use a appname and  record this appname's queue size
``` Kamon.metrics().gauge(appname, ?).record(size); ```

but all gauge api must input other parameters, (etc: CurrentValueCollector) i don't know what's the mean of other parameters and how to input CurrentValueCollector parameter

and can i use api like this:
```Kamon.metrics().gauge(appname, new Gauge.CurrentValueCollector()).record(size);``` ?
and Gauge.CurrentValueCollector is an abstract.

i see scala use gauge api ```Kamon.metrics.gauge("uuid-gauge")(0L).``` i think ```uuid-gauge=appname``` and ```0L=size``` but java api i don't know how to use

**Comment by dragontree101** [comment]
my code is
```
int index = 0;
    while(index++<1000000) {
      Random random = new Random();
      int i = random.nextInt(100);
      Kamon.metrics().gauge("gauge", () -> 0).record(i);
      try {
        Thread.sleep(100);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
    }
```
but out put
```
   Gauges                                                  |
|                                        ----------                                                |
|  gauge                                                                                           |
|          Min: 0                      Average: 23.0                        Max: 99            
```
i don't what is average mean, if i int num sequence is ```5 10 15 13 21``` i only want to get 21, how can i use gauge api?

**Comment by dragontree101** [comment]
does kamon send data to statsd has ```|g```   likes ```gaugor:333|g```  
i read kamon source code, found only ```|ms``` and ```|c```  , does kamon not support origin statsd's gauge?

**Comment by dpsoft** [comment]
@dragontree101 plese take a look to this old thread: https://groups.google.com/forum/#!searchin/kamon-user/gauge/kamon-user/Ga6sxxQG0uQ/B4-CpzfhHW8J

**Comment by yinhua-dai** [comment]
@dragontree101 , did you figure out how to use the gauge API?
I saw below usage in scala, do you know what's the difference of it?
Kamon.metrics.gauge("uuid-gauge")(0L)
Kamon.metrics.gauge("uuid-gauge")(1L)
Kamon.metrics.gauge("uuid-gauge")(2L)
@dpsoft , I would appreciate if you can let me know what is the differences?

**Comment by lakshmirajagopalan** [comment]
@yinhua-dai It probably converts a Long to CurrentValueCollector through implicits.
