### ISSUE TITLE
UnsatisfiedLinkError (libsigar-amd64-linux.so: file too short) when the working directory is in the classpath

### ISSUE THREAD

**Issue by gaelrenoux** [kamon-io/Kamon#361]
I have a had this error plaguing my application for a while : whenever I stopped then restarted the application, I got an UnsatisfiedLinkError because of libsigar-amd64-linux.so (full stack-trace joined). When I checked the file, it was indeed empty (size 0 bytes). Deleting the libisgar file allowed the application to restart correctly.

I finally found out this was because my work folder was in the classpath for my application and I had kept the default configuration for the Sigar lib (sigar-native-folder = ${user.dir}"/native"). Therefore, in SigarProvisioner.provision(), the source that was loaded was not the one from within the kamon-io jar, but the one from my working directory - the same one as the target. And of course, it didn't work out that well.

I corrected that by removing the working directory from the classpath (didn't make sense in my case) but I wonder if others might have the same problem. I think it would be better if the SigarProvisioner deleted the target file before creating the source stream.

[stacktrace.txt](https://github.com/kamon-io/Kamon/files/311617/stacktrace.txt)

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
