### ISSUE TITLE
Play 2.5 support 

### ISSUE THREAD

**Issue by vishaljoshi** [kamon-io/Kamon#367]
I can see that the code is added for Play 2.5. when will the new version of kamon  come out ?

**Comment by dpsoft** [comment]
We just published a snapshot version that contains the latest in the master repo, please don't forget add our repo: ```"Kamon Repository Snapshots" at "http://snapshots.kamon.io"``` and the artifact is: ```0.6.2-bda51ea175d734025bf36abb0f8678a5d1c0959d```

**Comment by vishaljoshi** [comment]
oh great will test it out today
