### ISSUE TITLE
Add instrument name to record value in a Histogram error message

### ISSUE THREAD

**Issue by eiennohito** [kamon-io/Kamon#371]
Currently, it is "Failed to store value $value in HdrHistogram, please review your range configuration."

However, it is difficult to guess what caused it because there is no context and for gauges it occurs on kamon thread. 

Messages would be much informative if there would be a name of the instrument as well.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
