### ISSUE TITLE
separate the  play/akka/backends modules to  your own repositories

### ISSUE THREAD

**Issue by dpsoft** [kamon-io/Kamon#372]

**Comment by agarbutt** [comment]
This seems related to issue #410 [Support for Scala 2.12]

Also, it seems that there is a heavy dependency on Akka as a subsystem. 
Do you have a document that describes the strategy for updating / sync'ing the Akka versions for release?
I'd love to help with this as my groups have heavily invested in Akka and the Akka Http X releases.
