### ISSUE TITLE
No Actor metrics showing with for Akka

### ISSUE THREAD

**Issue by RaghvendraGarg** [kamon-io/Kamon#378]
Hi Kamon team,

I am trying to integrate Kamon with my Spring-boot akka application. 
below are the dependencies i am using 
`
<dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-actor_2.11</artifactId>
            <version>2.3.12</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-slf4j_2.11</artifactId>
            <version>2.3.12</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-testkit_2.11</artifactId>
            <version>2.4-M3</version>
        </dependency>
        <dependency>
            <groupId>io.kamon</groupId>
            <artifactId>kamon-core_2.11</artifactId>
            <version>0.6.2</version>
            <exclusions>
            <exclusion>
                <groupId>org.hdrhistogram</groupId>
                <artifactId>HdrHistogram</artifactId>
            </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.kamon</groupId>
            <artifactId>kamon-statsd_2.11</artifactId>
            <version>0.6.2</version>
        </dependency>
        <dependency>
            <groupId>io.kamon</groupId>
            <artifactId>kamon-akka_2.11</artifactId>
            <version>0.6.2</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>1.8.4</version>
        </dependency>
`
and my application conf looks like this 

`kamon {
  metric {
    tick-interval = 10 seconds
    disable-aspectj-weaver-missing-error = false
    track-unmatched-entities = yes
    filters {
      akka-actor {
        includes = ["ImportSystem/user/*"]
        excludes = []
      }
      akka-router {
        includes = ["ImportSystem/user/*"]
        excludes = []
      }
      akka-dispatcher {
        includes = ["ImportSystem/akka.actor.default-dispatcher","ImportSystem/blocking-io-dispatcher"]
        excludes = []
      }
      trace {
        includes = [ "**" ]
        excludes = [ ]
      }
    }
  }
  show-aspectj-missing-warning = yes
  statsd {
    hostname = "127.0.0.1"
    port = 8128
    flush-interval = 10 seconds
    max-packet-size = 1024 bytes
    subscriptions {
      akka-actor      = [ "**" ]
      akka-dispatcher = [ "**" ]
      akka-router     = [ "**" ]
    }
    includes {
      actor       = [ "*" ]
      trace       = [ "*" ]
      dispatcher  = [ "*" ]
    }
    metric-key-generator = kamon.statsd.SimpleMetricKeyGenerator
    simple-metric-key-generator {
      application = "import-processor-service"
      include-hostname = true
      hostname-override = none
      metric-name-normalization-strategy = normalize
    }
  }
  # modules can be disabled at startup using yes/no arguments.
  modules {
    kamon-log-reporter.auto-start = no
    kamon-system-metrics.auto-start = yes
    kamon-statsd.auto-start = yes
    kamon-statsd.requires-aspectj = no
    kamon-system-metrics.requires-aspectj = no
    kamon-log-reporter.requires-aspectj = no
  }
}
akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "DEBUG"
  jvm-exit-on-fatal-error = false
  actor {
    default-dispatcher {
      type = Dispatcher
      executor = "fork-join-executor"
      throughput = 2
      fork-join-executor {
        parallelism-min = 8
        parallelism-factor = 2.0
        parallelism-max = 64
      }
    }
  }
}
blocking-io-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 16
  }
  throughput = 1
}
akka.actor.deployment {
  /batchStatsBuncher {
    router = smallest-mailbox-pool
    nr-of-instances = 1
  }
  /routerActor {
    router = smallest-mailbox-pool
    nr-of-instances = 100
  }
  /validatorActor {
    router = smallest-mailbox-pool
    nr-of-instances = 100
  }
  /importConfigLookupActor {
    router = smallest-mailbox-pool
    nr-of-instances = 15
  }
}`

I can see metrics under akka-dispatcher, Dont know why but all my actors are shown under akka-router but nothing in akka-actor section.
 Can you please point out if i am missing any configuration. Thanks In advance

**Comment by dpsoft** [comment]
@RaghvendraGarg if you are using a routerr, metrics are not individually gathered per routee but rather as the whole router; that you see as processing time in the router is the time it takes to the routees to process the messages and, the routing time, is the time it took to the router to decide which routee to use, basically it just measures the routing logic execution time and if you have a router in which you manually create the routees (a group IIRC) then you can get metrics per routee
but if the router is automatically creating the routees then they are all tracked as a whole.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
