### ISSUE TITLE
Reading current tags in TraceContext

### ISSUE THREAD

**Issue by elm-** [kamon-io/Kamon#379]
Hello,

is there a reason why it is not possible to read the current tags / metadata in the context? If so, would there be something against adding it via a PR?

Best,
Elmar

**Comment by dpsoft** [comment]
@elm- I think that doesn't exist a reason to not read the current tags. Please feel free to make a PR.

**Comment by dpsoft** [comment]
related to https://github.com/kamon-io/Kamon/pull/386.
