### ISSUE TITLE
Dispatcher metrics are not being reported accurately

### ISSUE THREAD

**Issue by osbornk** [kamon-io/Kamon#380]
I am running a Play 2.4 application with Akka 2.4.4 in Scala and Kamon 0.62.
So, I have two active thread pools, the default Play Fork-Join-Pool ("application/akka.actor.default-dispatcher") and a custom thread pool defined in application.conf and fetched through this line of code:

val ec: ExecutionContext = actorSystem.dispatchers.lookup("auditlog-context")

auditlog-context {
  executor = "thread-pool-executor"
  throughput = 1
  thread-pool-executor {
    fixed-pool-size = 10
    fixed-pool-size = ${?audit_poolsize}
  }
}

My kamon.metric.filters looks like this:

akka-dispatcher.includes = ["application/akka.actor.default-dispatcher", "auditlog-context"]

The problem is that my custom thread pool never shows up in the logs and the default thread pool never increments.

This is what I always get on the default pool no matter how much activity I throw at it:

+--------------------------------------------------------------------------------------------------+
|  Fork-Join-Pool                                                                                  |
|                                                                                                  |
|  Dispatcher: application/akka.actor.default-dispatcher                                           |
|                                                                                                  |
|  Paralellism: 8                                                                                  |
|                                                                                                  |
|                 Pool Size       Active Threads     Running Threads     Queue Task Count          |
|      Min           1                 0                   0                   0                   |
|      Avg           1.0               0.0                 0.0                 0.0                 |
|      Max           2                 0                   0                   0                   |
|                                                                                                  |
+--------------------------------------------------------------------------------------------------+

For Play, the parallelism should also be 24, which is their defaults.

And I don't get any reporting for my custom pool.

Is there a bug in the dispatcher monitoring? Everything else is reporting fine.

**Comment by dpsoft** [comment]
@osbornk I've tested with this configuration and making a simple controller like this: 

```
class KamonPlayExample @Inject() (system: ActorSystem) extends Controller {

  val ec: ExecutionContext = system.dispatchers.lookup("play.akka.actor.auditlog-context")

  val logger = Logger(this.getClass)

  def sayHello = Action.async {
    Future {
      Thread.sleep(100)
      Ok("Say hello to Kamon")
    }(ec)
  }
}
```
with this configuration:
```
play {
 akka {
   actor {
     auditlog-context {
       executor = "thread-pool-executor"
       thread-pool-executor {
       fixed-pool-size = 10
     }  
   }
  }
 }
}

kamon {
...
   metric {
    filters {
      trace.includes = []
      akka-actor.includes = []
      akka-actor.excludes = [ "**" ]
      akka-dispatcher.excludes = [ ]
      akka-dispatcher.includes = [ "application/play.akka.actor.auditlog-context" ]
    }
  }
...
}

``` 
and using `ab` in order to generate requests `ab -c 5 -k -n 5000 http://localhost:9000/helloKamon`
and this is what I get:
```
+--------------------------------------------------------------------------------------------------+
|  Thread-Pool-Executor                                                                            |
|                                                                                                  |
|  Dispatcher: application/play.akka.actor.auditlog-context                                        |
|                                                                                                  |
|  Core Pool Size: 10                                                                              |
|  Max  Pool Size: 10                                                                              |
|                                                                                                  |
|                                                                                                  |
|                         Pool Size        Active Threads          Processed Task                  |
|           Min              10                  4                      4                          |
|           Avg              10.0                4.0                    4.0                        |
|           Max              10                  5                      5                          |
|                                                                                                  |
+--------------------------------------------------------------------------------------------------+

+--------------------------------------------------------------------------------------------------+
|  Thread-Pool-Executor                                                                            |
|                                                                                                  |
|  Dispatcher: application/play.akka.actor.auditlog-context                                        |
|                                                                                                  |
|  Core Pool Size: 10                                                                              |
|  Max  Pool Size: 10                                                                              |
|                                                                                                  |
|                                                                                                  |
|                         Pool Size        Active Threads          Processed Task                  |
|           Min              7                   2                      0                          |
|           Avg              9.0                 4.0                    4.0                        |
|           Max              10                  5                      5                          |
|                                                                                                  |
+--------------------------------------------------------------------------------------------------+

+--------------------------------------------------------------------------------------------------+
|  Thread-Pool-Executor                                                                            |
|                                                                                                  |
|  Dispatcher: application/play.akka.actor.auditlog-context                                        |
|                                                                                                  |
|  Core Pool Size: 10                                                                              |
|  Max  Pool Size: 10                                                                              |
|                                                                                                  |
|                                                                                                  |
|                         Pool Size        Active Threads          Processed Task                  |
|           Min              10                  0                      0                          |
|           Avg              10.0                3.0                    3.0                        |
|           Max              10                  5                      5                          |
|                                                                                                  |
+--------------------------------------------------------------------------------------------------+

```

**Comment by osbornk** [comment]
Thanks for looking into this. I replicated your test function into my application and I still did not get any statistics for my custom dispatcher. The default dispatcher does seem to increment now. But the custom dispatcher does not seem to function.  I am not sure why, but I will have to look into it later.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
