### ISSUE TITLE
Module kamon-elasticsearch got lost in 0.6.2

### ISSUE THREAD

**Issue by danischroeter** [kamon-io/Kamon#382]
the kamon-elasticsearch module seems to be removed from aggregate...

> danischroeter
> @danischroeter
> 15:54
> Hi Guys
> I just wanted to upgrade to kamon 0.6.2 and noticed there is no 0.6.2 for the elasticsearch module at http://repo1.maven.org/maven2/io/kamon/kamon-elasticsearch_2.11/ while all other modules exist.
> Could that be an issue in the maven repo or did something go wrong in the release build?
> Diego Parra
> @dpsoft
> 16:00
> I think that in the latest release we lost the kamon-elasticsearch module from aggregate: https://github.com/kamon-io/Kamon/blob/master/project/Projects.scala#L27 :worried: ... can you please open a issue with this?

**Comment by dpsoft** [comment]
related to https://github.com/kamon-io/Kamon/pull/383
