### ISSUE TITLE
Adding ForkJoinPool.getQueuedSubmissionCount

### ISSUE THREAD

**Issue by michaelmoss** [kamon-io/Kamon#390]
Curious if getQueuedSubmissionCount (https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html#getQueuedSubmissionCount--)  was intentionally omitted and what the thoughts might be on adding it in?

I'd do a quick PR by adding it here-ish: https://github.com/kamon-io/Kamon/blob/71e777ebec4f244f5233788fd8af2e062cf14f24/kamon-core/src/main/scala/kamon/util/executors/ExecutorMetricRecorder.scala#L62 but thought it might be better for someone more familiar with the project to add it in properly.

**Comment by dpsoft** [comment]
@michaelmoss please feel free to make a PR. ;)

**Comment by dpsoft** [comment]
related to https://github.com/kamon-io/Kamon/pull/392
