### ISSUE TITLE
Counter.collect is not thread safe

### ISSUE THREAD

**Issue by isaacl** [kamon-io/Kamon#393]
It looks like the Kamon Counter uses an unsafe method to reset and calculate sums. `collect()` uses `LongAdder.sumThenReset()`, and this method not safe during contention.  In particular, these lines:
```scala
sum += a.value;
a.value = 0L;
```
can lose data if the Cell is incremented concurrently.  Looks like LongAdder needs a CAS based method?

**Comment by dpsoft** [comment]
related to https://github.com/kamon-io/Kamon/pull/399

**Comment by dpsoft** [comment]
@isaacl we just published the Kamon [0.6.3] version with this fix. Thanks!!

[0.6.3]:http://search.maven.org/#artifactdetails%7Cio.kamon%7Ckamon-core_2.11%7C0.6.3%7C
