### ISSUE TITLE
0.6.2 Not reporting any actor metrics w/ Akka 2.4.5

### ISSUE THREAD

**Issue by Sushisource** [kamon-io/Kamon#397]
Using Scala 2.11.8 and just the simple log reporter, I'm currently unable to get it to report a single thing. AspectJ weaver (1.8.9) is definitely loaded - I don't see the big warning banner. I'm calling Kamon.start() just after my actor system is initialized (tried before, too). 

Here's my configuration:

```
kamon {
  metric.filters {
    akka-actor {
      includes = ["boxsystem/user/**"]
      excludes = ["boxsystem/system/**"]
    }

    akka-dispatcher {
      includes = ["boxsystem/akka.actor.default-dispatcher"]
    }
  }

  statsd {  
    hostname = "localhost"
    port = 8125
  }
}
```

At first I thought remoting was maybe interfering, but even with remoting totally disabled I'm still getting:
`[INFO] [09/28/2016 10:58:50.288] [kamon-akka.actor.default-dispatcher-3] [akka://kamon/user/kamon-log-reporter] No metrics reported`

Looks like everything is starting up properly:

```
INFO  [2016-09-28 10:58:10,220] [main] [-] [] Kamon: Initializing Kamon...
[INFO] [09/28/2016 10:58:10.434] [main] [StatsDExtension(akka://kamon)] Starting the Kamon(StatsD) extension
[INFO] [09/28/2016 10:58:10.524] [main] [LogReporterExtension(akka://kamon)] Starting the Kamon(LogReporter) extension
```

Note that manually adding a counter and incrementing it does show up, although, curiously, incrementing the counter once causes it to show in the first logging event as 2 and then 0 every time after that, so perhaps something is wiping data.

I'm happy to try out any suggestions, or collect more info.

**Comment by ivantopo** [comment]
hello @Sushisource!

> Note that manually adding a counter and incrementing it does show up, although, curiously, incrementing the counter once causes it to show in the first logging event as 2 and then 0 every time after that, so perhaps something is wiping data.

Things are indeed being cleaned on every tick and flushed to all subscribers, in your case the log-reporter and statsd. May I ask what environment are you running your application on? is it a Play application?, also, are you entirely sure that the counter was incremented only once and showed 2? that shouldn't be happening!

**Comment by Sushisource** [comment]
Thanks @ivantopo - I noticed the thing about flushing a bit after I posted, so that makes sense, but yeah it did seem to go straight to two. I can run a debugger and see if it was getting called twice for some reason.

This is on Fedora Linux, latest. It's not a Play app, it's composed of a few different services but this one is an akka backend with a Dropwizard frontend.

**Comment by Sushisource** [comment]
Yeah, turns out I was calling Kamon.start() and incrementing the counter twice. So that explains that. Still not collecting any akka statistics though.

**Comment by Sushisource** [comment]
I'm realizing this is actually because it's not getting the right config values. I choose configs for the actor system at startup-time, and it not getting the right config.

Unfortunately, AFAICT there's no way to tell Kamon which config to use.

**Comment by Sushisource** [comment]
I've got this working essentially by stuffing the config for kamon into an akka reference.conf file, which isn't really where I want it to be according to my project structure but it'll do for now.

The ability to call Kamon.start(config) would totally solve this for me as per #395

**Comment by Sushisource** [comment]
One last thing I'm gonna throw in here: Had this working when running directly out of intellij, but running from a jar doesn't produce the akka metrics. I confirmed the configuration is being loaded properly, so it seems the instrumentation simply isn't working. AspectJWeaver is being loaded just fine AFAICT.

**Comment by frossi85** [comment]
@Sushisource I had the same problem. I am using kaon autowave, when the app is runned using sbt works but If I run it using a jar generated with sbt assemble then not works. Also Kamon autowave shows a message that says that AspectJWeaver was loaded. @ivantopo or @dpsoft do you have some idea on what could be happening?

**Comment by dpsoft** [comment]
@Sushisource @frossi85 I just make an simple [example] using `kamon-autoweave` and `sbt-assemby` in order to make a fat jar. When  we do this, we need pay attention to the [merge strategy] for the `aop.xml` files. (this also apply when passing the `AspectjWeaver` as `javaagent`)
[example]:https://github.com/kamon-io/Kamon/tree/master/kamon-examples/kamon-autoweave-example
[merge strategy]: https://github.com/kamon-io/Kamon/blob/master/kamon-examples/kamon-autoweave-example/build.sbt#L28-L62

**Comment by Sushisource** [comment]
@dpsoft Thanks for the info -- I'm using Maven so I'd have to translate that to the equivalent for the Shade plugin. Does this apply regardless of if I have any aop.xml files defined (I don't).

**Comment by dpsoft** [comment]
@Sushisource please take a look to this thread: https://groups.google.com/d/msg/kamon-user/WdwOUYVlq6M/o7O46bm6AwAJ

**Comment by Sushisource** [comment]
@dpsoft That did it for me. Thanks! This sort of thing probably needs to be a lot more discoverable, though.

**Comment by frossi85** [comment]
@dpsoft thanks, now I got metrics from akka but is only showing a few of them related to Kamon internals I think. I used ** in all filters. Could be some other thing that could generate this scenario?

**Comment by frossi85** [comment]
What is really happening is that I only getting mailbox size and not time in mailbox and the other metrics. @dpsoft Do you have an idea on what is happening?

**Comment by dpsoft** [comment]
hey @frossi85  Unlike when you use the `Aspectjweaver as javaagent` when you use the `kamon-autoweave` the first thing that you must call is kamon.start in your main method before all.

**Comment by frossi85** [comment]
@dpsoft you mean doing something like this?

`object MyApplication extends App with LazyLogging {

  Kamon.start()

//Actor system creation goes here
}`

Because is that what I am doing

**Comment by dpsoft** [comment]
@frossi85 that is ok. I don't understand why you are getting mailbox size and not time in mailbox.. that is weird... and when you say other metrics, what do you mean?

**Comment by frossi85** [comment]
@dpsoft sorry for confusing you. With other metrics I mean things like processing time. I see processing time for some actors (kamon and system actors) but not for my own actor. Could be related to settings like flush-interval  and max-packet-size?

**Comment by dpsoft** [comment]
@frossi85 if you put :

```

metric.filters {
    akka-actor {
      includes = ["**"]
      excludes = [""]
    }
```
you don't see your actor?

**Comment by frossi85** [comment]
@dpsoft I see the actors but I can't see the same thing for different Actor. This is mi configuration:

`
kamon {

  metric {
    filters {
      akka-actor {
        includes = [ "telemetry-router-system/user/**" ]
        excludes = [ "*/system/**", "*/user/IO-**", "*kamon*", "*/kamon/*", "**/kamon/**", "kamon/**" ]
      }

      akka-router {
        includes = [ "telemetry-router-system/user/**" ]
        excludes = [ "*/system/**", "*/user/IO-**", "*kamon*", "*/kamon/*", "**/kamon/**", "kamon/**" ]
      }

      akka-dispatcher {
        includes = [ "telemetry-router-system/user/**" ]
        excludes = [ "*/system/**", "*/user/IO-**", "*kamon*", "*/kamon/*", "**/kamon/**", "kamon/**" ]
      }

      trace {
        includes = [ "**" ]
        excludes = [ ]
      }
    }
  }

  statsd {

    report-system-metrics = true

    # Hostname and port in which your StatsD is running. Remember that StatsD packets are sent using UDP and
    # setting unreachable hosts and/or not open ports wont be warned by the Kamon, your data wont go anywhere.
    hostname = ${?STATSD_HOST}
    port = ${?STATSD_PORT}

    # Subscription patterns used to select which metrics will be pushed to StatsD. Note that first, metrics
    # collection for your desired entities must be activated under the kamon.metrics.filters settings.
    subscriptions {
      histogram       = [ "**" ]
      min-max-counter = [ "**" ]
      gauge           = [ "**" ]
      counter         = [ "**" ]
      trace           = [ "**" ]
      trace-segment   = [ "**" ]
      akka-actor      = [ "**" ]
      akka-dispatcher = [ "**" ]
      akka-router     = [ "**" ]
      system-metric   = [ "**" ]
      http-server     = [ "**" ]
    }

    # FQCN of the implementation of `kamon.statsd.MetricKeyGenerator` to be instantiated and used for assigning
    # metric names. The implementation must have a single parameter constructor accepting a `com.typesafe.config.Config`.
    metric-key-generator = kamon.statsd.SimpleMetricKeyGenerator

    simple-metric-key-generator {

      # Application prefix for all metrics pushed to StatsD. The default namespacing scheme for metrics follows
      # this pattern:
      #    application.host.entity.entity-name.metric-name
      application = ${?HOSTED_GRAPHITE_API_KEY}.${?APPLICATION_NAME}

      # Includes the name of the hostname in the generated metric. When set to false, the scheme for the metrics
      # will look as follows:
      #    application.entity.entity-name.metric-name
      include-hostname = true

      # When the sections that make up the metric names have special characters like dots (very common in dispatcher
      # names) or forward slashes (all actor metrics) we need to sanitize those values before sending them to StatsD
      # with one of the following strategies:
      #   - normalize: changes ': ' to '-' and ' ', '/' and '.' to '_'.
      #   - percent-encode: percent encode the section on the metric name. Please note that StatsD doesn't support
      #     percent encoded metric names, this option is only useful if using our docker image which has a patched
      #     version of StatsD or if you are running your own, customized version of StatsD that supports this.
      metric-name-normalization-strategy = normalize
    }
  }

  modules {
    kamon-log-reporter {
      requires-aspectj = no
      auto-start = no
    }

    kamon-akka {
      requires-aspectj = yes
      auto-start = yes
    }

    kamon-scala {
      requires-aspectj = yes
      auto-start = yes
    }

    kamon-statsd {
      requires-aspectj = no
      auto-start = yes
      extension-class = "kamon.statsd.StatsD"
    }

    kamon-system-metrics {
      requires-aspectj = no
      auto-start = yes
      extension-class = "kamon.system.SystemMetrics"
    }
  }
}
`

**Comment by dpsoft** [comment]
@frossi85  if you are using a router, metrics are not individually gathered per routee but rather as the whole router; that you see as processing time in the router is the time it takes to the routees to process the messages and, the routing time, is the time it took to the router to decide which routee to use, basically it just measures the routing logic execution time and if you have a router in which you manually create the routees (a group IIRC) then you can get metrics per routee but if the router is automatically creating the routees then they are all tracked as a whole and maybe this is the confusion.

**Comment by frossi85** [comment]
@dpsoft when you mean router you mean [this](http://doc.akka.io/docs/akka/current/scala/routing.html) because I am not using akka Routing. Just having one actor that pull data from kafka and send it to a child actor, then in the end I implement the one actor per request pattern. The logic that I use is:

1- Use BackoffSupervisor to supervise KafkaConsumer actor
2- KafkaConsumer has only one intance, pull messages from Kafka and send it to next child actor called TelemetryDumperSupervisor,
3- TelemetryDumperSupervisor is just one instance created with context.actorOf. When this actor receives a message, it creates a new actor of type TelemetryDumper. When TelemetryDumper finish its jobs it kill it self.

So I am not creating an actor router specifically, I do not know if BackoffSupervisor does it or the actor per request pattern acts like one router from Kamon perspective.

**Comment by dpsoft** [comment]
@frossi85 sorry I suppose that you use a router because are in your config: 
```
  akka-router {
    includes = [ "telemetry-router-system/user/**" ]
    excludes = [ "*/system/**", "*/user/IO-**", "*kamon*", "*/kamon/*", "**/kamon/**", "kamon/**" ]
  }
```

**Comment by frossi85** [comment]
@dpsoft I put it there because I use it like a template for all services, and perhaps a service will use router. But I can remove it if you think that could be a problem.

**Comment by frossi85** [comment]
@dpsoft I found where is the issue, when you use the pattern actor per request, in each request you create and unnamed actor. Because you can have uniques names, then Akka creates a new name for each of those actors. That is translated to only one message per actor with unique name, so that not brings the metrics related to time because kamon does not have sufficient information about the processing time.

Will be good if Kamon is capable to detect actor per request pattern and try to put each actor instance metric under only one metric name. One option simple option is detect the akka naming (a, b, c...,z, A,B,....Z, aa,...) convention for one actor class and group all metrics under the same name, for example the first one "a".

Here you have a sample project: https://github.com/frossi85/akka-kamon-sample/tree/master
It contains the similar actor hierarchy and usage that I have in my project. "master" branch is using the actor per request and only reporting mailbox-size. In branch "working" I replaced the actor per request pattern to use always the same actor and the all metrics appear.

**Comment by dpsoft** [comment]
hey @frossi85 thanks for digging in this issue... and yes we need add support for actor groups metrics. please take a look to [this] issue.

[this]: https://github.com/kamon-io/Kamon/issues/101

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
