### ISSUE TITLE
Consider modifying GenericEntityRecorder to support subclassing

### ISSUE THREAD

**Issue by dspasojevic** [kamon-io/Kamon#398]
Currently `GenericEntityRecorder-register` has `private` visibility which means that subclasses of `GenericEntityRecorder` that want to add new instrument types can not register those instruments for cleanup and `collect` must also be overridden to collect from the private `instruments` and wherever the added instruments are stored.

Making `register` protected would solve these two issues and ease the creation of new, custom instruments.

**Comment by ivantopo** [comment]
hey @dspasojevic, could you please tell us a bit about what kind of instruments you would like to add? there are a couple changes coming into this particular are in Kamon and we would like to know more about what our users need :).

**Comment by dspasojevic** [comment]
Hi @ivantopo. We would like to have a strict histogram available for metrics with low volumes but a high precision - beyond what can be achieved by tuning the quantisation parameters.

We are happy to implement it in our codebase but it would be nice if plugging it into the `GenericEntityRecorder` was easier.

**Comment by ivantopo** [comment]
then, the interface of the histogram would be exactly the same than the histogram we already have, yould would just need a different implementation rather than the one bundled in Kamon?

**Comment by dspasojevic** [comment]
Yep, correct. Simple to do, but increasing the visibility of the `register` method in the `GenericEntityRecorder` will let us register it for collection and cleanup.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
