### ISSUE TITLE
Add import statements to codeblocks on Kamon website

### ISSUE THREAD

**Issue by zainab-ali** [kamon-io/Kamon#400]
Looking at the code blocks on the [Kamon site](http://kamon.io/introduction/get-started/), it's hard to see what imports are necessary.  Import statements at the top of each code block could be helpful. e.g.

```
import kamon._
import kamon.metric._
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
