### ISSUE TITLE
Getting iIllegalAccessError when used kamon to collect metrics of a cassandra cluster

### ISSUE THREAD

**Issue by parekuti** [kamon-io/Kamon#408]
[ERROR] [10/19/2016 11:23:26.063] [kamon-akka.actor.default-dispatcher-2] [ActorSystem(kamon)] Uncaught error from thread [kamon-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.IllegalAccessError: tried to access field org.HdrHistogram.AtomicHistogram.counts from class org.HdrHistogram.ModifiedAtomicHistogram
    at org.HdrHistogram.ModifiedAtomicHistogram.countsArray(ModifiedAtomicHistogram.scala:27)

**Comment by parekuti** [comment]
DSE version : 4.8.6
Spark version: 1.4.1
Akka: 2.3.15
Kamon: 0.6.3

**Comment by dpsoft** [comment]
@parekuti that is really weird.... which JDK version are you using? you can try with other kamon version?

**Comment by parekuti** [comment]
JDK 1.8 version, and also tried with Kamon 0.6.0 version.

Let me know if there is any specific version of Kamon I should be using for this.

**Comment by dpsoft** [comment]
@parekuti I can't reproduce this issue, can you check if you have other version of the `org.hdrhistogram` dependency in your classpath?

**Comment by parekuti** [comment]
@dpsoft  In the build.sbt file I used shaderule to override the  org.hdrhistogram version as below,
<ShadeRule.rename("org.hdrhistogram.HdrHistogram.**" -> "filodb.org.hdrhistogram.HdrHistogram.@1").inAll>

**Comment by dpsoft** [comment]
@parekuti filodb are using kamon internally and if you are using a diferent kamon versión that filo, you can get errors like this ;).

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
