### ISSUE TITLE
kamon-remote does not propagate trace context with akka 2.4.11+

### ISSUE THREAD

**Issue by tabdulazim** [kamon-io/Kamon#411]
I am using kamon-akka-remote_akka-2.4 in production, when using remote/cluster actors the trace context does not get propagated with akka 2.4.11+.

When I downgrade to akka 2.4.10 the trace context is being propagated correctly with any later akka version the trace is just empty.

**Comment by sjoerdmulder** [comment]
Maybe it's related with the new Remoting they introduced: http://akka.io/news/2016/09/30/akka-2.4.11-released.html#new-remoting causing some internal akka refactoring breaking the AspectJ hooks

**Comment by sjoerdmulder** [comment]
`senderOption:      Option[ActorRef],` in `constructMessage()` changed to `senderOption:      OptionVal[ActorRef],` probally causing the incompatibilities. I could make a PR but i'm not familair with back-compat stuff and AspectJ. Could we add both `@Pointcut` for old and new code?

**Comment by dpsoft** [comment]
@tabdulazim please go ahead!!!. But please make the PR here: https://github.com/kamon-io/kamon-akka-remote we are separating our projects in their own repositories.
