### ISSUE TITLE
gradle support

### ISSUE THREAD

**Issue by kknd22** [kamon-io/Kamon#413]
Is there any **gradle** support for aspectj - specifically the sbt equivalent **aspectj-play-24-runner** plugin support for gradle?

Even if the plugin doesn't exist, is there any work around for the gradle-scala based project?
Thanks
-Chris L.

**Comment by dpsoft** [comment]
@kknd22 I think that what you need is only pass the `AspectJWeaver` as `javaagent` with `gradle`

[here] an example

[here]: https://github.com/jwilsoncredera/spring-aop-blog/blob/master/spring-aop-aspectj-ltw/build.gradle

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
