### ISSUE TITLE
Clarifying System and JVM metrics docs

### ISSUE THREAD

**Issue by macobo** [kamon-io/Kamon#417]
Hi, http://kamon.io/integrations/system-metrics/system-and-jvm-metrics/ mentions the following:

```
garbage-collection-time: a gauge tracking the time spent in garbage collections, measured in milliseconds.
```

Say I graph this in datadog, what does this represent? What is the unit of time per which 3.95ms of garbage collecting happened in the screenshot below?

![image](https://cloud.githubusercontent.com/assets/148820/20964100/de4677fa-bc78-11e6-94a3-e947ab47e430.png)

**Comment by dpsoft** [comment]
@macobo that metric is calculated as delta between each cg run: https://github.com/kamon-io/kamon-system-metrics/blob/master/src/main/scala/kamon/system/jmx/GarbageCollectionMetrics.scala#L36. I see in your graph that you have an avg?

**Comment by macobo** [comment]
So in this case, this would be `no of milliseconds spent in gc per 100 ms of real time` (gauge default interval)? If so, then how can the number be above 100 in the above graph? Bad data, something else?

Yeah, the average is for averaging together statistics from multiple jvms, datadog doesn't really provide another option I think (besides sum, which wouldn't be useful here).

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
