### ISSUE TITLE
Getting kamon-log-reporter to Scala 2.12

### ISSUE THREAD

**Issue by akauppi** [kamon-io/Kamon#424]
It would be great if a version `0.6.5` (on par with current Kamon core which is available for Scala 2.12) was released, and published to Maven Central.

Here is the state today (29-Dec-16):

kamon-log-reporter has `crossScalaVersions` including 2.12.0 ([line](https://github.com/kamon-io/kamon-log-reporter/blob/master/project/Settings.scala#L33)), but running `sbt +publishLocal` fails, due to missing dependencies:

```
$ sbt +publishLocal
...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.kamon#kamon-core_2.12;0.6.3: not found
[warn] 	:: org.scalatest#scalatest_2.12;2.2.4: not found
[warn] 	:: com.typesafe.akka#akka-testkit_2.12;2.3.14: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

To fix this:

- `kamonVersion` should be updated to 0.6.5
- `akkaVersion` should be updated to 2.4.16 (>= 2.4.14)
- `scalatest` should be updated to 3.0.1

Within `project/Settings.scala`, I noticed:

- `-Yinline-warnings` is not recognized by Scala 2.12
- `-optimise` is deprecated in Scala 2.12
- `-target:jvm-1.6` gives a warning on Scala 2.12 (for obvious reasons): forces target to JVM8
 
Supporting both Scala 2.10 and 2.12 might not be possible, or at least easy. `akka-testkit` is available for Scala 2.12 since 2.4.14 but Scala 2.10 is support ends in the 2.3.x series.

---

My changes are in the [scala-2.12](https://github.com/akauppi/kamon-log-reporter/tree/scala-2.12) branch. It compiles and publishes, but I thought it best not to make a PR for such an essential version bump thing that probably needs to be done at the right time - and especially since it cuts out 2.10 support.

**Comment by cory-p-oncota** [comment]
See [here](https://github.com/kamon-io/kamon-scala/blob/master/project/Dependencies.scala) for a pattern that supports the matrix of Scala/Akka versions. I followed this pattern from the kamon-core and have been getting PRs moved along for 2.12 compatibility in other modules.

**Comment by dpsoft** [comment]
@akauppi @cory-p-oncota done wiht:: https://github.com/kamon-io/kamon-log-reporter/commit/e4713f047061e97c88be89db0f1b17bd3cdceca7

**Comment by akauppi** [comment]
Looks awesome. Nice way to keep supporting older Scala, too. Will try at work next year - Happy New Year!
