### ISSUE TITLE
Provide initial value for configProvider

### ISSUE THREAD

**Issue by andrebeat** [kamon-io/Kamon#426]
With #403 there was a behavior change and it's now impossible to use the Kamon metrics API (e.g. `Kamon.metrics.shouldTrack`) if Kamon hasn't started since an exception is thrown. 

A quick way to fix this would be to set a default value for [`configProvider`](https://github.com/kamon-io/Kamon/blob/master/kamon-core/src/main/scala/kamon/Kamon.scala#L66). Maybe changing it to `private[kamon] var configProvider: Option[ConfigProvider] = Some(new KamonDefaultConfigProvider())`.

**Comment by ivantopo** [comment]
in which version are you getting errors? once #422 gets merged it shouldn't be a problem, I just tried it and it just works.

**Comment by andrebeat** [comment]
I'm using version `0.6.5`. I agree that #422 should fix it.
