### ISSUE TITLE
kamon-spm: replace spray with akka-http v10

### ISSUE THREAD

**Issue by pjfanning** [kamon-io/Kamon#427]
Spray is no longer maintained and it should be relatively straightforward to swap out the Spray Client code and replace with Akka Http.

**Comment by pjfanning** [comment]
@agarbutt yes, my proposal is that we use Akka-Http client functionality instead of Spray.
The main reason is not to rely on unmaintained libraries,
In practice, I think more people will be using Kamon to monitor Akka-Http than Spray applications and an advantage here is that they won't need to have Akka-Http and Spray libraries on their classpath.
I'm having a look at putting together a pull request.

**Comment by pjfanning** [comment]
@agarbutt I'm wondering if maybe it would be better to use a neutral http client eg Apache HttpClient or HttpAsyncClient. Thinking about it again, if I switch kamon-spm to use Akka-Http client then that will introduce a dependency on akka 2.4.x and this could cause problems for users of Spray.

**Comment by pjfanning** [comment]
I have the basic implementation at https://github.com/pjfanning/kamon-spm/tree/akka-http-client - in the implementation, I just need to get the HTTP retries working and on the test side, I need to complete the rewrite to use a mocked Http Client.
I'm still tempted to switch tack and use Apache HttpAsyncClient instead.

**Comment by agarbutt** [comment]
@pjfanning Good points.  However, remember, that Kamon is Akka based, so that dependency comes along anyway.  It would be worth considering the major dependency matrix that Kamon wants to support.  @ivantopo , @dpsoft Thoughts?

Also, a suggestion for you @pjfanning, I would move this thread to the kamon-spm repository.

**Comment by pjfanning** [comment]
@agarbutt kamon-spm module does not have Issues enabled

**Comment by pjfanning** [comment]
https://github.com/kamon-io/kamon-spm/issues/3
