### ISSUE TITLE
Allow a Future[Long] value in CurrentValueCollector in Gauge

### ISSUE THREAD

**Issue by oripwk** [kamon-io/Kamon#431]
Hi,

It seems to me that having a `Long` `CurrentValueCollector` has little to no value in a reactive environment such as Play/Akka. In most cases, value collectors will return `Future`s. For example: gauging a how many people are managers in `Persons` collection in MongoDB using ReactiveMongo:

```scala
Kamon.metrics.gauge("managers", Kamon.metrics.settings.tickInterval) {
  collection.count(Some(Json.obj("type" -> "manager"))).map(_.toLong)
}
```

The above code won't compile because it returns `Future[Long]` instead of `Long`.

Of course, this can be solved by using `Await.result()`, but this is really a bad practice because it blocks the thread.

On the other hand, implementing it in Kamon with a `Future` is quite straightforward:
Inside `kamon.metric.instrument.HistogramBackedGauge`, implement `refreshValue` method like this:
```scala
def refreshValue(): Unit =
  currentValueCollector.currentValue.map(underlyingHistogram.record)
```
instead of this:
```scala
def refreshValue(): Unit =
  underlyingHistogram.record(currentValueCollector.currentValue)
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
