### ISSUE TITLE
Kamon 0.6.6 not available in 

### ISSUE THREAD

**Issue by zettelmj** [kamon-io/Kamon#432]
Seems that this job failed: https://travis-ci.org/kamon-io/Kamon/builds/193549091
Hence no artifact for kamon 0.6.6 is available on maven central:

https://mvnrepository.com/artifact/io.kamon/kamon-core_2.11
https://mvnrepository.com/artifact/io.kamon/kamon-core_2.12

**Comment by ivantopo** [comment]
that was an issue with tests, but definitely not the reason why artifacts are not in central... now we are going through bintray and we don't have all setup to sync to central yet, but you can find everything here: https://bintray.com/kamon-io/releases

Just add `Resolver.bintrayRepo("kamon-io", "releases")` to your resolvers and you will get access to the very latest versions! Will close this once all is properly synced, thanks for reporting.

**Comment by zettelmj** [comment]
oh ok that solves that.

Cheers
Jens

2017-01-31 11:32 GMT+00:00 Ivan Topolnjak <notifications@github.com>:
