### ISSUE TITLE
option to disable autoweave

### ISSUE THREAD

**Issue by vkrot** [kamon-io/Kamon#433]
Please add an option to disable autoweave. I think it is useful for test - I have a autoweave module in dependencies, but would like to disable it in tests - there weave errors that I don't care about at test time (at runtime it works well)

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
