### ISSUE TITLE
Incorrect dependency in docs

### ISSUE THREAD

**Issue by Discipe** [kamon-io/Kamon#434]
Each kamon project says that dependency keys looks like this:
> libraryDependencies += "kamon.io" %% "kamon-system-metrics" % "0.6.5"

or
> libraryDependencies += "kamon.io" %% "kamon-core" % "0.6.5"

But it's actually "io.kamon", not "kamon.io". Seriously, it's an error in first "Get Started" step.

**Comment by ivantopo** [comment]
![](http://i1.kym-cdn.com/entries/icons/facebook/000/000/554/facepalm.jpg)

We are gonna fix it ASAP, thanks for reporting this!

**Comment by dpsoft** [comment]
@Discipe thanks for reporting this embarrassing issue. I've fixed all repositories.

**Comment by Discipe** [comment]
Wow, that was quick :) Kudos.
