### ISSUE TITLE
performance improvement in CompactHdrSnapshot

### ISSUE THREAD

**Issue by kennethleider** [kamon-io/Kamon#435]
I noticed that the percentile function starts at the smallest values and works it way up.  Since most of the time we care about the larger percentiles, I bet you'll get a boost by starting at the highest value and moving down.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
