### ISSUE TITLE
Kamon is not getting metrics from JDBC

### ISSUE THREAD

**Issue by ricardoatsouza** [kamon-io/Kamon#436]
So maybe I'm just missing something here and this is not an issue.

My `build.sbt` file has the following dependencies (among others):
```
  "io.kamon"                      %% "kamon-core"               % kamonVersion,
  "io.kamon"                      %% "kamon-autoweave"          % kamonVersion,
  "io.kamon"                      %% "kamon-jdbc"               % kamonVersion,
  "io.kamon"                      %% "kamon-log-reporter"               % kamonVersion,
  "io.kamon"                      %% "kamon-jmx"                % kamonVersion
```

My application also does database operations, mostly **write** operations. That's why I'd like to use `kamon-jdbc` for this task.

The problem is: Kamon is not reporting anything regarding JDBC to the logs.

So, my questions are:

1. How does Kamon communicates with the JDBC drivers? 
2. Is it enough to just load `kamon-autoweave` in the build file? (I do see `Kamon-autoweave has been successfully loaded` in the logs)
3. By loading `kamon-autoweave` in the build, does it guarantee that `kamon-jdbc` will be loaded after it? I'm asking this because of this log message: `This offers extra flexibility but obviously any classes loaded before attachment will not be woven.`
3. Is there any problems if I'm using ScalikeJDBC (http://scalikejdbc.org/) to communicate with the database? As far as I know, it should not matter, right?
4. The database I'm connecting to is Sql Server in Azure. Does this matter? (I'm using a JDBC driver to establish the connection)

A bit more of (probably) relevant information:
- I'm working on a Mac OS El Capitain 
- Scala version 2.12.0
- Kamon version 0.6.5
- There are no log error regarding `kamon-autoweave` or `kamon-jdbc`
- All the other measures from Kamon are being properly reported
- During development, the application is running in IntelliJ (probably this does not matter)

I will really appreciate you answer.
Thank you in advance for your help.

**Comment by ivantopo** [comment]
hello there!

I think that the main issue is that you will need to add a `aop.xml` file to your project, including the classes for the JDBC driver that you are using.. I'm currently working on improving that situation (see https://github.com/kamon-io/kamon-jdbc/issues/2) but in the meantime, something like the file bellow in `META-INF/aop.xml` should do the trick.. sorry for the inconvenience, this will be solved pretty soon!

```xml
<!DOCTYPE aspectj PUBLIC "-//AspectJ//DTD//EN" "http://www.eclipse.org/aspectj/dtd/aspectj.dtd">
<aspectj>
  <weaver>
    <!-- replace this with the base package of the driver you are using -->
    <include within="com.zaxxer.hikari..*"/>
  </weaver>
</aspectj>

```

**Comment by ricardoatsouza** [comment]
Hi @ivantopo, thank you for your quick response.

Besides the inconvenience, it's a better chance to learn how Kamon works, so don't worry about it. :)

Regarding your answer, I'm just a bit confused on where exactly this file should be located. In my folder structure there isn't a `META-INF` folder, so I have tried to create it inside the `src/main/resources/` folder, and in the project root folder. Unfortunately, none of them seems to work (or at least, no changes in the logs). And I'm using IntelliJ to develop (not sure if it matters).

One interesting point though... In the logs I see this sequence of Kamon libraries being loaded:
```
INFO  Kamon - Kamon-autoweave has been successfully loaded.
[LogReporterExtension(akka://kamon)] Starting the Kamon(LogReporter) extension
[SystemMetricsExtension(akka://kamon)] Starting the Kamon(SystemMetrics) extension
[JMXExtension(akka://kamon)] Starting the Kamon(JMX) extension
[JMXMetricsExtension(akka://kamon)] Starting the Kamon(JMXMetrics) extension
```

Funny, `Kamon(JDBC)` is not in. Do you think it could be because the `aop.xml` file is missing?

**Comment by ivantopo** [comment]
putting it `src/main.resources` is correct, but I just remembered something: it will only record metrics IF there is a trace context during the JDBC usage, are you measuring traces in your app?

To be honest, I think it would be better wait a bit until these issues are solved, that way you could also give us a hand trying out the new module! :D... it shouldn't take more than a couple days from now... what do you think about that? Also, may I ask, what connection pool are you using? We are starting with support for Hikari but BoneCP, TomcatDBCP and C3P0 will come right after!

**Comment by ricardoatsouza** [comment]
Hi @ivantopo 

I'll check for the trace context and I'll write it back here.

And of course I would like to try it. I still want to solve it in the "old way", but I'm in for testing the new module if possible. :) In my application, I'm using ScalikeJDBC for the connection pool with the database (is that what you meant?), and the database is MSSql in Azure (just in case you need this information :) ).

**Comment by ricardoatsouza** [comment]
Hi @ivantopo 

I tried the `aop.xml` file, but couldn't make it work. It's located in `src/main/resources/META-INF`, as you can see in the image below, and I pasted its content below as well.

![image](https://cloud.githubusercontent.com/assets/7985816/22784613/05d6a1b6-eed1-11e6-9c2b-89b43e9803b6.png)

```
<!DOCTYPE aspectj PUBLIC "-//AspectJ//DTD//EN" "http://www.eclipse.org/aspectj/dtd/aspectj.dtd">
<aspectj>
    <weaver>
        <!-- replace this with the base package of the driver you are using -->
        <include within="com.microsoft.sqlserver.jdbc"/>
    </weaver>
</aspectj>
```

I also enabled the trace logging according to the sql server documentation: https://docs.microsoft.com/en-us/sql/connect/jdbc/tracing-driver-operation

Unfortunately it's difficult to know why it's not working. Any ideas? When is the new module coming out? :)

Cheers

**Comment by whiteancient** [comment]
I am just as eager as Ricardo to start using this module. Just so you know how happy you will make the world when it is released :)
And I am using Hikari :)

**Comment by ivantopo** [comment]
hello there! I just created a PR with the upgrades to the module, please take a look here: https://github.com/kamon-io/kamon-jdbc/pull/3

also published a snashot here: https://bintray.com/kamon-io/snapshots/kamon-jdbc/0.6.6-156d4ab57980130828dbb217d5f562a8e29ed28c, in case any of you wants to give it a try while we add more features :smile:

**Comment by andresfgomez** [comment]
Hello, 
I'm trying to work with this module but it wasn't successful.
If I want to subscribe and capture all the metrics generated by jdbc module, which category should I use? Is fine to use "trace" category?

By the way I'm using Java 8 and Kamon 0.6.0
We want to integrate this tool to our application which use akka and spring jdbc.

Thanks for any help you can give me.

**Comment by dpsoft** [comment]
hey @andresfgomez please make sure you use `0.6.6` version.

**Comment by andresfgomez** [comment]
Hi, 
I changed to 0.6.6 version but still doesn't work.

[KamonExample1.txt](https://github.com/kamon-io/Kamon/files/822678/KamonExample1.txt)

In the example attached, when I try to obtain Kamon.metrics().find(....), it fails because any metrics was found.

Can you give me a hint please?

**Comment by dpsoft** [comment]
@andresfgomez are you starting the application with -javaagent:aspectjweaver.jar?

**Comment by andresfgomez** [comment]
@dpsoft I do not. I'm using autoweave instead of.
Everything does work (akka metrics, my own trace and segments) but jdbc metrics not.

**Comment by dpsoft** [comment]
@andresfgomez please try the following:

create a folder in the root project `META-INF` and put the following in a file called `aop.xml`

```xml
<!DOCTYPE aspectj PUBLIC "-//AspectJ//DTD//EN" "http://www.eclipse.org/aspectj/dtd/aspectj.dtd">

<aspectj>
  <weaver>
    <include within="com.zaxxer.hikari.pool.HikariPool"/>
    <include within="com.zaxxer.hikari.pool.ProxyConnection"/>

    <!-- JDBC Drivers -->
    <include within="oracle.jdbc...*"/>
  </weaver>
</aspectj>
```

**Comment by ivantopo** [comment]
@andresfgomez there is a difference between trace metrics and jdbc-related metrics, I just published version 0.6.8 of the kamon-jdbc module and it already includes proper filters in the `aop.xml` file for oracle databases. Now, with regards to your example, it is generating a trace named "contexto-jdbc", so if you want to measure that you could query the "trace" category and the "contexto-jdbc" entity name, without tags because you didn't add any tags to the actual trace.

With regards to JDBC metrics, you will get some values under the `jdbc-statement` category if you are just using a plain driver without Hikari, you see [here](https://github.com/kamon-io/kamon-jdbc/blob/master/src/main/scala/kamon/jdbc/metric/StatementMetrics.scala#L23) the metrics that will be exposed, I will update the website with this info asap.

**Comment by andresfgomez** [comment]
@dpsoft thank you, I added the aop.xml file to resource package instead of META-INF folder and now I got the jdbc metrics.
@ivantopo  yes, I was confused about the metrics name published in the web site so I digged into the source and found the category name and the metrics name.
Everything is working now !!!

I just found a problem, for example I want to know the name of the slowest queries, but as I use PreparedStatement and execute jdbc method without arguments, I got "not-available" name.
I saw the aspects configured and it seems is not possible to obtain the name.

Thank you for your help.

**Comment by ricardoatsouza** [comment]
Hello @ivantopo. It took me some time to get back to this issue.

It seems that AspectJ is being loaded correctly, but I am receiving an error from AspectJ and I'm not sure if it is related to Kamon (probably not), so maybe you have a better idea of where to look in order to fix the issue:

```
[AppClassLoader@2f4d3709] warning at <Unknown>::0 no match for this type name: com.zaxxer.hikari.pool.HikariPool [Xlint:invalidAbsoluteTypeName]
[AppClassLoader@2f4d3709] warning at <Unknown>::0 no match for this type name: com.zaxxer.hikari.pool.ProxyConnection [Xlint:invalidAbsoluteTypeName]
[AppClassLoader@2f4d3709] warning at kamon/jdbc/instrumentation/HikariInstrumentation.scala::0 no match for this type name: com.zaxxer.hikari.pool.HikariPool [Xlint:invalidAbsoluteTypeName]
[AppClassLoader@2f4d3709] warning at kamon/jdbc/instrumentation/HikariInstrumentation.scala::0 no match for this type name: com.zaxxer.hikari.pool.HikariPool [Xlint:invalidAbsoluteTypeName]
[AppClassLoader@2f4d3709] warning at kamon/jdbc/instrumentation/HikariInstrumentation.scala::0 no match for this type name: com.zaxxer.hikari.pool.HikariPool [Xlint:invalidAbsoluteTypeName]
[AppClassLoader@2f4d3709] warning at kamon/jdbc/instrumentation/HikariInstrumentation.scala::0 no match for this type name: com.zaxxer.hikari.pool.HikariPool [Xlint:invalidAbsoluteTypeName]
[AppClassLoader@2f4d3709] warning at kamon/jdbc/instrumentation/HikariInstrumentation.scala::0 no match for this type name: com.zaxxer.hikari.pool.HikariPool [Xlint:invalidAbsoluteTypeName]
[AppClassLoader@2f4d3709] warning at kamon/jdbc/instrumentation/HikariInstrumentation.scala::0 no match for this type name: com.zaxxer.hikari.pool.HikariPool [Xlint:invalidAbsoluteTypeName]
[AppClassLoader@2f4d3709] warning at kamon/jdbc/instrumentation/HikariInstrumentation.scala::0 no match for this type name: com.zaxxer.hikari.pool.ProxyConnection [Xlint:invalidAbsoluteTypeName]
[AppClassLoader@2f4d3709] warning at kamon/jdbc/instrumentation/HikariInstrumentation.scala::0 no match for this type name: com.zaxxer.hikari.pool.ProxyConnection [Xlint:invalidAbsoluteTypeName]
[AppClassLoader@2f4d3709] warning at kamon/jdbc/instrumentation/HikariInstrumentation.scala::0 no match for this type name: com.zaxxer.hikari.pool.ProxyConnection [Xlint:invalidAbsoluteTypeName]
[AppClassLoader@2f4d3709] error can't determine modifiers of missing type com.zaxxer.hikari.pool.HikariPool
when processing type mungers kamon.metric.SubscriptionsDispatcher$
when processing type mungers 
when weaving 
 [Xlint:cantFindType]
[AppClassLoader@2f4d3709] error can't determine modifiers of missing type com.zaxxer.hikari.HikariConfig
when processing type mungers kamon.metric.SubscriptionsDispatcher$
when processing type mungers 
when weaving 
 [Xlint:cantFindType]
[AppClassLoader@2f4d3709] error can't determine modifiers of missing type com.zaxxer.hikari.pool.ProxyConnection
when processing type mungers kamon.metric.SubscriptionsDispatcher$
when processing type mungers 
when weaving 
 [Xlint:cantFindType]
```

I'm using the `kamon-jdbc` v0.6.7 and `kamon-autoweave` v0.6.5. And I also have this `aop.xml` inside `resources/META-INF`:

```
<!DOCTYPE aspectj PUBLIC "-//AspectJ//DTD//EN" "http://www.eclipse.org/aspectj/dtd/aspectj.dtd">
<aspectj>
    <weaver>
        <!-- replace this with the base package of the driver you are using -->
        <include within="com.microsoft.sqlserver.jdbc"/>
    </weaver>
</aspectj>
```

**Comment by ricardoatsouza** [comment]
I changed a bit my code. Now I'm using Hikari instead of ScalikeJDBC. It seems to be working fine together with AspectJ (`kamon-autoweave`). I see, for example, in my console Error or Warning messages about my sql transactions.

So, it seems that I finally managed to actually get the JDBC metrics from Kamon. 

I am also using Kamon-jmx, and would be nice if I can also see the JDBC metrics being exported to JMX. I thought this would be automatic together with `kamon-jdbc` module, but it isn't (or at least, it's not reporting). So, for my next question: is it possible to export the `kamon-jdbc` to JMX? 

Thanks :)

**Comment by ricardoatsouza** [comment]
Hello again,

I'm not a specialist in how Kamon internally works, so I might be talking a bit of non-sense here and, if this is the case, forgive me. :)

Because we really want to have those jdbc metrics in JMX, I was diving a bit into the libraries to understand how it works. So, I checked a few classes, and I was trying to understand how the JMX registration happens. That was when I decided to put a few breakpoints in the [StatementMetrics](https://github.com/kamon-io/kamon-jdbc/blob/master/src/main/scala/kamon/jdbc/metric/StatementMetrics.scala#L23) class.

I found out that, somehow (due to a bug, misconfiguration or my mistake) the code lines in the StatementMetrics class that create the metrics (histograms, counter, etc... around the lines in between 24 and 30) are not being executed and, therefore, that could be why there isn't any jdbc metrics being reported in the JMX.

In other hand, when checking another Kamon module (in this case `kamon-system-metrics`, classes `MemoryMetrics` and `CpuMetrics`) I could actually see, through breakpoints, that the histogram and counters are being created (and those metrics are being propagated to JMX).

I also noted that there isn't any logs in `stdout` reporting that `kamon-jdbc` has started. From Kamon, I see the following lines in the initialization:
```
kamon.Kamon$Instance - Initializing Kamon...
kamon.Kamon$Instance - Kamon-autoweave has been successfully loaded.
kamon.Kamon$Instance - The AspectJ load time weaving agent is now attached to the JVM (you don't need to use -javaagent).
kamon.Kamon$Instance - This offers extra flexibility but obviously any classes loaded before attachment will not be woven.
[JMXMetricsExtension(akka://kamon)] Starting the Kamon(JMXMetrics) extension
registering jmx exporter
JMX exporting thread] [SystemMetricsExtension(akka://kamon)] Starting the Kamon(SystemMetrics) extension
```

One more think to add: Kamon is, though, reporting SqlError and SlowQueries to stdout, which makes me conclude that AspectJ is working. E.g.:

```
ERROR kamon.jdbc.DefaultSqlErrorProcessor - the query [INSERT INTO DummyTable (
          column1,
          column2,
          column3
       ) VALUES (
          'invalid SQL to produce an error',
          'invalid SQL to produce an error',
          'invalid SQL to produce an error'
       );] failed with exception [String or binary data would be truncated.]

WARN  kamon.jdbc.DefaultSlowQueryProcessor - The query [
      waitfor DELAY '00:00:20'
] took 20105 ms and the slow query threshold is 2000 ms
```

I would like to dig deeper into this, but I certainly cannot do it by myself. I appreciate your help and patience so far with this issue.
Thank you :)

**Comment by andresfgomez** [comment]
Hi @ricardoatsouza,
If you want to issue jdbc metrics to JMX, according to the documentation you need to subscribe to the correct category and entities. Did you?
By default are these values:
kamon.jmx {
  subscriptions {
    histogram       = [ "**" ]
    min-max-counter = [ "**" ]
    gauge           = [ "**" ]
    counter         = [ "**" ]
    trace           = [ "**" ]
    trace-segment   = [ "**" ]
    akka-actor      = [ "**" ]
    akka-dispatcher = [ "**" ]
    akka-router     = [ "**" ]
    system-metric   = [ "**" ]
    http-server     = [ "**" ]
  }
}
I would add this:
   jdbc-statement     = [ "**" ]

**Comment by ricardoatsouza** [comment]
Hello @andresfgomez, thank you for your reply.

Yes, it worked. Thank you! I finally see `jdbc-statement` in the JMX now.  Just one correction though, what I added was:
```
jdbc-statement = [ "**" ]
```

Can you point me to where in the documentation can I find this information? Because, at the moment, it isn't in the [JDBC](http://kamon.io/documentation/kamon-jdbc/0.6.6/overview/) or the [JMX](http://kamon.io/documentation/kamon-jmx/0.6.6/overview/) documentation pages. I really want to know, because I missed that :)

But, even though I see the `jdbc-statement` category in JMX now, the metrics are always zero. I am constantly sending queries that, on purpose, will be slow (20 seconds) or return an error. Kamon does write in the console `WARM kamon.jdbc.DefaultSlowQueryProcessor` or `ERROR kamon.jdbc.DefaultSqlErrorProcessor`. So, am I missing something else?

Thank you,
Cheers

**Comment by andresfgomez** [comment]
Hello @ricardoatsouza 

1. The documentation is not updated,  @ivantopo said he will try to update it asap.

2. I recommend to you read what are the correct entities exposed [here](https://github.com/kamon-io/kamon-jdbc/blob/master/src/main/scala/kamon/jdbc/metric/StatementMetrics.scala#L23)
In this file you will find the category and the metric names.

3. If you don't receive values in your metrics (queries, errors, updates, generic-execute, ..) maybe your using some jdbc function that is not traced.
For example, to fill queries entity you need to use "statement.executeQuery(..)"
If you use "statement.execute(query)" you'll receive values in generic-execute entity.

**Comment by ricardoatsouza** [comment]
Hello @andresfgomez 
Thank you for your answer :)

I will try and I will let you know if it worked. In the meantime, can I add the `jdbc-statement` information to the README in kamon-jdbc repository? It's a really valuable information. :)

Cheers

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
