### ISSUE TITLE
Kamon libraries versioning issue

### ISSUE THREAD

**Issue by cwei-bgl** [kamon-io/Kamon#438]
Hi, it would be nice if somehow Kamon can provide a universal versioning over its libraries or an easy way to assist with the use of its compatible libraries. I have been spending some time to figure out the right combinations.

val kamonDependencies = {
  val kamonVersion = "0.6.5"
  Seq(
    "io.kamon" %% "kamon-core" % "0.6.6",
    "io.kamon" %% "kamon-akka-2.4" % kamonVersion,
    "io.kamon" %% "kamon-akka-remote_akka-2.4" % "0.6.3",
    "io.kamon" %% "kamon-akka-http" % kamonVersion,
    //"io.kamon" %% "kamon-log-reporter"   % kamonVersion,
    "io.kamon" %% "kamon-system-metrics" % kamonVersion,
    "io.kamon" %% "kamon-statsd" % kamonVersion
    //"io.kamon" %% "kamon-jmx" % "0.6.5",
    //"io.kamon" % "sigar-loader" % "1.6.6-rev002",
  )
}

I am getting the following:
`
2 [kamon-akka.actor.default-dispatcher-2] DEBUG Sigar  - no libsigar-universal64-macosx.dylib in java.library.path
org.hyperic.sigar.SigarException: no libsigar-universal64-macosx.dylib in java.library.path
`

`
Exception in thread "main" java.lang.NoClassDefFoundError: kamon/util/executors/ForkJoinPools$ScalaForkJoin$
	at akka.kamon.instrumentation.DispatcherInstrumentation.registerDispatcher(DispatcherInstrumentation.scala:79)
	at akka.kamon.instrumentation.DispatcherInstrumentation.afterActorSystemInitialization(DispatcherInstrumentation.scala:52)
`

Thanks,
Cheng

**Comment by pjfanning** [comment]
There are 0.6.6 jars available for most (or maybe all) of those jars now

**Comment by cwei-bgl** [comment]
thanks. close now.
