### ISSUE TITLE
Kamon reports that AspectJ is loaded and, at the same time, that it's not loaded

### ISSUE THREAD

**Issue by ricardoatsouza** [kamon-io/Kamon#447]
This is an interesting one.

Our project is being compiled with sbt and, later, deployed into a docker-container in AWS. Because it seems more convenient, we decided to go for kamon-autoweave, instead of, during the deploy process, download AspectJ and move it inside docker inside AWS.

During the start-up of the services, kamon-autoweave is being properly loaded:
```
INFO  kamon.Kamon$Instance - Kamon-autoweave has been successfully loaded.
INFO  kamon.Kamon$Instance - The AspectJ load time weaving agent is now attached to the JVM (you don't need to use -javaagent).
INFO  kamon.Kamon$Instance - This offers extra flexibility but obviously any classes loaded before attachment will not be woven.
```

Problem is: in the next few lines, Kamon reports:
```
ERROR kamon.ModuleLoaderExtension - 
  ___                           _      ___   _    _                                 ___  ___ _            _
 / _ \                         | |    |_  | | |  | |                                |  \/  |(_)          (_)
/ /_\ \ ___  _ __    ___   ___ | |_     | | | |  | |  ___   __ _ __   __ ___  _ __  | .  . | _  ___  ___  _  _ __    __ _
|  _  |/ __|| '_ \  / _ \ / __|| __|    | | | |/\| | / _ \ / _` |\ \ / // _ \| '__| | |\/| || |/ __|/ __|| || '_ \  / _` |
| | | |\__ \| |_) ||  __/| (__ | |_ /\__/ / \  /\  /|  __/| (_| | \ V /|  __/| |    | |  | || |\__ \\__ \| || | | || (_| |
\_| |_/|___/| .__/  \___| \___| \__|\____/   \/  \/  \___| \__,_|  \_/  \___||_|    \_|  |_/|_||___/|___/|_||_| |_| \__, |
            | |                                                                                                      __/ |
            |_|                                                                                                     |___/

 It seems like your application was not started with the -javaagent:/path-to-aspectj-weaver.jar option but Kamon detected
```

After that, I tried the approach of loading the AspectJ jar in the docker (by copying the `aspectjweaver.jar` file into docker and using `-javaagent` to run), but also no success (kamon still complains that it's not there).

I'm not sure if this an issue from Kamon, AspectJ, the combination of Kamon + Docker, or the combination Kamon + AspectJ + Docker.

Sorry for being a bit annoying with issues, but I'll appreciate your help once more :)

Cheers,

**Comment by ivantopo** [comment]
hey @ricardoatsouza! How are you packaging your app? it could be that if you are using sbt-assembly without a proper merge strategy then the aop.xml files are not being merged properly and the instrumentation that tells Kamon that the weaver is there is not working.. if that is the case please take a look at this: https://gist.github.com/colestanfield/fac042d3108b0c06e952

**Comment by dpsoft** [comment]
@ricardoatsouza @ivantopo also you can take a look in our examples https://github.com/kamon-io/Kamon/blob/master/kamon-examples/kamon-autoweave-example/build.sbt

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
