### ISSUE TITLE
Trace context storage link is invalid. 

### ISSUE THREAD

**Issue by jaroslawZawila** [kamon-io/Kamon#448]
Link on the http://kamon.io/documentation/kamon-core/0.6.6/tracing/core-concepts/ 
to 
http://kamon.io/documentation/kamon-core/0.6.6/tracing/trace-context-storage/ is invalid.

**Comment by greenbird-chr** [comment]
The relevant information seems to be in the "TraceContext Storage" section here now: http://kamon.io/documentation/kamon-core/0.6.6/tracing/trace-context-manipulation/
