### ISSUE TITLE
all Kamon artifacts should be published for all versions

### ISSUE THREAD

**Issue by swachter** [kamon-io/Kamon#463]
It would be great if all Kamon artifacts would be available for all versions. This would allow to set a single value e.g. "kamon.version=0.6.7" and use that version for all Kamon artifacts.

**Comment by ivantopo** [comment]
for all 0.6.x yes, definitively! We will get them published over the weekend, thanks for pointing this out :D

**Comment by dpsoft** [comment]
done.
