### ISSUE TITLE
Spray Module: EmptyTraceContext present while closing the trace with token

### ISSUE THREAD

**Issue by gmalouf** [kamon-io/Kamon#465]
Kamon-Spray: 0.6.6
Spray: 1.3.3
Akka: 2.3.16

I recently upgraded from Akka 2.3.10 and Kamon 0.5.2 to the versions listed above.  With Kamon active in production, I am seeing the following on every request:

```
k.s.SprayExtension - EmptyTraceContext present while closing the trace with token [ip-172-31-22-247-5022]
```

Where the `5022` is generated/changing on each request.  The metrics no longer are going to StatsD as well, indicating that something is definitely wrong.  Reverting to 0.5.2 fixes this, but want to understand why this is failing?

**Comment by gmalouf** [comment]
Hard to tell, but the description on https://github.com/kamon-io/Kamon/issues/397#issuecomment-257041485 may match up with this.  (We do actor-per-request pattern in Spray).  Not sure why this broke with the upgrade to 0.6.2.

**Comment by gmalouf** [comment]
I was able to identify that we were providing the wrong kamon-statsd version at runtime (0.5.2) which probably is not compatible with kamon-spray 0.6.6.  We will have to test that this resolves the StatsD publishing issue, uncler if it will resolve the EmptyTraceContext one.

**Comment by gmalouf** [comment]
I am able to reproduce this error in staging with the correct versions of kamon-statsd and kamon-spray (0.6.6).  

Besides the `06/06 21:33:09.494 WARN [lt-dispatcher-6] k.s.SprayExtension - EmptyTraceContext present while closing the trace with token [ip-10-0-0-19-36]` happening repeatedly, can also confirm that stats are not making it to StatsD.  I see the following at startup:

```
06/06 21:25:26.578 INFO [main] k.Kamon$Instance - Initializing Kamon...
[INFO] [06/06/2017 21:25:27.691] [main] [StatsDExtension(akka://kamon)] Starting the Kamon(StatsD) extension
```

Falling back to using Kamon **v0.5.2** gets everything working again.  Are there any changes to how to add the kamon-statsd dependency between 0.5.x and 0.6.x?

**Comment by ivantopo** [comment]
Hello there! The error you are seeing there is about instrumentation not being able to propagate the request context all the way from the beginning of the request until the response is back. Since the trace context is not available in the response then it cannot be closed, and, if it cannot be closed then no metrics are recorded for the trace :'(... do you happen to be logging the trace token along the way? I guess if you are doing so you will notice that at some point it stops being logged and that's when the context is lost.

What other Kamon modules are you adding to your application?

**Comment by gmalouf** [comment]
The only 3 being explicitly added are kamon-spray, kamon-core, and
kamon-statsd (runtime only).  What gets me is that this is not happening in
0.5.2 and all of my metrics are recorded.  Wondering if how our code uses
kamon-spray needs to change between the 0.5.x and 0.6.x releases....

**Comment by gmalouf** [comment]
I am able to reproduce this locally using the log-reporter in-place of the
StatsD reporter.  Pretty confident now something changed either in the core
or spray module between 0.5.x and 0.6.x that caused this to start
happening.  Will continue debugging to see if I can find where context is
lost.

**Comment by gmalouf** [comment]
Okay, after testing a few 0.6.x versions I can confirm that the problem
first appears in the 0.6.6 release of kamon-spray.  Further, the failing
unit tests on the master branch demonstrate the exact issue I am seeing...

Going commit-by-commit, I've narrowed where the tests first start failing
both *locally* and in Travis:
https://github.com/kamon-io/kamon-spray/commit/3d31d6e46f1e30403350d1a0e8012448f882d5b8
- I am confident that the cause of this is also causing my issue.

Looking at the commit - the major build change is going from depending on
kamon-core 0.6.3 to 0.6.6 (along with minor Akka, Spray and HDHistogram
version bumps).  Did anything change in how traces are done between these
versions of the core module?



FWIW, An example of a path that generates the warning (and does not output
a metric) in 0.6.6:

get {
  path("status") {
    traceName("Status") {
      complete("A-OK")
    }
  }
}


The above results in

06/07 19:37:57.870 WARN [lt-dispatcher-9] k.s.SprayExtension -
> EmptyTraceContext present while closing the trace with token
> [giraffe.local-3]
>

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
