### ISSUE TITLE
What is the proper way to use counters when they are 0?

### ISSUE THREAD

**Issue by alexbezhan** [kamon-io/Kamon#468]
When I use counter instrument, it sends its value even if it's 0. 

I see two possible ways how to fix that:
- make kamon not send 0 values to backend(datadog in my case)
- make datadog ignore 0 values

How do you guys use counter's with Datadog for proper reporting?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
