### ISSUE TITLE
Create versionless URLs

### ISSUE THREAD

**Issue by otisg** [kamon-io/Kamon#471]
I just noticed the site/URLs have changed. e.g. http://kamon.io/backends/spm/ used to work, but now that is at http://kamon.io/documentation/kamon-sematext-spm/0.6.6/overview/ . The problem with this URL is that it has a version number in it.  Is there a URL to backends like this Sematext SPM backend that does not have a version number in it? That way we could link to it without the fear of breaking or pointing to a stale version in the future.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
