### ISSUE TITLE
removeGauge doesn't call Instrument.cleanup(), leaking a scheduler

### ISSUE THREAD

**Issue by jypma** [kamon-io/Kamon#476]
`InstrumentMetrics.removeGauge` doesn't call `Instrument.cleanup()`, which leaves a scheduler running. Depending on what references the gauge's collector function has, this can be a memory leak.

`removeGauge` should clean up the removed instrument (probably all removal methods should invoke `_.cleanup()`)

**Comment by jypma** [comment]
Current workaround: do a `metrics.find(...).map(_.cleanup)` before removing it.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
