### ISSUE TITLE
Add feature to publish events

### ISSUE THREAD

**Issue by bartkummel** [kamon-io/Kamon#477]
We're using Datadog to visualize metrics of our microservices. Datadog has a nice feature that let us plot **events** as overlay on time-series based views. It can be really helpful to see e.g. a "restart" event in a graph that displays a cache size, since that event could explain why the cache size suddenly drops. This is just one example of events being very helpful to interpret metrics.

While Datadog has this feature to combine metrics and events in one view, Kamon doesn't have a feature to collect the events. So if we'd like to publish those events from our microservices, we would have to use the Datadog API directly for that, which is not what we want. It would be great if Kamon did implement some sort of event stream where we could publish events, in order to be able to forward those to Datadog (or any other backand of course).

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
