### ISSUE TITLE
 Kamon-autoweave failed to load

### ISSUE THREAD

**Issue by aamirfayaz** [kamon-io/Kamon#478]
I am including aspectjweaver-1.8.0.jar file in VM options, but as soon as I run my program this exception comes:

17:39:28.114 INFO  [undefined][] kamon.Kamon$Instance  - Initializing Kamon...
17:39:28.126 DEBUG [undefined][] kamon.Kamon$Instance  - Kamon-autoweave failed to load. Reason: kamon.autoweave.Autoweave.

[ERROR] [07/10/2017 17:39:29.914] [kamon-akka.actor.default-dispatcher-2] [ActorSystem(kamon)] Uncaught error from thread [kamon-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
