### ISSUE TITLE
Kamon Akka vs Lightbend Telemetry

### ISSUE THREAD

**Issue by ryan-ju** [kamon-io/Kamon#482]
Hi, I'm currently using Kamon Akka in a prototype I am building.  It works great, but I want to know if it can support the same set of features as Telemetry http://developer.lightbend.com/docs/monitoring/latest/instrumentations/akka/akka.html.

In particular, whether there is plan to support:
1. Actor metrics (Sent/received message rate, failures, unhandled messages, dead letters)
2. Remote metrics (serialization/deserialization time, message size)
3. Cluster metrics

Thanks

**Comment by jadireddi** [comment]
+1

**Comment by danischroeter** [comment]
kamon already provides these metrics (long before akka telemetry existed)
see here:
https://kamon.io/docs/latest/instrumentation/akka/metrics/

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
