### ISSUE TITLE
Kamon support for SSL

### ISSUE THREAD

**Issue by anarwal27** [kamon-io/Kamon#485]
I had working solution with local deployment of influxdb and setting done via application.conf. However now I have deployed influxdb in secured container which uses https for communication, I get an error for https not supported by kamon:

[ERROR] [10/02/2017 09:31:04.235] [kamon-akka.actor.default-dispatcher-2] [akka://kamon/user/influxdb-metrics-sender] Protocol https is not supported by Kamon InfluxDB Client
akka.actor.ActorInitializationException: akka://kamon/user/influxdb-metrics-sender: exception during creation
followed by

Caused by: java.lang.UnsupportedOperationException: Protocol https is not supported by Kamon InfluxDB Client
Here is my configuration:

kamon {

  metric {
      tick-interval = 10 second
  }

  influxdb {
    hostname = "influxdb.foo.com"
    max-packet-size = 1024
    database = "mydb"
    protocol = "https"

    application-name = "foo-service"
    hostname-override = foo

    percentiles = [50.0, 70.5]
  }

  modules {
    kamon-log-reporter.auto-start = yes
    kamon-influxdb.auto-start = yes
  }

  trace {
      level-of-detail = simple-trace
    }

}

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
