### ISSUE TITLE
[feature request] support application.properties file in spring boot format

### ISSUE THREAD

**Issue by wei-hai** [kamon-io/Kamon#492]
I am trying to use Kamon in my spring boot project, and my application.properties is in the following format:

```
# Kamon
kamon.influxdb.hostname=localhost
kamon.influxdb.port=8200
kamon.influxdb.max-packet-size=1024
kamon.influxdb.application-name=kamon-backend-service
kamon.influxdb.protocol=udp
kamon.influxdb.database=telegraf
kamon.metric.tick-interval="60 seconds"
kamon.metric.default-collection-context-buffer-size=1000
kamon.system-metrics.sigar-enabled=false
```

I set breakpoint in my code and found that Kamon doesn't recognize these variables and use default config instead. Please add support to spring boot property file.

**Comment by ivantopo** [comment]
Hey @wei-hai, just out of curiosity: did you close the issue because you got it to work the way Kamon is now or because it is no longer relevant for you?

**Comment by wei-hai** [comment]
@ivantopo it is no longer relevant
