### ISSUE TITLE
MinMaxCounter apparently cannot be completely removed with the remove method

### ISSUE THREAD

**Issue by risinga** [kamon-io/Kamon#494]
Hi Kamon team,

On recent 0.67 version (with Akka 2.5.1), I've encountered a leak, based on the assumption that the metrics.removeMinMaxCounter method would remove the counter, as well as the entity and scheduler resources. This doesn't seem to be the case. In fact during profiling I found that PadMinMaxCounter instances as well as underlying histograms where hanging, and the scheduler were also increasing, as I called the Kamon.metrics.minMaxCounter(name, tags) to create the counter and the Kamon.metrics.removeMinMaxCounter(name, tags) to remove it, during lifecycle of the objects which referenced these counters.

I would like to get a confirmation if this is considered a bug or not. If in fact it's working as designed, I would suggest to update the documentation, explaining proper usage, including what is the removeMinMaxCounter method purpose if it doesn't actually remove the resources completely.

Thanks

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
