### ISSUE TITLE
trace subscriptions logic error.

### ISSUE THREAD

**Issue by coding4m** [kamon-io/Kamon#495]
kamon.trace.TraceSubscriptions.scala
line 32:
`subscribers = subscribers.filter(_ == leavingSubscriber)`
should be:
`subscribers = subscribers.filterNot(_ == leavingSubscriber)`

line 35 has the same issue.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
