### ISSUE TITLE
Provide Java API for SamplingDecision

### ISSUE THREAD

**Issue by n1ko-w1ll** [kamon-io/Kamon#506]
Hi,
the SamplingDecision case classes like `SamplingDecision.Sample` or `SamplingDecision.DoNotSample` are not accessible from Java. Because of this, Users are not able to write custom `http-headers-keys` codecs in Java.
Best regards
Niko

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
