### ISSUE TITLE
Allow specifying arbitrary tags as part of the environment

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#510]
I propose to add arbitrary tags on the `Environment` via configuration and allow reporting modules to include them. This should be completely optional since not all reporting modules will want or need to expose these additional tags.

Also, this was possible in some modules in Kamon 0.6, we missed it in the upgrade!

**Comment by CasperKoning** [comment]
Would adding some `customTags`, 
```scala
case class Environment(host: String, service: String, instance: String, incarnation: String, customTags: Map[String, String])
```
that would end up in `application.conf` as
```hocon
kamon.environment.custom-tags = {
  key1: value1
  key2: ${ENV_VAR}
}
```
be a good way to go?

That would make it fairly easy to inject environment variables in there as well. 

I can also imagine that you'd want some way to append tags in some programmatic way though.

**Comment by CasperKoning** [comment]
In the datadog module, this was implemented as in this PR: https://github.com/kamon-io/kamon-datadog/pull/1

**Comment by ivantopo** [comment]
Hey @CasperKoning, please take a look at https://github.com/kamon-io/Kamon/pull/515, that is implementing this feature. This just means that Kamon's environment will have the tags, but it will still be a decision of each reporting module to include them or not in the data.
