### ISSUE TITLE
Case sensitive comparison when fetching B3 Headers

### ISSUE THREAD

**Issue by pgorin** [kamon-io/Kamon#517]
When retrieving headers from carrier, a default map storage is used, so accessing headers by key name is not using case insensitive comparison (I think that http headers are case-insensitive).

Thanks!
Patricio.

**Comment by ivantopo** [comment]
Hey @pgorin, may I ask where did you experience this issue? we didn't take this "little" detail into account :s.. although I think this is something we should probably push to each HTTP toolkit integration module!

**Comment by pgorin** [comment]
Hi! First of all, thank you for your rapid response, and then, most important, congrats for all the work done developing kamon!

About the issue, I am using kamon-akka-http instrumentation module. When I make a request sending X-B3 headers (without respecting the casing of the headers) I think that those headers are not fetched from the carrier headers and then not propagated to the rest of the http request flow.

Debugging the code, SpanCode.decode(carrier: TextMap, context: Context) may contain the issue when looking up for the X-B3 headers on the given carrier.

**Comment by ivantopo** [comment]
This is something we should be fixing ASAP. For reference, there is [Headers.scala](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/Headers.scala) from Play.

**Comment by thomschke** [comment]
Same issue exists during context propagation over HTTP, 
config entries under `kamon.context.codecs.string-keys` has to match in a case-intensive way.

**Comment by thomschke** [comment]
Hi @ivantopo, 

this issue has multiple side effects: 
- kamon-akka-http
  - kamon-io/kamon-akka-http#38
  - kamon-io/kamon-akka-http#39
- kamon-play 
  - kamon-io/kamon-play#21

But what about `HttpPropagation` in `kamon-core`, I think it has to handle header-names in a case insensitive way too?

**Comment by thomschke** [comment]
Hi @ivantopo,

the sideeffects (see my last comment) are closed, but what about `HttpPropagation`? In the moment I have to define my own B3 propagation format because your official version includes uppercases:

https://github.com/kamon-io/Kamon/blob/9cb3b054a5f4a2f39c998a008233c1d379ddc6a4/kamon-core/src/main/scala/kamon/trace/SpanPropagation.scala#L99-L105
