### ISSUE TITLE
Kamon is accepting null values for tags

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#518]
We should not let a tag key or value to be null and there are no checks in Kamon regarding this. I think the behavior should be different depending on whether the null is on the tag key or the value:
  - When the key is null I'm thinking we could log an error message and move on. 
  - When the value is null we could either log and move on, or translate that into a `null` string and put it as value for the tag. Maybe even log a warning as well.

Important thing is that no matter what, this should produce some info that users can notice and work on, without breaking operations.

**Comment by lustefaniak** [comment]
When using `span.addError(throwable.getMessage)` I'm sometimes passing `null`, which later on causes exception in Kamino reporter. Probably that should be handled in `Span.Local.addError`:

```
    override def addError(error: String): Span = synchronized {
      if(open) {
        hasError = true

        if(sampled) {
          spanTags = spanTags ++ Map(
            "error" -> TagValue.True,
            "error.object" -> TagValue.String(error)
          )
        }
      }
      this
    }
```

WDYT?

**Comment by lustefaniak** [comment]
`addError` with Throwable is also vulnerable.

**Comment by lustefaniak** [comment]
Looking at that code I'm not sure what is the purpose of passing `error` at all as it is not used anywhere:
```
override def addError(error: String, throwable: Throwable): Span = synchronized {
      if(open) {
        hasError = true

        if(sampled) {
          spanTags = spanTags ++ Map(
            "error" -> TagValue.True,
            "error.object" -> TagValue.String(throwable.getMessage())
          )
        }
      }
      this
    }
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
