### ISSUE TITLE
consider creating a noop codec

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#522]
@jsw just shared a [noop](https://github.com/jsw/play-2.6-with-kamon/pull/2/commits/b3e875c5042798bcb7aae27d94eedd5935ccbb88#diff-8580ae5122ea13d17acb7db63869d10d) codec for cases in which context propagation for a specific key should be explicitly disabled (for whatever reason it is) and it seems like this is something good to have in Kamon.

**Comment by jsw** [comment]
You may already be thinking along these lines, but one suggestion is to have the user set the value to `null`, and then kamon could simply skip over that map entry when processing config.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
