### ISSUE TITLE
Narrow down the identity providers choice

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#523]
There are a couple PRs (see https://github.com/kamon-io/kamon-jaeger/pull/6 and https://github.com/kamon-io/Kamon/pull/520) related to how identity providers could be used and while looking into those there is a greater issue that came to surface: currently there is no way for a SpanReporter to know whether it can convert any arbitrary identifier into what a specific tracing platform might need. 

The whole idea of having the IdentityProviders as a separate component was to be able to play nice with other tracing platforms where a Kamon-instrumented service might be involved, although diversity on terms of trace and span identifiers is not as bad as we thought.. Here is the list of platforms that we support or plan to support in the near future:
  - Zipkin
  - Jaeger
  - Kamino
  - Stackdriver
  - Amazon X-Ray
  - Datadog

This narrows down the trace ID formats to just 3 options:
  - 16 bytes, supported by Zipkin, Jaeger, Kamino and Stackdriver.
  - 8 bytes, supported by Zipkin, Jaeger, Kamino and Datadog.
  - 4 + 12 bytes Amazon format.

In all cases the span IDs are 8 bytes so no conflict at all.

One more thing to take into account is the [Trace Context spec](https://w3c.github.io/distributed-tracing/report-trace-context.html) which follows the 16 bytes approach for trace IDs and that will hopefully make it even more common in the years to come. 

Unless I am grossly missing something here, I think it would be a good move to implement these 3 identity providers in core and have a easy way for reporters to know which provider is in place and whether they can accept it or not, failing during initialization if needed.

#### Adopting a third party identifier as trace ID

One thing that came up on the PRs was adopting a external identifier as a trace ID, specifically in the case of Heroku's `X-Request-Id` raised by @jtjeferreira or Cloudflare's `cf-ray` header which we use in our apps. The CF case is easy because the format can be stripped down to a 8 byte identifier, but Heroku's identifier is a UUID which makes it "special" to say the least.. I'm not sure that we should be doing this at all, though.. these external correlation IDs cannot be used as-is as trace identifiers, but it is actually valuable to have them moving around with the context and add them to the logs for correlation.

I would say that we should not adopt third party identifiers as trace IDs but rather encourage users to define them as broadcast context strings so that they will be automatically added to the context and available for logging if needed, but I would like to hear opinions on this.

**Comment by adriancole** [comment]
Agree with the general sentiments here. I am not sure if there are big
reasons to strictly tie identifier providing strictly to a product. Most
use same way except amazon and even amazon approach is fine for some. So
maybe just note mechanisms as opposed to branding.. ex epochPrefixedTraceId
could be amazon

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
