### ISSUE TITLE
Improve the configuration experience on reporters

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#524]
Currently (1.1.x) we can use this to "configure" reporters:

```
// On application.conf:
kamon.reporters = ["my.reporter.Class"]

// During startup:
Kamon.loadReportersFromConfig()
```

It works but fails to provide a few features we had in Kamon 0.6.x, most notably, we were able to start a reporter just by having it on the classpath and enable/disable reporters by having a single setting set to yes/no, now we would need to add/remove from a collection. The second is not a big deal, though.

There is one more thing that might be worth having in core as well: when configuring a reporter, being able to provide metric filters and the flush internal for them. Currently filters can only be set when adding the reporter by code and in 0.6.x a few modules were using a snapshot buffer in case the tick-interval was smaller than what the reporter wanted but. Realistically, how many cases do we have in which users have more than 1 metrics reporter and would need different flush intervals for them? That would be nice to know... regardless of that, though, being able to personalize reporters via configuration on the same way we can do by code would be a very nice addition.

Would love to hear feedback on the above!

**Comment by Falmarri** [comment]
> The second is not a big deal, though

This can actually be a decently big deal. If you're trying to override config, you can't easily remove from an array. How I solved this is to use arbitrary key/values. So something like

```
kamon.reporters {
 "myreporter" = "my.reporter.Class"
}
```

Then you can just set `kamon.reporters.myreporter = null` in your override file. The key that the you use is arbitrary and isn't actually used for anything other than config targeting.

What is your goal here? Keeping it a flat array? It sounds like it makes more sense to have some kind of nested object though.

```
kamon.reporters {
 "myreporter" {
    class = "my.reporter.Class"
    config = {}
  }
}
```

**Comment by ivantopo** [comment]
Hey @Falmarri, I agree with you. I missed the fact that there is no `-=` in Typesafe Config. The goal would definitely be having something like what you put above:

```
kamon.reporters {
 "myreporter" {
    class = "my.reporter.Class"
    config = {}
  }
}
```

If we get to a point where everything we could do from code in terms of adding reporters could be easily done by config then we will be all set :smiley:...Then all reporters could ship their default `kamon.reporters.xxx` section and have a `enabled=yes|no` setting. If for any reason someone wants to add a second instance of a reporter with a different config it should be simple to do so by config as well, although I would say that's a very less common use case.

**Comment by jalaziz** [comment]
I believe Kamon 2.0 solves the loading issue. However, being able to filter metrics at the config level is still missing.

Now that filter configurations is moved into the modules, it could be up to the reporters to support filtering. However, it seems like a general enough problem that should be supported in Kamon core.

**Comment by xoyo24** [comment]
> how many cases do we have in which users have more than 1 metrics reporter and would need different flush intervals for them

We are using Datadog and NewRelic at the same time for different purposes now.
For java services, we use Micrometer which can specify a value for step separately. I so we can change if for a single reporter when it's necessary(ex. for reduce API calls)
But for scala projects we use Kamon so can't do that now.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
