### ISSUE TITLE
kamon-testkit 1.1.2 is not published in Maven

### ISSUE THREAD

**Issue by jasonmartens** [kamon-io/Kamon#534]
For some reason, kaman-core 1.1.2 is there, but the latest kamon-testkit is 1.1.1. 
http://search.maven.org/#search%7Cga%7C1%7Ckamon-testkit

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
