### ISSUE TITLE
Potential memory leak with Kamon 1.0.1

### ISSUE THREAD

**Issue by cwei-bgl** [kamon-io/Kamon#541]
Hi,

I am using Kamon 1.0.1. The symptoms are similar to the issue #213 .  Could you please help me? thanks.

![image](https://user-images.githubusercontent.com/12963397/41689927-88ffcb20-7536-11e8-800f-9b1944448301.png)

![image](https://user-images.githubusercontent.com/12963397/41689915-6dc103ba-7536-11e8-9ccb-bb4fb1fa6474.png)

![image](https://user-images.githubusercontent.com/12963397/41689864-23695484-7536-11e8-856f-9b4719eaa55c.png)

![image](https://user-images.githubusercontent.com/12963397/41689878-38b576ce-7536-11e8-9842-dd581bcba947.png)

**Comment by dpsoft** [comment]
hey @cwei-bgl I think that you are sufering the same as :https://github.com/kamon-io/kamon-prometheus/issues/21

**Comment by cwei-bgl** [comment]
thanks @dpsoft , I am not using prometheus. You can see from my dependencies. I am using influxdb. But I did using sharding for persistent actors.

**Comment by cwei-bgl** [comment]
@dpsoft Thanks for the valuable tool. Will someone be looking into this issue?  Thanks.

**Comment by ivantopo** [comment]
Hello @cwei-bgl, could you please share what your akka filters section look like? this seems like you probably are tracking every single actor and creating many many of them.

**Comment by Yannic92** [comment]
Does this mean that it is not possible to create a timer with name 'http_roundtrip_time' for every request and add status code and path as tags?
I seem to suffer from the same problem and in my case the problem is timers (which are based on histograms).

**Comment by cwei-bgl** [comment]
@ivantopo , Sure thing. The following is the configuration. It might be the case as you pointed out. But even so, I think Kamon should not be using so much memory, as it is a small app? However I am waiting for your suggestions. Thanks.

kamon {
  system-metrics {
    #sigar is enabled by default
    sigar-enabled = true

    #jmx related metrics are enabled by default
    jmx-enabled = true
  }

  util.filters {
    "akka.tracked-actor" {
      includes = [ "*/user/**" ]
      excludes = [ "*/system/**", "*/user/IO-**" ]
    }

    "akka.tracked-dispatcher" {
      includes = ["**"]
    }
  }

  influxdb {

    # Hostname and port in which your InfluxDB is running
    hostname = "a_host_name"
    port = 8086

    # The database where to write in InfluxDB.
    database = "a_database_name"

    # For histograms, which percentiles to count
    percentiles = [50.0, 70.0, 90.0, 95.0, 99.0, 99.9]

    # Allow including environment information as tags on all reported metrics.
    additional-tags {

      # Define whether specific environment settings will be included as tags in all exposed metrics. When enabled,
      # the service, host and instance tags will be added using the values from Kamon.environment().
      service = yes
      host = yes
      instance = yes

      # Specifies which Kamon environment tags should be ignored. All unmatched tags will be always added to al metrics.
      blacklisted-tags = []
    }
  }
}

**Comment by cwei-bgl** [comment]
@ivantopo @dpsoft Any suggestions or progress on this one? Thanks.

**Comment by ivantopo** [comment]
Hey @cwei-bgl, having `includes = [ "*/user/**" ]` in the `"akka.tracked-actors"` filter is almost never a good idea. There is a fixed amount of memory to be used for every tracked actor and if you Kamon is consuming that much memory it most certainly means that you have thousands and thousands of active actors that are being tracked. 

We usually ask people to add `**` just to see what actors need to be tracked and then narrow down the filters before going to production. I would recommend you to take a look at the max over time for the `akka.system.active-actors` metric which I'm almost sure must be in the order of many thousands for this to happen.

Most of the time when people think they want to track many many actors, what they really need to do is to have an [actor group](http://kamon.io/documentation/1.x/instrumentation/akka/actor-system-metrics/#actor-group-metrics) defined, have you looked at it?

**Comment by cwei-bgl** [comment]
Thanks for the pointer - actor group. I will have a look.

**Comment by stianlagstad** [comment]
Thanks for the super-quick response!

Here's the app's configuration:
```
akka {
  default-dispatcher {
    # Dispatcher is the name of the event-based dispatcher
    type = Dispatcher
    # What kind of ExecutionService to use
    executor = "fork-join-executor"
    # Configuration for the fork join pool
    fork-join-executor {
      # Min number of threads to cap factor-based parallelism number to
      parallelism-min = 8
      # Parallelism (threads) ... ceil(available processors * factor)
      parallelism-factor = 3.0
      # Max number of threads to cap factor-based parallelism number to
      parallelism-max = 64
      # Setting to "FIFO" to use queue like peeking mode which "poll" or "LIFO" to use stack like
      # peeking mode which "pop".
      task-peeking-mode = "LIFO" # because that means currently running tasks will be prioritized
    }
    # Throughput defines the maximum number of messages to be
    # processed per actor before the thread jumps to the next actor.
    # Set to 1 for as fair as possible.
    throughput = 1
  }
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
  log-config-on-start = off
  logger-startup-timeout = 60s
}
```

I misspoke earlier. I did not mean routers. I looked at the value from the prometheus query `avg(akka_actor_mailbox_size_sum{app="our-app", path=~"our-app/user/trala/trala-router/trala-actor.*"})`. This value quickly got up to several million. Same with `akka_actor_mailbox_size_count`. Is there another way I could get a better understanding of how many messages are in the inbox of actors?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
