### ISSUE TITLE
Thoughts about allowing Histograms to be manually resetted/cleared

### ISSUE THREAD

**Issue by Yannic92** [kamon-io/Kamon#542]
I'm currently trying to expose Metrics stored in a DropWizard MetricRegistry via Kamon to Prometheus.

For this purpose I implemented a `com.codahale.metrics.ScheduledReporter` that is responsible to store the values of metrics in Kamons metric instruments.
I have to use this DropWizward MetricRegistry in the first place, since akka-persistence-mongo uses this to report their metrics.

For codahales metric instruments: Counter and Gauge this is relatively easy since I can just set the values from them to kamons metric instruments: Counter and Gauge.

For Timers, Histograms and Meters this isn't possible since I can't set their recorded values to a Kamon Histogram.

Would it be an option to allow a Histogram to be resetted/cleared?
I would love to provide a pull request to allow this.

_additional information_
To make more clear how a reset of a histogram would help me I want to provide a small code snippet that shows how I want to put the values from codahales Histogram into Kamons Histogram: 

    private void report(final String name, final com.codahale.metrics.Histogram histogram) {
        final HistogramMetric metric = Kamon.histogram(name);
        final kamon.metric.Histogram h = refine(metric);
        // h.clear()/reset() // this doesn't exist, yet
        final long[] snapshotValues = histogram.getSnapshot().getValues();
        for (final long snapshotValue : snapshotValues) {
            h.record(snapshotValue);
        }
    }

As you can see I am able to get all values from codahales Histogram and add them to Kamons Histogram, but they will be ADDED each time codahales Histogram is beeing reported.
If I could delete the already reported values from Kamons histogram this would not be an issue.

Thank you for your work!

**Comment by ivantopo** [comment]
Aha, I think I got it now. The only thing that comes to mind at the moment would be to use the `HdrHistogramResetOnSnapshotReservoir` from [Marshall Pierce](https://bitbucket.org/marshallpierce/hdrhistogram-metrics-reservoir). I think in that case the behavior from Dropwizard internals would be similar to what Kamon does and also, high definition data!

The only issue I see is that it wouldn't work nice if other reporters are configured in DW.

**Comment by Yannic92** [comment]
Thank you, wasn't aware of this reservoir. There is no other reporter configured for this, but I'm not sure if I have a chance to change the reservoir of the Histogram.
I will check this.

**Comment by Yannic92** [comment]
Unfortunately I can't use this reservoir :(
To get you right: You don't think allowing a reset of a Kamon Histogram is a good idea?

**Comment by ivantopo** [comment]
Correct. Kamon has its own schedule on which it will reset histograms freely allowing users to reset a histogram at any point in time could be problematic, that's one of the reasons why we have separate write (instrumentation) and read (reporters) apis. 

Now, that being said, our histogram has the [ability to be reset](https://github.com/kamon-io/Kamon/blob/master/kamon-core/src/main/scala/kamon/metric/Histogram.scala#L67) which is not exposed, but it is there. We use this on the [testkit](https://github.com/kamon-io/Kamon/blob/master/kamon-testkit/src/main/scala/kamon/testkit/MetricInspection.scala#L56-L63) to get snapshots and internally to produce the snapshots on every tick. That API is not meant to be used outside of Kamon, but if you really want to get it working you can basically do the same that we do in the testkit to reset the histograms.

**Comment by Yannic92** [comment]
Ok, I will think about it. Thank you for your help.
I will close this issue as everything is said I guess :)
