### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by oridag** [kamon-io/Kamon#544]
When closing reporters, any events that are queued and not yet sent to the reporter are lost. The buffer should be drained before calling close() on a reporter.

**Comment by ivantopo** [comment]
hey @oridag, can you please take a look at https://github.com/kamon-io/Kamon/issues/533? I think it's the same as you describe here. I would rather close this one and track progress on that other. Thanks!

**Comment by oridag** [comment]
@ivantopo Yep, that's an exact duplicate. I'll close this one. Thanks!
