### ISSUE TITLE
Inconsistent dependency versions for kamon submodules

### ISSUE THREAD

**Issue by ashleymercer** [kamon-io/Kamon#545]
**Kamon version**
1.1.x

Hi there,

A very minor thing: I noticed that the dependencies for the latest versions of kamon are inconsistent. For example, the latest version of `kamon-scala-future` available in Maven central is `1.0.0`, and this depends directly on `kamon-core` version `1.0.0`:

http://search.maven.org/#artifactdetails%7Cio.kamon%7Ckamon-scala-future_2.12%7C1.0.0%7Cjar

However, the latest version of `kamon-core` itself is 1.1.3:

http://search.maven.org/#artifactdetails%7Cio.kamon%7Ckamon-core_2.12%7C1.1.3%7Cjar

Therefore if I try to use the latest version of `kamon-core`, then `sbt` whinges at me about mismatched dependency versions, e.g.

```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* io.kamon:kamon-core_2.12:1.1.3 is selected over {1.1.0, 1.0.0}
[warn] 	    +- com.foo:bar_2.12:0.1.0                             (depends on 1.1.3)
[warn] 	    +- io.kamon:kamon-scala-future_2.12:1.0.0             (depends on 1.0.0)
[warn] 	    +- io.kamon:kamon-prometheus_2.12:1.1.1               (depends on 1.1.0)
[warn] 	    +- io.kamon:kamon-play-2.6_2.12:1.1.0                 (depends on 1.1.0)
```

I can think of a couple of solutions to this, although there may be others:

- always release `kamon-core` and all submodules with versions locked together. This is a bit of an admin overhead, but is the easiest for the end user

- allow version ranges for the dependencies, or else mark them as `provided` scope, so the end user can decide which versions to use together (although this risks pulling in incompatible versions)

**Comment by ivantopo** [comment]
Hey @ashleymercer, thanks for bringing this up! 

There was a time when we were doing things as in your first proposal and it was just painful for us. As Kamon grows there are many small fixes that need to be applied and when fixing one tiny think in kamon-akka required us to release 20 modules more, it was clear that we had to break and have independent releases.

Now, these versions ranges thingy seems interesting. I did a quick google search around it because I'm not familiar with it at all, but it seems like something worth investigating further. Do you have any experience or recommended material around it? :thinking:

**Comment by ashleymercer** [comment]
Sure, the sbt docs are here:
https://www.scala-sbt.org/1.x/docs/Library-Management.html#Dependencies

Under the hood, sbt uses Ivy and the full syntax for version ranges is here:
https://ant.apache.org/ivy/history/2.3.0/ivyfile/dependency.html#revision

So I guess it depends what your policy on compatibility-breaking changes is, but in general you could probably declare something like `[1.0.0,2.0.0)` which is "everything from `1.0.0` upwards (inclusive) but strictly less than `2.0.0`". Of course, if you make backwards-_in_compatible changes then this won't be true :)

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
