### ISSUE TITLE
Metric.refine method should return a Metric itself, to allow for easy chaining/wrapping

### ISSUE THREAD

**Issue by danielkza** [kamon-io/Kamon#546]
I'm trying to write a simple trait to give all metrics created inside my actor some pre-defined tags. Unfortunately, `Metric.refine` returns the underlying type of the `Metric`, which cannot be further composed, and is different from the types returned by the methods in the `Kamon` object.

To illustrate, inside my `Actor` I would like to be able to call `metrics.histogram(...)` and get a `MetricHistogram` (exactly like `Kamon.histogram` would give me), but with customizations.

To illustrate better, here is what I was hoping to be able to do:

```scala
import java.time.Duration

import akka.actor.Actor
import kamon.Kamon
import kamon.metric._


trait ActorMetrics { actor: Actor =>
  private val defaultMetricTags = Map(
    "myTag" -> "myValue"
  )

  protected def metricTags: Map[String, String] = defaultMetricTags

  protected val metrics = new MetricLookup {
    // All the following definitions fail to compile with typing errors:
    // type mismatch;
    // [error]  found   : kamon.metric.RangeSampler
    // [error]  required: kamon.metric.RangeSamplerMetric
    // [error]       Kamon.rangeSampler(name, unit, sampleInterval, dynamicRange).refine(actor.metricTags)

    override def histogram(name: String, unit: MeasurementUnit, dynamicRange: Option[DynamicRange]): HistogramMetric =
      Kamon.histogram(name, unit, dynamicRange).refine(actor.metricTags) 

    override def timer(name: String, dynamicRange: Option[DynamicRange]): TimerMetric =
      Kamon.timer(name, dynamicRange).refine(actor.metricTags)

    override def counter(name: String, unit: MeasurementUnit): CounterMetric =
      Kamon.counter(name, unit).refine(actor.metricTags)

    override def gauge(name: String, unit: MeasurementUnit): GaugeMetric =
      Kamon.gauge(name, unit).refine(actor.metricTags)

    override def rangeSampler(name: String, unit: MeasurementUnit, sampleInterval: Option[Duration],
                              dynamicRange: Option[DynamicRange]): RangeSamplerMetric =
      Kamon.rangeSampler(name, unit, sampleInterval, dynamicRange).refine(actor.metricTags)
  }

}
```

**Comment by ivantopo** [comment]
Hey @danielkza! This is something we have been thinking of lately. It has happened to us already that we wanted to have a bit more flexibility regarding tagging metrics. (Plus, changing the name `refine` with `tag` which seems a lot more familiar to the public in general).

I'll evaluate whether we can do this and keep backwards compatibility, if so we will add this soon. Otherwise it will have to wait until Kamon 2.0 (which is not too far btw :smile:)

**Comment by danielkza** [comment]
@ivantopo Thank you, good to know my needs make sense. If there is still time for suggestion, an API using a builder pattern, or immutable metrics that return new instances of the same types on "refinement" would be much more flexible, and more familiar to Java/Scala users (respectively).

For example:

```scala
// Builder-style
val metricBuilder: HistogramMetricBuilder = Kamon.histogramBuilder.withName("my-metric").withTags(Map("default" -> "value"))
val metric: HistogramMetric = metricBuilder.withTags(Map("custom" -> "value")).build()

// Immutable object style
val baseMetric: HistogramMetric = Kamon.histogram("my-metric").withTags(Map("default" -> "value"))
val metric: HistogramMetric = baseMetric.withTags(Map("custom" -> "value"))
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
