### ISSUE TITLE
SubsctiptionsDispatcher TickMetricSnapshot exist?

### ISSUE THREAD

**Issue by evbo** [kamon-io/Kamon#547]
Trying to follow docs, but not seeing this class "SubscriptionsDispatcher.TickMetricSnapshot"?
http://kamon.io/documentation/kamon-core/0.6.6/metrics/subscription-protocol/

Are 0.6.6 docs not accurate with the latest code? What class should I use to subscribe to periodic metrics?

Thanks!

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
