### ISSUE TITLE
Copy certain context keys into the HTTP responses

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#558]
There is a common request for adding the trace and span ids on the HTTP responses from an instrumented service (see https://github.com/kamon-io/kamon-play/issues/16 for example). This is a common enough request that we should add it, but we need to figure out what's the cleanest way to do it.

Since #552 we will have an abstraction for instrumenting HTTP servers so, my proposal would be to add some special configuration there so that we can say "write the key `span` into the response, using the XXXX entry writer". This needs some more thought, looking forward for comments.

**Comment by adriancole** [comment]
works for http. I think Amazon write back the sampled status on a root span
in some of their instrumentation. I wouldn't recommend putting input
headers like B3 in the response as that has caused confusion in the past.
Also it will lead to propagation lock in as only reason someone would put a
response header is a user to access it. there is a long issue in the B3
repo about this. anyway was thinking about requiring the user to provide
their own name when they want.

interesting that you commonly get requests about span ID. I haven't noticed
this as much as trace ID.

**Comment by ivantopo** [comment]
Thanks for the feedback, @adriancole. We finally got to implement this, it was a rather quick thing to do!

**Comment by jtjeferreira** [comment]
this means https://github.com/kamon-io/kamon-play/issues/29 is fixed?
