### ISSUE TITLE
Why did CurrentValueCollector get removed in new version? 

### ISSUE THREAD

**Issue by eugenemiretsky** [kamon-io/Kamon#568]
The old version (0.6.X) had CurrentValueCollector for scheduling Gauge value  collection periodically. It has been removed in 1.X.X. What was the reasoning for that? Is the expect usage for users to schedule their own function to periodically report the new value?

**Comment by danischroeter** [comment]
use `.autoUpdate`
close issue...

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
