### ISSUE TITLE
my counter prints in datadag a stream path

### ISSUE THREAD

**Issue by NirOhayon** [kamon-io/Kamon#571]
if you could please look at the issue described here https://stackoverflow.com/questions/54894447/datadog-present-weird-kamon-counter-string

looks like its a Kamon bug.

Thanks!

**Comment by NirOhayon** [comment]
now it happens to me on another counted by with different path string...."application/system/io-tcp/selectors/_a/47635"

never seen this before....

**Comment by dpsoft** [comment]
hey @NirOhayon can you share with us the dependencies that are you using?

**Comment by NirOhayon** [comment]
sure, those are my dependencies:

  val kamon = Seq(
    "io.kamon" %% "kamon-core" % "0.6.7",
    "io.kamon" %% "kamon-system-metrics" % "0.6.7",
    "io.kamon" %% "kamon-scala" % "0.6.7",
    "io.kamon" %% "kamon-play-2.6" % "0.6.8",
    "io.kamon" %% "kamon-akka-2.5" % "0.6.8",
    "io.kamon" %% "kamon-datadog" % "0.6.8" exclude("org.asynchttpclient", "async-http-client")
  )

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
