### ISSUE TITLE
mailbox metrics missing

### ISSUE THREAD

**Issue by Michael-List** [kamon-io/Kamon#602]
Hey,

since the Google group is kinda dead I'm trying my luck here. I have an example akka application (https://github.com/Michael-List/akka-microservice-sample/tree/kamon) in which I integrated Kamon 2 and the prometheus reporter. On the Kamon status page on port 5266 I can see that the modules host metrics, jvm metrics, process metrics and status page are successfully started. In the metrics section there is a metric akka.actor.mailbox-size but I can't find this metric on the prometheus server, only other kamon metrics. Could you please tell me what I'm doing wrong? If you need further information please feel free to ask.

![kamon_status_1](https://user-images.githubusercontent.com/9529849/62885866-38310400-bd3a-11e9-8826-908ecf68ab50.png)
![kamon_status_2](https://user-images.githubusercontent.com/9529849/62885867-38c99a80-bd3a-11e9-8d35-125f8327f792.png)

Greetings
Michael

**Comment by ivantopo** [comment]
Hey @Michael-List, I think the key is on the "0 instances" on the metric. The difference you see has to do with the fact that the Status Page and the Reporters have different sources of information:
- The Status Page uses Kamon's status API, which can know that a metric has been defined even before any instruments for that metric has been created.
- The reporters only get data from instruments and judging by the screenshot, even though some actors are created I would say that non of them is explicitly being tracked. Take a look at [this setting](https://github.com/kamon-io/kamon-akka/blob/master/kamon-akka/src/main/resources/reference.conf#L71-L77) for more info.

This should be it! If not please comment or stop by our [Gitter channel](https://gitter.im/kamon-io/Kamon). Thanks for sharing!
