### ISSUE TITLE
Adding kamon-bundle 2.0.0 causes NoClassDefFoundError

### ISSUE THREAD

**Issue by lukoyanov** [kamon-io/Kamon#603]
Hey!

I've tried to add kamon monitoring to my tiny scala http4s application, but got following error on my first request:

```
[scala-execution-context-global-11] INFO  o.h.s.b.BlazeServerBuilder - http4s v0.20.0 on blaze v0.14.0 started at http://[0:0:0:0:0:0:0:0]:9000/ 
[blaze-selector-1] ERROR o.h.b.c.n.SelectorLoop - Unhandled exception in selector loop 
java.lang.NoClassDefFoundError: Could not initialize class scala.concurrent.Future$
	at org.http4s.server.blaze.BlazeServerBuilder.pipelineFactory(BlazeServerBuilder.scala:281)
	at org.http4s.server.blaze.BlazeServerBuilder.$anonfun$resource$6(BlazeServerBuilder.scala:331)
	at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.fromKey$1(NIO1SocketServerGroup.scala:274)
	at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.$anonfun$handleClientChannel$2(NIO1SocketServerGroup.scala:289)
	at org.http4s.blaze.channel.nio1.SelectorLoop$$anon$2.run(SelectorLoop.scala:147)
	at org.http4s.blaze.util.TaskQueue.go$1(TaskQueue.scala:82)
	at org.http4s.blaze.util.TaskQueue.executeTasks(TaskQueue.scala:99)
	at org.http4s.blaze.channel.nio1.SelectorLoop.org$http4s$blaze$channel$nio1$SelectorLoop$$runLoop(SelectorLoop.scala:166)
	at org.http4s.blaze.channel.nio1.SelectorLoop$$anon$1.run(SelectorLoop.scala:67)
	at java.lang.Thread.run(Thread.java:748)
[blaze-selector-1] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-1 
```
More info:

1. The only library I added was "io.kamon" %% "kamon-bundle" % "2.0.0".
2. I double checked my dependencies for some old 2.11 jar or dublicates, but everything is ok and works without kamon dependency.

**Comment by ivantopo** [comment]
Hey @lukoyanov, have you tried the latest bundle? version 2.0.1 was released just last night and it includes a fix on the kamon-scala-future module that could be fixing this issue!

**Comment by lukoyanov** [comment]
Just tried kamon-bundle 2.0.1 the error is still there :(

My kamon deps look like this:
![Снимок экрана 2019-08-15 в 13 22 36](https://user-images.githubusercontent.com/842901/63089232-cd611200-bf5f-11e9-85c0-5a9828cd2fca.png)

**Comment by ivantopo** [comment]
Could you please help out with a minimum example to reproduce the issue?

**Comment by lukoyanov** [comment]
Ok, i'll try to create a pet project reproducing a bug. 

Meanwhile, dont know if this is important or not - on the status page scala future instrumentation is disabled:
![Снимок экрана 2019-08-15 в 13 42 45](https://user-images.githubusercontent.com/842901/63090240-5b8ac780-bf63-11e9-847a-4d0bce1490aa.png)

**Comment by lukoyanov** [comment]
@ivantopo, I've created a private repository and added you as a collaborator. Please do the following:

```
$ sbt run
.. after start in another terminal
$ http -v localhost:8080/ideas summary=xx text=x
```

**Comment by ivantopo** [comment]
I tried using it to reproduce the issue but it didn't break :confused:, please check your Gitter!

**Comment by ivantopo** [comment]
For the record, the issue was that `Kamon.init()` was being called a bit late during initialization. Here is an extract from the example for reference:

```scala
object Main extends IOApp {

  def stream[F[_]: ConcurrentEffect](implicit T: Timer[F]): Stream[F, ExitCode] = {

    val commonErrorHandler = CommonErrorHandler[F]
    val ideaModule         = IdeaModule[F]()

    val httpApp =
      commonErrorHandler
        .handle(
          IdeaApi.ideaRoutes(ideaModule.service) <+>
            UsersApi.usersRoutes()
        )
        .orNotFound
    //.handleErrorWith(globalError => Conflict(s"global error $globalError"))

    val finalHttpApp = Logger.httpApp(logHeaders = true, logBody = true)(httpApp)
    // Kamon.init() <---- This is too late!

    BlazeServerBuilder[F]
      .bindHttp(8080, "0.0.0.0")
      .withHttpApp(finalHttpApp)
      .serve
  }

  def run(args: List[String]): IO[ExitCode] = {
    Kamon.init() // Leaving it here was early enough for this example to work!
    stream[IO].compile.drain.as(ExitCode.Success)
  }

}
```
