### ISSUE TITLE
kamon-testkit 2.0.0 is not published 

### ISSUE THREAD

**Issue by DieBauer** [kamon-io/Kamon#609]
The last testkit release is 2.0.0-M4. And is not cross build for Scala 2.13.

Can the testkit be released for 2.0.0?

**Comment by miguelpuyol** [comment]
This would be really useful!

**Comment by ivantopo** [comment]
Hey folks, since version 2.0.2 the testkit is published properly as well! It was never out intention not to publish it but we had some problems in our build. Now it is up!
