### ISSUE TITLE
Kamon2 Akka2.5 Scala12 not showing metrics under Tomcat8

### ISSUE THREAD

**Issue by jaimecasero** [kamon-io/Kamon#611]
Hi,
Im using new Kamon2 2.0.0 to instrument Akka system as part of a regular War application in tomcat8. When running junit test to check metrics, i can see Akka metrics shown in Status page. Unfortuantely when i run Tomcat8, i cant see any Akka metrics shown in Status page, which seems to indicate some sort of issue. For tomcat8 im running with javaagent Kanela, still no progress.

Any clue what maybe the issue? Any kwown issue for Tomcat8 envs? Is there a way to debug Kanela/Kamon to find what is going on? Like maybe enbaling some sort of logging?

Dependencies
`       <dependency>
         <groupId>io.kamon</groupId>
         <artifactId>kamon-bundle_2.12</artifactId>
         <version>2.0.0</version>
       </dependency>  
       <dependency>
         <groupId>io.kamon</groupId>
         <artifactId>kamon-datadog_2.12</artifactId>
         <version>2.0.0</version>
       </dependency>     
<dependency>
 <groupId>io.kamon</groupId>
 <artifactId>kamon-status-page_2.12</artifactId>
 <version>2.0.0</version>`

Akka application.conf
`
kamon.instrumentation.akka.filters {

    actors.track {
      includes = [ "RestComm/user/restcommMonitoringService", "RestComm/user/restcommMediaResourceBroker", "RestComm/user/smsService","RestComm/user/CallManager","RestComm/user/ConferenceCenter","RestComm/user/BridgeManager","RestComm/user/UserAgentManager","RestComm/user/smppMessageHandler","RestComm/user/ProxyManager","RestComm/user/smppService" ]
    }

    actors.trace {
      includes = [ "RestComm/user/restcommMonitoringService", "RestComm/user/restcommMediaResourceBroker", "RestComm/user/smsService","RestComm/user/CallManager","RestComm/user/ConferenceCenter","RestComm/user/BridgeManager","RestComm/user/UserAgentManager","RestComm/user/smppMessageHandler","RestComm/user/ProxyManager","RestComm/user/smppService" ]
    }

    dispatchers {
      includes = [ "RestComm/akka.actor.default-dispatcher", "RestComm/restcomm-blocking-dispatcher" ]
    }
}

kamon {
  global-tags = ["service:restcomm-connect"]
  modules {
    datadog-agent {
      enabled = true
    }
    datadog-trace-agent {
      enabled = true
    }

  }
  datadog {
    time-units = "ms"
    #
    # Settings relevant to the DatadogAgentReporter
    #
    agent {

      # Hostname and port in which your dogstatsd is running (if not using
      # the API). Remember that Datadog packets are sent using UDP and
      # setting unreachable hosts and/or not open ports wont be warned
      # by the Kamon, your data wont go anywhere.
      hostname = "127.0.0.1"
      port = 8125

      # Max packet size for UDP metrics data sent to Datadog.
      max-packet-size = 1024 bytes
      measurement-formatter = "default"
      packetbuffer = "default"
    }

    #
    # Settings relevant to the DatadogSpanReporter
    #
    trace {

      # Default to trace agent URL
      # See: (https://docs.datadoghq.com/api/?lang=python#tracing)
      api-url = "http://localhost:8126/v0.4/traces"

      # FQCN of the "kamon.datadog.KamonDataDogTranslator" implementation
      # that will convert Kamon Spans into Datadog Spans, or "defult" to
      # use the built-in translator.
      translator = "default"

      # HTTP client timeout settings:
      #   - connect-timeout: how long to wait for an HTTP connection
      #     to establish before failing the request.
      #   - read-timeout: how long to wait for a read IO operation
      #     to complete before failing the request.
      #   - write-timeout: how long to wait for a write IO operation
      #     to complete before failing the request.
      #
      connect-timeout = 5 seconds
      read-timeout = 5 seconds
      write-timeout = 5 seconds
    }
  }
}
`

**Comment by jaimecasero** [comment]
for those interested in this approach i managed to get something working by:

1. Patching catalina code Bootstrapper,and including Kamon.init there.
2. Include kamon/akka/scala/config libs in a special bootlib dir inside tomcat
3. Configure tomcat catalina.sh CLASSPATH to include bootlib dir
4. Remove kamon/akka/scala/config libs from my webapp WEB-INF/lib dir to prevent colissions
5. Put application.conf file in bootlib dir for kamon configuration

I automated all of this using maven assembly plugin, so this is part of my regular project build.
After this, i can finally see Akka metrics, and Akka metrics for my configured Actors. It takes some time after app start for Kamon to discover the new Actors, but other than that seems to work well.

**Comment by ivantopo** [comment]
Hey @jaimecasero, thanks a lot for sharing your solution!

**Comment by Rogachev99** [comment]
Hi @jaimecasero, @ivantopo 
Could you explain why it's not working with WAR applications?
Solution provided by @jaimecasero looks too hacky for me.

**Comment by jaimecasero** [comment]
@Rogachev99 you are completely right, actually this would be a perfect definition of a hacky solution in a dictionary. It couldnt be more hacky. In a microservice world, where appServe/Tomcat is going to be used for a single WAR, this works for me, with all the hassle of maven pom corrections, and Tomcat boorstrap overloading. 

In terms of why is not working, as stated by Kamon doc, Kamon init needs to be called first thing in the java app main method. For an appServer such as Tomcat, the WAR starting is too much later than that. I can only guess Kamon.Init will start intrumentation of any matching code (akka lib..) and that needs to happen before anyone in the JVM is attempting to use it. The subsequent problem, is that all libs instrumented by Kamon.init needs to be accesible at java.main time, so we need to move them from war/lib to tomcat/lib and configure the JVM classpath accordingly.

Actually, this is a burden created in Kamon2. For kamon1 there was no Kamon.init required, and regular aspectweaver agent was used. I guess this design decision makes sense for new-wave microservice framework such as SpringBoot/Play, but for good old legacy JEE environments is a kill.

**Comment by subrotosanyal** [comment]
hi @ivantopo , hi @jaimecasero 
Is there any other solution other than patching tomcat?
I have a similar situation and the tomcat environment is not under my control..
