### ISSUE TITLE
JMX Reporter for Scala 2.13

### ISSUE THREAD

**Issue by lostiniceland** [kamon-io/Kamon#630]
The kamon-jmx artifact seems to be no longer maintained, so I cannot use it with Scala 2.13

Is there any currently working JMX-Reporter?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
