### ISSUE TITLE
Prometheus reporter with Kamon and Kanela

### ISSUE THREAD

**Issue by dlmutart** [kamon-io/Kamon#631]
We've been using the Kanela java agent for Kamon with Prometheus exporter for a long while with no issues and exporting Prometheus metrics successfully via the standard configuration.  Over the holidays, the Prometheus exporter has seemed to stop working correctly.   On startup, we get the expected result with a placeholder published as expected for the first few seconds:
# The kamon-prometheus module didn't receive any data just yet.
This suggests that the agent is working, the application is initializing Kamon, Kamon Status Page, and the Kamon Proms exporter successfully as it always has.  But a few seconds later, we get a blank page at published and it just stays blank with no metrics published.  We have made no code or configuration changes since this was working in December, and it seems to have impacted ALL of our environments including Windows and Linux.  I am starting to wonder if one of the project dependencies has a bug related to the date but really don't know where else to look for clues.

**Comment by ivantopo** [comment]
Hey @dlmutart, there was an issue with the Prometheus reporter and they way it accumulates the data, it all happened exactly on December 20th and was fixed on the 2.0.1 release of the reporter. Here is the PR that fixed it: https://github.com/kamon-io/kamon-prometheus/pull/36
