### ISSUE TITLE
Akka Actor metrics not published to Prometheus

### ISSUE THREAD

**Issue by code-colonel** [kamon-io/Kamon#632]
Hi, I'm trying to use Kamon 2.0 with Prometheus reporting in my Akka 2.5.27 application.

I'm not seeing any 'akka' metrics being published.

my pom...
` ...

        <dependency>
            <groupId>io.kamon</groupId>
            <artifactId>kamon-core_2.12</artifactId>
            <version>2.0.4</version>
        </dependency>
        <dependency>
        	<groupId>io.kamon</groupId>
        	<artifactId>kamon-akka_2.12</artifactId>
        	<version>2.0.1</version>
        	<scope>runtime</scope>
        </dependency>
        <dependency>
               <groupId>io.kamon</groupId>
               <artifactId>kamon-system-metrics_2.12</artifactId>
               <version>2.0.1</version>
               <scope>runtime</scope>
         </dependency>
         <dependency>
                <groupId>io.kamon</groupId>
                <artifactId>kamon-prometheus_2.12</artifactId>
                <version>2.0.1</version>
                <scope>runtime</scope>
       	</dependency>
      	<dependency>
                <groupId>io.kamon</groupId>
                <artifactId>kanela-agent</artifactId>
                <version>1.0.4</version>
                <scope>provided</scope>
         </dependency>
         <dependency>
               <groupId>io.kamon</groupId>
               <artifactId>kamon-logback_2.12</artifactId>
               <version>2.0.2</version>
               <scope>runtime</scope>`
         </dependency>
`
Documentation suggests all I need to do is Kamon.init() but Prometheus scrape does not include akka metrics.

Kamon Status page doen't no anything about them either....
![Kamon](https://user-images.githubusercontent.com/4900853/72237937-1ced5c00-362c-11ea-957a-e10af9f79db9.PNG)

What am I missing??

**Comment by dlmutart** [comment]
Do you have the Akka metrics extension turned on?  In application.conf:

# Enable metrics extension in akka-cluster-metrics.
akka.extensions=["akka.cluster.metrics.ClusterMetricsExtension"]

There are some other kamon settings in application.conf that we might also want to look at.

**Comment by code-colonel** [comment]
Thanks @dlmutart but I'm not using Akka Cluster (atm)

**Comment by code-colonel** [comment]
...looks like a duplicate of https://github.com/kamon-io/kamon-akka/issues/61

**Comment by mladens** [comment]
Hi, did you make sure to have `Kamon.init()` as first thing executing within main, sometimes static or mixed members might get initialized first and cause akka classes to get loaded before Kanela is attached. 

Additionally you can enable Kanela log and check whether `akka.*` gets transformed
```
kanela {
  debug-mode = true
  log-level = "DEBUG"
}

**Comment by code-colonel** [comment]
> @mladens ... did you make sure to have `Kamon.init()` as first thing executing within main, sometimes static or mixed members might get initialized first and cause akka classes to get loaded before Kanela is attached.
> 
> Additionally you can enable Kanela log and check whether `akka.*` gets transformed
> 
Unfortunately, my ActorSystem is created via a ServletContextListner in a Web Server (not in a main).  
I created a KamonServletContextListner to do the Kamon.init() (in the constructor) before the Application's ServletContextListner is run and akka classes are referenced - no luck.
I turned on Kanela debugging but saw no kanela messages in the logs.
The properties are being read/set and the server jvm shows the Kanela banner as the first thing in stdout/console so I'm pretty sure its being used.
What ahould I see as kanela debug messages?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!

**Comment by kartachena** [comment]
> > @mladens ... did you make sure to have `Kamon.init()` as first thing executing within main, sometimes static or mixed members might get initialized first and cause akka classes to get loaded before Kanela is attached.
> > Additionally you can enable Kanela log and check whether `akka.*` gets transformed
> 
> Unfortunately, my ActorSystem is created via a ServletContextListner in a Web Server (not in a main).
> I created a KamonServletContextListner to do the Kamon.init() (in the constructor) before the Application's ServletContextListner is run and akka classes are referenced - no luck.
> I turned on Kanela debugging but saw no kanela messages in the logs.
> The properties are being read/set and the server jvm shows the Kanela banner as the first thing in stdout/console so I'm pretty sure its being used.
> What ahould I see as kanela debug messages?

Hi @code-colonel 
If it's still relevant - this is most likely related to https://github.com/kamon-io/Kamon/issues/611
