### ISSUE TITLE
Integrating Kamon with akka-actor_2.10-2.1.4 and Scala scala-library-2.10.2

### ISSUE THREAD

**Issue by rubygoldbergmachineinc** [kamon-io/Kamon#636]
Hello,

I am trying to integrate Kamon Akka instrumentation with Scala 2.10 with Prometheus reporting integration. I tried to follow dependencies graph from https://mvnrepository.com/artifact/io.kamon/kamon-akka_2.10/0.6.3 with final set of maven dependencies as here:

> <dependency>
>    <groupId>io.kamon</groupId>
>    <artifactId>kamon-akka_2.10</artifactId>
>    <version>0.6.3</version>
> </dependency>

> <dependency>
>    <groupId>io.kamon</groupId>
>    <artifactId>kamon-core_2.10</artifactId>
>    <version>0.6.3</version>
> </dependency>

> <dependency>
>    <groupId>io.kamon</groupId>
>    <artifactId>kamon-scala_2.10</artifactId>
>    <version>0.6.3</version>
> </dependency>

My app currently without instrumentation uses following akka and scala lib - akka-actor_2.10-2.1.4.jar, scala-library-2.10.2.jar.  With this configuration, I get following error while starting my app.

java.lang.NoSuchMethodError: akka.actor.ReflectiveDynamicAccess.createInstanceFor(Ljava/lang/String;Lscala/collection/immutable/Seq;Lscala/reflect/ClassTag;)Lscala/util/Try;

Can someone please suggest what is compatible set of libraries here for Kamon to work?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
