### ISSUE TITLE
Prometheus metrics not show

### ISSUE THREAD

**Issue by theSemenov** [kamon-io/Kamon#638]
I have kamon for getting akka cluster metrics. In my dependencies I have:
```
libraryDependencies ++= Seq(
  "io.kamon" %% "kamon-bundle" % "2.0.1",
  "io.kamon" %% "kamon-prometheus" % "2.0.0",
)
```

And it was worked fine during this moment. Now when I go to see Prometheus metrics I don't see any metrics. 

But if I change the library to kamon-prometheus" % 2.0.1 metrics have appeared. 

I don't understand why it stops work? In my dependency nothing is changed.

e.g. I am migrating from "kamon-prometheus" % "1.1.2" to "kamon-prometheus" % "2.0.0" for the same reason. It's stop works without any reason until update version

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
