### ISSUE TITLE
Added support for Akka "affinity-pool-executor" dispatcher executor

### ISSUE THREAD

**Issue by nitayk** [kamon-io/Kamon#640]
Hey,
Currently, it seems that the only metrics being sent from Kamon are for dispatchers configured as either **fork-join-pools** or **thread-pool-executors**.
In my case, I have **affinity-pool-executor** (you can read about it [here](https://blog.scalac.io/improving-akka-dispatcher.html)) configured and I don't get the metrics for it (while I do get the metrics from a thread-pool-executor dispatcher I configured).

I am using Scala 2.11.12 with Akka 2.5.13.

> [ERROR] [k.e.Executors] - Cannot register unsupported executor service [AffinityPool(id = dispatchers.cpu-bound-dispatcher, parallelism = 2, affinityGroupSize = 512, threadFactory = MonitorableThreadFactory(sonic-actor-system-dispatchers.cpu-bound-dispatcher,false,Some(sun.misc.Launcher$AppClassLoader@18b4aac2),akka.actor.ActorSystemImpl$$anon$2@3075f5df,56), idleCpuLevel = 5, queueSelector = FairDistributionHashCache(fairDistributionThreshold = 128), rejectionHandler = akka.dispatch.affinity.ThrowOnOverflowRejectionHandler@71d710ed)]

Let me know if I need to supply any other information

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
