### ISSUE TITLE
Expose wrapped ThreadPoolExecutor and ThreadPoolExecutor

### ISSUE THREAD

**Issue by jalaziz** [kamon-io/Kamon#642]
Sometimes we need access to the methods and properties on ThreadPoolExecutor and ThreadPoolExecutor.

Unfortunately, when using `InstrumentedThreadPoolExecutor`, we lose access to the underlying ThreadPoolExecutor.

Even better would be to have `InstrumentedThreadPoolExecutor` extend `ThreadPoolExecutor`, but not sure how feasible that is without eliminating the ability to "wrap" existing executors. If `InstrumentedThreadPoolExecutor` extended `ThreadPoolExecutor` then any code expecting access to raw `ThreadPoolExecutor` methods would not need to be Kamon aware.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
