### ISSUE TITLE
not valid example code

### ISSUE THREAD

**Issue by bassmake** [kamon-io/Kamon#649]
this code is not valid:
```scala
Context
  .create(Span.ContextKey, span)
  .withKey(Key.broadcastString("userID"), Some("user-1"))
  .withKey(Key.local[Option[String]("requestID", None), Some("request-id") {
  // loggers called in this context will have access to the userID, requestID
}
```
generic parameter is missing closing `]` and there is also missing `)`
I probably should look more like this:
```
    val span = Kamon
      .buildSpan("some operation")
      .start()

    val context = Context
      .create(Span.ContextKey, span)
      .withKey(Key.broadcastString("userID"), Some("user-1"))

    Kamon.withContext(context) {
        ...
    }
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
