### ISSUE TITLE
Enhancement: option to avoid attaching raw query to spans

### ISSUE THREAD

**Issue by dominics** [kamon-io/Kamon#653]
Some of the projects where I'm currently using kamon-jdbc contain sensitive information that we're not allowed to share with third-party entities without a bunch of legal work. (There are various instances where this might be the case - mostly due to legislation, for example HIPAA or GDPR.) Yet it's still quite useful for us to have query spans in those environments, because they still give us useful timing information, the span.processing_time metric, etc. (And in development/staging environments, we can leave the full query string attached to debug things further.)

For those restricted production environments, we'd like to have the option to:
- Turn off the attachment of queries to JDBC spans, or
- Somehow sanitise the queries (e.g. to remove parameter values from parameterised queries)
  - But this second option is harder, because the behaviour of toString on a statement depends on the driver, etc.

This would avoid those projects having to e.g. transfer liability on to the systems the reporters talk to, and make sure those are also compliant when handling PII/PHI.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
