### ISSUE TITLE
Enhancement: Add weaver entry for jTDS Driver

### ISSUE THREAD

**Issue by ltronky** [kamon-io/Kamon#654]
Hi!
It would be nice to include also the jTDS driver ([http://jtds.sourceforge.net/](http://jtds.sourceforge.net/)) to the weaver.
I have done a rough test adding
```
<aspectj>
   ...
   <weaver>
      ...
      <include within="net.sourceforge.jtds.jdbc.*"/>
      <exclude within="net.sourceforge.jtds.jdbc.SharedNamedPipe"/>
   <weaver>
<aspectj>
```
to a copy of the default `aop.xml` and seems working pretty smooth.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
