### ISSUE TITLE
Hikari pool metrics are not reported (play 2.4) 

### ISSUE THREAD

**Issue by emmanuelbigarnet** [kamon-io/Kamon#655]
Hello, 
I'm facing with the problem below.
Metric kamon jdbc work correctly with kamon plugin sbt-aspectj-play-runner (1.0.4). ( slow query , hikaricp metric) 
but no in production context.

project is built with : com.typesafe.play" % "sbt-plugin" % "2.4.3"

I use : 

        "io.kamon" %% "kamon-core" % "1.1.0",
        "io.kamon" %% "kamon-play-2.4" % "1.1.0",
        "io.kamon" %% "kamon-prometheus" % "1.1.0",
        "io.kamon" %% "kamon-jdbc" % "1.0.2",
        "io.kamon" %% "kamon-system-metrics" % "1.0.0",
         "org.postgresql" % "postgresql" % "42.2.1",
        "com.zaxxer" % "HikariCP" % "2.7.8",

aop.xml is loaded with agent aspectj_weaver agent like this.

java ... -Dorg.aspectj.weaver.loadtime.configuration="$CP_PATH/conf/META-INF/aop.xml" -Dorg.aspectj.tracing.factory=debug -javaagent:$CP_PATH/lib/aspectjweaver-1.9.1.jar 

[aop.xml.txt](https://github.com/kamon-io/kamon-jdbc/files/2495077/aop.xml.txt)

thanks for your help.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
