### ISSUE TITLE
Add component tag

### ISSUE THREAD

**Issue by yarosman** [kamon-io/Kamon#656]
We don't have _component tag_ in jdbc metrics.

Used version: 
```sbt
"io.kamon"                   %% "kamon-jdbc"              %  "1.0.2"
```

jdbc_pool_borrow_time_seconds_bucket{poolVendor="hikari",poolName="HikariPool-1",le="0.005"} 275961.0
span_processing_time_seconds_bucket{operation="query",error="false",parentOperation="****",le="1.0"} 4.0

But in other kamon libraries we have such tag in metrics
component="system-metrics"
component="play.server.netty"
component="play.client.ws"
component="akka.actor"

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
