### ISSUE TITLE
org.postgresql.jdbc.PgPreparedStatement cannot be cast to kamon.instrumentation.jdbc.HasConnectionPoolTelemetry

### ISSUE THREAD

**Issue by alexmnyc** [kamon-io/Kamon#660]
org.postgresql.jdbc.PgPreparedStatement cannot be cast to kamon.instrumentation.jdbc.HasConnectionPoolTelemetry on startup using https://kamon.io/docs/latest/guides/frameworks/elementary-akka-setup/

**Comment by kubudi** [comment]
And I got this:

```class org.postgresql.jdbc.PgPreparedStatement cannot be cast to class kamon.instrumentation.jdbc.HasDatabaseTags 

(org.postgresql.jdbc.PgPreparedStatement and kamon.instrumentation.jdbc.HasDatabaseTags are in unnamed module of loader 'app')
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
