### ISSUE TITLE
Hikari pool instrumentation causes NPE when connection fails, effectively hiding the real exception

### ISSUE THREAD

**Issue by eyalfa** [kamon-io/Kamon#662]
whenever Hikari fails to connect, we get an NPE instead of the actual exception:

> 
> Caused by: java.lang.NullPointerException: null
> 	at kamon.instrumentation.jdbc.HikariPoolCreatePoolEntryMethodAdvice$.exit(HikariInstrumentation.scala:117)
> 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:510)
> 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
> 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
> 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
> 	at com.datorama.pluto.PlutoContext.$anonfun$getDBConnection$1(PlutoContext.scala:49)
> 	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
> 	at com.datorama.pluto.PlutoContext.getDBConnection(PlutoContext.scala:38)
> 	at com.datorama.pluto.sql.Jdbc$FetchSupport.connect(Jdbc.scala:71)
> 	at com.datorama.pluto.sql.Jdbc$RsState$1.$anonfun$x$11$1(Jdbc.scala:173)
> 	at com.datorama.pluto.plan.execution.Span$.wrap(TaskExecutor.scala:338)
> 	at com.datorama.pluto.sql.Jdbc$RsState$1.measured(Jdbc.scala:166)
> 	at com.datorama.pluto.sql.Jdbc$RsState$1.liftedTree1$1(Jdbc.scala:171)
> 	at com.datorama.pluto.sql.Jdbc$RsState$1.<init>(Jdbc.scala:171)
> 	at com.datorama.pluto.sql.Jdbc$.$anonfun$streamArrowMessages$2(Jdbc.scala:266)
> 	at scala.util.Try$.apply(Try.scala:209)
> 	at com.datorama.pluto.sql.Jdbc$.$anonfun$streamArrowMessages$1(Jdbc.scala:266)
> 	at akka.stream.impl.UnfoldResourceSource$$anon$1.preStart(UnfoldResourceSource.scala:35)
> 	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:306)
> 	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:593)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:701)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:750)
> 	at akka.actor.Actor.aroundPreStart(Actor.scala:543)
> 	at akka.actor.Actor.aroundPreStart$(Actor.scala:543)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:690)
> 	at akka.actor.ActorCell.create(ActorCell.scala:637)
> 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
> 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
> 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
> 	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
> 	at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedThreadPool$TimingRunnable.run(ExecutorInstrumentation.scala:428)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 

I believe the root cause is in the PoolEntry instrumentation, specifically [here](https://github.com/kamon-io/kamon-jdbc/blob/cc103794d9c6c00cd4f3771a524179054b61315c/src/main/scala/kamon/instrumentation/jdbc/HikariInstrumentation.scala#L208).
com.zaxxer.hikari.pool.HikariPool#createPoolEntry returns null in case of an exception, therefore [this code](https://github.com/kamon-io/kamon-jdbc/blob/cc103794d9c6c00cd4f3771a524179054b61315c/src/main/scala/kamon/instrumentation/jdbc/internal/PoolEntryProtectedAccess.scala#L10-L14) fails when trying to extract the connection from the pool entry, effectively hiding the real exception (Hikari intentionally swallows exceptions in this code path exposing them via an internal mechanism).

will you be willing to accept a pull-request fixing this?

**Comment by dpennell** [comment]
We are seeing the same issue.  I agree with @eyalfa's analysis.  All of the callers of createPoolEntry defend against null.

**Comment by simonnineone** [comment]
I have encountered this as well. One can temporarily set `kanela.modules.jdbc.enabled=false` to see the original exception.

What is the reason for kamon swallowing the original exception rather than rethrowing it / at least logging it? I think HikariPool correctly throws exception, there's a com.zaxxer.hikari.pool.HikariPool#checkFailFast method which does exactly that.
