### ISSUE TITLE
Flows in Akka Streams reported as `flow-X-X-unknown-operation`

### ISSUE THREAD

**Issue by sbrnunes** [kamon-io/Kamon#666]
Hi,

I've been trying to set-up some instrumentation for Akka streams. Got it working, but, even though I named all my Flows that are part of the streams, I still get this sort of names in the metrics:

`flow-0-0-unknown-operation`

A simple example of what I'm trying to do:
```
val myflow = Flow[String].named("myflow").map(println)

Source.via(myflow).to(Sink.ignore).run()
```

I basically want to see the metrics for the Actor that gets created for "myflow", with a proper name.

Is there an issue around this? Am I missing something?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
