### ISSUE TITLE
Custom dispatcher using FQCN support

### ISSUE THREAD

**Issue by rpankajakshan** [kamon-io/Kamon#668]
I have the following snippet in my application config to setup a custom dispatcher using FQCN

s3-dispatcher {
      type = "Dispatcher"
      executor = "com.a.b.s3.S3ThreadPoolExecutorConfigurator"
      maxConnections = 500
    }

s3-dispatcher does not show up in the metrics. Please could you support this?

ref - https://doc.akka.io/docs/akka/current/scala/dispatchers.html

This is on 
kamon 0.6.7
akka 2.5.6
scala 2.12

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
