### ISSUE TITLE
Customize Span building from Akka actors and messages

### ISSUE THREAD

**Issue by lmlynik** [kamon-io/Kamon#672]
Currently, the logic of creating spans is to get the actor class name and message class name.
For some systems where you create your own envelope messages, you get only `xyzActor: MyEnvelope`.

This makes tracing basically unusable for projects which choose to make their own envelopes.
A mechanism to inject a project-specific "SpanBuilder" would be useful

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
