### ISSUE TITLE
Mailbox size is wrong for BoundedMailbox

### ISSUE THREAD

**Issue by martin-g** [kamon-io/Kamon#673]
I use Akka BoundedMailbox (with size 1) but Kamon reports that its current size is much bigger, and the value increases with the time. 
I didn't see any special logic in Kamon-Akka about bounded mailboxes and I have the feeling that Kamon registers the `enqueue` call but since the messages are sent to the DeadLetters actor it won't be ever `dequeue`d for my actor and this causes the confusion in the report.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
