### ISSUE TITLE
MailBoxSize  metric with Custom mailbox

### ISSUE THREAD

**Issue by hungnt1997** [kamon-io/Kamon#675]
I have already custom my mail-box with timeout. When a message to the mail-box, if this message in mailbox exceed 2 seconds then this mailbox ignore the messge and excute the next messge. The problem for me that I see the chart with the mail-box size but it dont decrease the size of mail-box when the messge won't go to the mailbox. Can someone help me what the problem here? Thanks you!

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
