### ISSUE TITLE
Akka instrumentation doesn't work

### ISSUE THREAD

**Issue by ColOfAbRiX** [kamon-io/Kamon#678]
I know I'm vague but I can't be more precise because I don't know what's happening. I'll try to describe as much as I can, please bear with me. If needed I'll provide more details

We need Akka actor tracing in an existing and big project that uses gradle, scala 2.11 and it's split into several applications. The problem is that **I can't see any Akka data**, either metrics or tracing.

I'm using kamon-bundle 2.0.3 and kamon-jaeger 1.0.0 (2.0.0 gives a bytecode compatilibty exception)

Manual tracing done creating spans works and I can see the spans in Jaeger.

The logs show that Kanela starts because I see the banner and I can access the status page. But **I can't enable more verbose logging**. On the status page I can't see any module about Akka (not sure if I'm supposed to see something)

I followed the official documentation, guides, read opened and closed issues, migration guide, source code, i widened the filter to `"**"` and enabled `doomsday-wildcard = on` (See config at the bottom)

But still nothig and I have no idea why. My only wild guess is that the Akka module doesn't start but I can't prove this idea.

A summary of the problems I faced during this debug are:

* No metrics and tracing happens for Akka
* Impossibility to increase the log level
* Documentation not up to date (i.e. the kamon-akka readme says to include kamon-akka-2.5 1.1.0 while the documentation says to include kamon-akka 2.0.0)
* Versions for kamon-jaeger don't match (i.e. I expected to use kamon-jaeger 2.0.0 with kamon 2.0.0) there's no official documentation on what version to use

My application.conf
```
kamon {
  environment {
    service = "akka-http-service"
  }
  trace {
    tick-interval = 5 seconds
    sampler = always
  }
  jaeger {
    enabled = true
    host = 127.0.0.1
    port = 14268
    protocol = http
  }
}

kamon.instrumentation.akka {
  filters {
    actors {
      doomsday-wildcard = on
      track {
        includes = [ "**" ]
        excludes = [ "*/system/**", "*/user/IO-**" ]
      }
      trace {
        includes = [ "**" ]
        excludes = [ "*/system/**", "*/user/IO-**" ]
      }
      start-trace {
        includes = [ "**" ]
        excludes = [ "*/system/**", "*/user/IO-**" ]
      }
    }
  }
}

kanela {
  log-level = "DEBUG"
}

kamon {
  status-page {
    listen {
      hostname = "0.0.0.0"
      port = 15266
    }
  }
}

kamon.util.filters {
  "akka.traced-actor" {
    includes = [ "/**" ]
    excludes = [ "*/system/**" ]
  }
}

kamon.zipkin {
  host = 127.0.0.1
  port = 9411
  protocol = "http"
}
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
