### ISSUE TITLE
Fails to deserialize remote message when remote application does not have kamon instrumentation enabled

### ISSUE THREAD

**Issue by kpritam** [kamon-io/Kamon#680]
Support a situation where `App1` is `kamon` aware (i.e. it calls `Kamon.init()`) and `App2` is the third party and you do not have control over that which is not `kamon` aware

In that case, in akka-remote/cluster scenario, message sent from one app is not understood by other

This results in deserialization failure, shouldn't Kamon's Serializer intercepter distinguish these message and handle gracefully?

**Comment by mfulgo** [comment]
This issue also comes into play when rolling out a new version of the same app/service that enables (or disables) Kamon. It basically forces downtime, a cluster reboot, or clusters running in parallel with a hard cutover.

**Comment by SimunKaracic** [comment]
Fixed via #917
