### ISSUE TITLE
Classic Sharding Metrics are not exposed in Akka 2.6

### ISSUE THREAD

**Issue by nathanmbrown** [kamon-io/Kamon#682]
We are using Akka 2.6 but still using Classic Cluster Sharding.
It seems the ShardingInstrumentation is only enabled on 2.5 (see [here](https://github.com/kamon-io/kamon-akka/blob/master/instrumentation/common/src/main/scala/kamon/instrumentation/akka/remote/ShardingInstrumentation.scala#L15)).

Can this be made configurable somehow rather than being hard tied to the version?

**Comment by SimunKaracic** [comment]
This was fixed way back in March, we just forgot to close it!
It should work on akka 2.5 and 2.6!
