### ISSUE TITLE
Application is broken when libsigar-amd64-linux.so is not writable (?)

### ISSUE THREAD

**Issue by StephenKing** [kamon-io/Kamon#683]
I am very sure that the `native/libsigar-amd64-linux.so` file was actually readable for the user that should run the application, but it reported a log message "Permission Denied" and then (in contrast to kamon-io/kamon-system-metrics#10) **continues** to start the application.

In our case, it attracted traffic from the rest of the Akka cluster, but did not respond back (and also not log anything further).

If this cannot be reproduced, I can give it again a try with higher log levels.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
