### ISSUE TITLE
Figure out how to turn certain metrics as gauges for the prometheus reporter

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#687]
This is a follow up from the discussion on this PR: https://github.com/kamon-io/kamon-system-metrics/pull/11

**Comment by pnerg** [comment]
As I was browsing open tickets I came across this one....yes I had a boring evening...:)
Perhaps this PR #1011  is the answer for how to turn certain metrics into histograms.
If so then you can close this ticket...one less in the backlog as I say

**Comment by SimunKaracic** [comment]
Please have more boring evenings in the future! :D
