### ISSUE TITLE
Make error cases customizable

### ISSUE THREAD

**Issue by mladens** [kamon-io/Kamon#688]
Currently both 500 and 400 families of error codes result in span marked as error. This is not convenient when we don't control the clients whose bad requests pollute metrics hiding local errors in the noise.

There should be a config setting to decide whether 4xx should be considered an error or not.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
