### ISSUE TITLE
Kamon trace context is not propagated when nesting Futures

### ISSUE THREAD

**Issue by n1ko-w1ll** [kamon-io/Kamon#689]
Hi @ivantopo,

like discussed in Gitter, I found an issue that the trace context is not propagated when you have nested CompletionStages (Java) like in such a route definition:

```
completeOKWithFuture(ask(greetings, "hello", REQUEST_TIMEOUT)
  .thenCompose(result -> ask(greetings, result, REQUEST_TIMEOUT)), Jackson.marshaller())
```

The first ask to `greetings` gets the right trace context, but the second ask in the `thenCompose` gets an empty context.

I uploaded a reproducible here: https://github.com/n1ko-w1ll/kamon-akka-java

Best regards
Niko

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
