### ISSUE TITLE
Provide Java kompatible API for TracingDirectives

### ISSUE THREAD

**Issue by n1ko-w1ll** [kamon-io/Kamon#690]
Hi,

the KamonTracingDirective is not usable with the Java language. I guess it just needs a proper RouteAdapter definition with a delegate of the original directive like the akka-http PathDirectives have:

```
  def path(segment: String, inner: Supplier[Route]): Route = RouteAdapter {
    D.path(segment) { inner.get.delegate }
  }
```

Best regards
Niko

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
