### ISSUE TITLE
Context is not propagated to RejectionHandler and ExceptionHandler

### ISSUE THREAD

**Issue by sebarys** [kamon-io/Kamon#691]
Hello,
I was using `0.6.6` kamon version.
In our application we were using `Tracer` and `TraceLocal` for context initialisation, e.g. 
```
// somewhere in the code to initialise context
Tracer.setCurrentContext(Kamon.tracer.newContext("some-context"))
TraceLocal.storeForMdc("contextTraceId", contextTraceId)
```
Thanks for this I was able to use set values in logs  (logback) using fucnction `kamon.trace.logging.MdcKeysSupport#withMdc` from kamon library.

In new version (`1.0.0`) we are trying to use `Context` but in akka-http RejectionHandler and ExceptionHandler my Context Keys values are not accessible ( I could not find any other solution in documentation ). Below example of our new setup:

```
val contextTraceKey = LogbackContextTraceIdConverter.ContextTraceIdKey 
//in my logback: <conversionRule conversionWord="contextTraceId" converterClass="com.some.package.LogbackContextTraceIdConverter" />

//somewhere on application
Kamon.withContext(Context()
          .withKey[String](contextTraceKey, "contextTraceId")) {

     logger.info("In the main thread with context")
     Future {
        Thread.sleep(10000)
        logger.info("Inside future with context")
     }

     throw new Exception("Test exception")
}

//Exception handler
ExceptionHandler {
  case ex: Exception =>
    // this will be logged without context values
    logger.error("ErrorHandler - Unexpected error: ", ex)
    makeErrorResponse(StatusCodes.InternalServerError, ex.getMessage, None)
}

```
Two first logs (in main thread and in the future) contains propagated in Context value. Unfortunately log from ExceptionHandler do not contain it.
Could you look into this issue or explain how I can propagate that value in other way to make it accessible in places like RejectionHandler or ExceptionHandler

Thank you for your help!
Regards,
sebarys

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
