### ISSUE TITLE
Getting difference in request response times between 0.6.8 and 1.1.0

### ISSUE THREAD

**Issue by jorkzijlstra** [kamon-io/Kamon#692]
So we have opted to upgrade to the latest version from 0.6.8 to 1.1.0. Including this change was a switch over from Grafana to Prometheus.
So I'm not sure which one is causing the issues.

Test case:
- same application
- same AWS regions (us-west-2) although different K8s stacks
- recieves axactly the same data on both application instances

Differences:
- one application uses kamon akka http 0.6.8 and exports to Graphite 
- one application uses kamon akka http 1.1.0 and exports to Prometheus with scraping interval of 15s 

We have some dashboard upon this data and we noticed some significant differences in request response (elaped-time / span_processing_time_seconds_bucket) times

Grafana dashboard based upon Graphite data:
![graphite](https://user-images.githubusercontent.com/15804835/40722386-789a23a0-641c-11e8-92bb-737be2298eaf.png)

Query: `groupByNode(sports.$environment.api.*.service.trace.api.elapsed-time.50thPercentile, 6, 'avg')`

Grafana dashboard based upon Prometheus data:
![prometheus](https://user-images.githubusercontent.com/15804835/40722390-7c7f4cca-641c-11e8-8941-b076209b08eb.png)

Query: `histogram_quantile($quantile, sum(rate(span_processing_time_seconds_bucket{application_id="api"}[$interval])) by (operation, http_status_code, le))
`
Where $quantile = 0.50 and $interval = 30s

As you can see there is well over 100ms of difference in response times and we have actually seen an even bigger difference. So we are wondering what might be causing this difference and if its correct or not or that we are querying wrong.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
