### ISSUE TITLE
How can I turn off traces for some of the routes?

### ISSUE THREAD

**Issue by lustefaniak** [kamon-io/Kamon#694]
I have two healthcheck routes in my application, and I trace 1% of the traces. Unfortunately right now most of my traces in Stackdriver are about those two healthcheck routes - they are queried every 10s on 3 nodes. Is there way how can I cancel trace generation for specific route?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
