### ISSUE TITLE
Clarify what times to expect when tracing requests on server with streamed request

### ISSUE THREAD

**Issue by jrudolph** [kamon-io/Kamon#695]
It seems that in https://github.com/kamon-io/kamon-akka-http/blob/d164eec06804f1dcccc8bb3f327f2ff1e9ed5fc3/kamon-akka-http/src/main/scala/kamon/akka/http/instrumentation/ServerFlowWrapper.scala#L57-L67

a span is started as soon as an `HttpRequest` is received. However, for streamed requests that doesn't mean that the request body was actually fully received. When you then use an `entity(as)` or similar directive inside of the trace the trace time is including the time for receiving the request body. It means that you cannot use those times to measure the performance of the server because it includes time spans that are completely depending on the client side / network. Is that expected or documented somewhere?

We got [reports](https://groups.google.com/forum/#!topic/akka-user/-_C9jCPDwts) of people that were surprised to see bad latencies with akka-http that might be caused by this.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
