### ISSUE TITLE
Support for Akka cachedHostConnectionPoolHttp

### ISSUE THREAD

**Issue by Lazu13** [kamon-io/Kamon#696]
Are You planning to add any type of support/wrapper for ` Http().cachedHostConnectionPoolHttp()` ?

**Comment by nathanmbrown** [comment]
Kamon appears to work with `Http().cachedHostConnectionPoolHttp()` since Akka HTTP 10.2.0 so this seems obsolete.

**Comment by SimunKaracic** [comment]
Nice find, closing! :D 
Thanks for the help @nathanmbrown
