### ISSUE TITLE
Streamed Result Tracing

### ISSUE THREAD

**Issue by cchampignon** [kamon-io/Kamon#703]
I'm trying to trace a streamed result. I would expect to see a span duration of ~10s in my SpanReporter using the following controller action, but instead see ~100ms. Reading the code it appears that the span.finish() is occurring when the source is ready and not when it is complete. Would it be possible to trace requests in this manner?
```
def index()  = Action {
  val content: Source[ByteString, NotUsed]  = Source(1 to 5).map{x =>
    Thread.sleep(2000)
    ByteString(x.toString)
  }

  Ok.sendEntity(Streamed(content, None, None))
}
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
