### ISSUE TITLE
Provide status code and request url for netty integration

### ISSUE THREAD

**Issue by nicolasblaye** [kamon-io/Kamon#706]
Hi,

At Powerspace, @sderosiaux made a fork of kamon-play to adapt it for netty. I noticed that he integrated this change to the base repo but with some adaptation. 

In the custom version we use, we have these kind of metrics:
`span_processing_time_seconds_count{http_verb="GET",operation="http-request",error="true",http_status_code="503",http_url="/ndi/:positionShortCode"}`

With the kamon 1.1.0 version, I see:
`span_processing_time_seconds_count{http_method="GET",operation="ndi.positionShortCode.get",error="true",span_kind="server",component="play.server.netty"`

I was wondering if you intend to add some of the metrics above like `status code` or `url`, which are quite useful for our graphana. We have a use case where knowing the status code is needed, and urls provide nice legends.

I would gladly provide some help on that issue, but I was wondering why it wasn't added there https://github.com/kamon-io/kamon-play/pull/19?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
