### ISSUE TITLE
Serialize HttpHeaders to the outgoing response

### ISSUE THREAD

**Issue by dispalt** [kamon-io/Kamon#707]
Probably need to do something like 

```scala
result.withHeaders(Kamon.contextCodec().HttpHeaders.encode(Kamon.currentContext()).values.toSeq: _*)
```

In the error and non error case in the `RequestHandlerInstrumentation` https://github.com/kamon-io/kamon-play/blob/0dad63b8c8bfe28a7f96e37fd4fb9e50cf0259b7/kamon-play-2.6.x/src/main/scala/kamon/play/instrumentation/RequestHandlerInstrumentation.scala#L55

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
