### ISSUE TITLE
Initialize OperationNameFilter twice

### ISSUE THREAD

**Issue by yarosman** [kamon-io/Kamon#708]
The  OperationNameFilter initialize twice

[info] [kamonTraceId=91bc3d17f44dd9cd, kamonSpanID=8df27b93e0894d24] - p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

**kamon.play.OperationNameFilter**
**kamon.play.OperationNameFilter**
  http.filters.TracingContextFilter
  http.filters.AccessLoggingFilter
  http.filters.ShutdownFilter
  http.filters.ContentSecurityHeadersFilters

I think it occurred because we have the same aspect in [AkkaHttpRequestHandlerInstrumentation](https://github.com/kamon-io/kamon-play/blob/master/kamon-play-2.6.x/src/main/scala/kamon/play/instrumentation/AkkaHttpRequestHandlerInstrumentation.scala#L60)
and [NettyRequestHandlerInstrumentation](https://github.com/kamon-io/kamon-play/blob/master/kamon-play-2.6.x/src/main/scala/kamon/play/instrumentation/NettyRequestHandlerInstrumentation.scala#L61)
```
@Around("call(* play.api.http.HttpFilters.filters(..))")
  def filters(pjp: ProceedingJoinPoint): Any = {
    filter +: pjp.proceed().asInstanceOf[Seq[EssentialFilter]]
}
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
