### ISSUE TITLE
DataDogAgentReporter not sending data

### ISSUE THREAD

**Issue by mkeshav** [kamon-io/Kamon#715]
Hi,
   I will explain our setup so there is context.

Our applications are deployed on ECS cluster as docker containers. Datadog agent runs next to the app container. In this setup, when i use DataDogAgent reporter, I do not see any data in datadog.

I used StatsDReporter from kamon-statsd and it is successful in sending the data. I am a bit confused as both of them use the same port (8125) to send data. 

I briefly looked at the difference in code in the 2 reporters, StatsD one has long living channel, whereas Datadog one opens the channel before flushing and closes it. I was not sure hence didn't raise a PR

Please let me know if you have heard/faced this problem. I am happy to fix it and raise PR.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
