### ISSUE TITLE
TimeUnit can not be changed when using DatadogAgentReporter 

### ISSUE THREAD

**Issue by bamboosch** [kamon-io/Kamon#716]
The configuration parameter timeUnit has no effect on the DatadogAgentReporter. 
Regardless of what I configure, the payload always contains ms:

`span.processing-time:5.234491392|ms`

Furthermore, it looks like the scaling is not correct. The processing time was about 5 seconds, therefore the value should be 5234.491392 in case of milliseconds or am I wrong?

I'm using version 1.0.0

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
