### ISSUE TITLE
UnresolvedAddressException in Reporter can never recover

### ISSUE THREAD

**Issue by Voltir** [kamon-io/Kamon#717]
We are using Kubernetes, deploying some scala apps in containers that report to datadog via kamon. We noticed that occasionally, any of these pods could end up being unable to report metrics and looking through the logs of the impacted container we see this reoccurring error:
```
2018-11-27 23:08:30,032 ERROR[ogAgentReporter] k.ReporterRegistry$Default$MetricReporterTicker - Reporter [kamon.datadog.DatadogAgentReporter] failed to process a metrics tick.
java.nio.channels.UnresolvedAddressException: null
    at sun.nio.ch.Net.checkAddress(Net.java:101)
```
The current work-around we have been using is to restart the pod. However, looking at 
https://github.com/kamon-io/kamon-datadog/blob/master/src/main/scala/kamon/datadog/DatadogAgentReporter.scala#L177

It seems that a small refactor could make the reporter able to recover from this error on its own. What I think is happening is that there is a race condition in the order in which pods start - if one of our application pods becomes online before the datadog pods have sorted themselves out, it is possible that the ip addr for the datadog agent isn't quite available, but come online soon. However, the reporter only tries to resolve the address one time and then is stuck forever with whatever value it received. Changing it to a def such that it re-resolves the ip address for the agent seems like a potential solution to our issue.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
