### ISSUE TITLE
Make API reporter extendable

### ISSUE THREAD

**Issue by KOnaitis** [kamon-io/Kamon#718]
We moved to Kamon 1.0 from 0.6 and started using `DatadogAPIReporter` with a slightly modified version of `DatadogLegacyWrapper` (from [#21](https://github.com/kamon-io/kamon-datadog/issues/21)). However, we are running into more problems with the reporter.
Right now, the API reporter tries to submit a metric and if the request fails it gets logged and that's that. 
This causes 2 problems:
  * There is no way to retry the request.
  * There is no way to bring down the log level or change the message of the log.

Both of these problems stem from the fact that `reportPeriodSnapshot` does not return anything. Which means, that even if we use approach similar to `DatadogLegacyWrapper` there is no way to tell what happened to the request and act accordingly. And since all of `DatadogAPIReporter` fields and methods are `private` it is impossible to extend it. 
Obviously, we would prefer that you would solve the problems we're facing on your end. However, we recognize that while the first problem seems quite generic, the second problem might be too specific to our use case for you to implement it. The only option we have right now is to rewrite `kamon-datadog` according to our needs. But before doing that, we were wondering whether you could make the API reporter extendable so we would only need to worry about high-level decisions of metric submission. Additionally, it would probably make the transition from 0.6 to 1.0 easier for others.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
