### ISSUE TITLE
Payload is not in the expected format

### ISSUE THREAD

**Issue by ollis** [kamon-io/Kamon#719]
Hi, I experience an error when i try to use the DatadogAPIMetricsSender. It seems like the json body is not correctly formated. The error that is logged is:
`
[ERROR] [10/06/2017 13:18:01.239] [kamon-akka.actor.default-dispatcher-8] [akka://kamon/user/datadog-metrics-sender] Datadog request failed, some metrics may have been dropped: NettyResponse {
	statusCode=400
	headers=
		Date: Fri, 06 Oct 2017 11:18:01 GMT
		Content-Type: text/plain; charset=utf-8
		Content-Length: 80
		Connection: keep-alive
		DD-POOL: propjoe
		X-Content-Type-Options: nosniff
		Strict-Transport-Security: max-age=15724800;
	body=
Payload is not in the expected format: invalid character ':' after array element
`

The body is like this:
`["metric": "kamon.system-metric.cpu-idle.min", "points": [
	[1507288599795, 52.0]
], "type": "gauge", "host": "xxx", "tags": []], ["metric": "kamon.system-metric.cpu-idle.max", "points": [
	[1507288599795, 77.0]
], "type": "gauge", "host": "xxx", "tags": []], ` and so on.

Version 0.6.8 is used.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
