### ISSUE TITLE
Span marks nano precision

### ISSUE THREAD

**Issue by mladens** [kamon-io/Kamon#720]
Reporter cuts off span mark precision at millis (Kamon uses nanos). It should pass on nano timestamps.

child of https://github.com/kamino-apm/kamino/issues/134

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
