### ISSUE TITLE
 The percentiles computed by statsd from kamon-statsd connector are wrong.

### ISSUE THREAD

**Issue by RomanBrodetski** [kamon-io/Kamon#721]
Kamon aggregates the histogram data within `kamon.metric.tick-interval`, and uses rates to send it to statsd. For example, the following measures:
```
1.0 sent 80 times
2.0 sent 70 times
3.0 sent 62 times
4.0 sent 55 times
5.0 sent 45 times
6.0 sent 36 times
7.0 sent 27 times
8.0 sent 18 times
9.0 sent  9 times
```

Result in the following message to statsd:
```
1.0|ms|@0.0125:2.0|ms|@0.014084507042253521:3.0|ms|@0.016129032258064516:4.0|ms|@0.018518518518518517:5.0|ms|@0.022222222222222223:6.0|ms|@0.027777777777777776:7.0|ms|@0.037037037037037035:8.0|ms|@0.05555555555555555:9.0|ms|@0.1111111111111111
```

But statsd seems to ignore the `rate` for the purpose of median/percentiles calculation. So, in this case, the median computed by statsd and shown in grafana is `5`, but it should be `3`.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
