### ISSUE TITLE
StatsDReporter "caches" hostname dns resolution

### ISSUE THREAD

**Issue by brunoballekens** [kamon-io/Kamon#722]
The StatsDReporter resolves the passed hostname to an `InetSocketAddress` when started.
If at that time the dns resolution does not work, it will always throw a java.nio.channels.UnresolvedAddressException.
Also when the statsd server is moved (change of ipaddress), we need to restart to have the data sent to the new ipaddress.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
