### ISSUE TITLE
Add support for KafkaCollector

### ISSUE THREAD

**Issue by mbuccini** [kamon-io/Kamon#723]
Hello, 

I would like to propose to add a new reporter. Here at my company we are using KafkaCollector with Zipkin, so that we don't depend on the http service. 

Would it be of interest for you, if I created a PR with the support for Kafka?

At the moment, the quickest way for me was to fork the project and change the implementation to have simply something like:
```
AsyncReporter.create(
      KafkaSender.newBuilder().topic(kafkaZipkinTopic).bootstrapServers(kafkaBootstrapServers).build()

    )
```

However, if we want to proceed, we'd need to extract part of the Zipkin project so that we could have separate modules like "zipkin-http" and "zipkin-kafka", and so forth. This implies having a "kamon-io.zipkin-core", though, that will be necessary for the individual reporters. Or, if you have other ideas, so that we don't break backward compatibility, please let me know. The only reason would be not to add any unnecessary dependencies for those who don't want to include kafka in their projects.

PS: thanks a lot for creating such powerful tools!

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
