### ISSUE TITLE
Zipkin reporter not sending trace data any more if connectivity with zipkin server get broken

### ISSUE THREAD

**Issue by shekh-akther** [kamon-io/Kamon#724]
Hello, 

We are using Kamon in (spring boot + akka) application to send trace data to zipkin.  The issue is related to kamon zipkin reporter connectivity. Whenever the connectivity is broken between zipkin server and client application (connected via kamon zipkin), client application does not send traces any more to zipkin server. In client application log we have something like: z.r.AsyncReporter$BoundedAsyncReporter#280 Dropped 51 spans due to IllegalStateException... 

We are using following dependencies:
aspectjweaver.version 1.9.0
kamon.akka.version 1.0.0
kamon.core.version 1.1.0
kamon.logback.version 1.0.0
kamon.zipkin.version 1.0.0

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
