### ISSUE TITLE
No 2.0.2 for scala 2.13

### ISSUE THREAD

**Issue by sjoerdmulder** [kamon-io/Kamon#725]
It seems that 2.0.2 is not published for scala 2.13 but is for 2.11 and 2.12

https://search.maven.org/search?q=kamon-zipkin

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
