### ISSUE TITLE
Add hostname & ip as process tags

### ISSUE THREAD

**Issue by japgolly** [kamon-io/Kamon#728]
If you use the Jaeger client directly, it adds `hostname` and `ip` tags as process tags which show up in the UI like this:
http://www.hawkular.org/img/blog/2017/2017-04-19-jaeger-trace.png

It would be great if the kamon jaeger reporter did this too.

It seems that calling [`process.setTags` like this](https://github.com/jaegertracing/jaeger-client-java/blob/94162341643e2d691d37887309c52a1ab98da861/jaeger-core/src/main/java/com/uber/jaeger/senders/ThriftSender.java#L61), in the reporter [here during initialisation](
https://github.com/kamon-io/kamon-jaeger/blob/master/src/main/scala/kamon/jaeger/JaegerReporter.scala#L57) is all that will be needed.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
