### ISSUE TITLE
GZIP/Deflate HTTP POST requests

### ISSUE THREAD

**Issue by pjfanning** [kamon-io/Kamon#730]
https://github.com/kamon-io/kamon-influxdb/pull/2#issuecomment-273412448

I have a basic prototype solution in the similar code in kamon-spm (https://github.com/kamon-io/kamon-spm/issues/5).

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
