### ISSUE TITLE
Kamon Time Units

### ISSUE THREAD

**Issue by pkhamutou** [kamon-io/Kamon#732]
Hello,

I was able to successfully set up Kamon (Scala) with InfluxDB but all trace timers are stored in `ns`. Is there a way to store it in `ms`?

Best,
Pavel Khamutou

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
