### ISSUE TITLE
404 Not found when database does not exist.

### ISSUE THREAD

**Issue by TimSoethout** [kamon-io/Kamon#733]
In the debug logs of the application with Kamon, I saw some `404 not found` of the `ASyncHttpConnector`.

After creating the database in InfluxDB (`mydb` as default setting), it started working.

Although I'm still getting:
`[info] [DEBUG] [06/19/2017 17:31:15.269] [AsyncHttpClient-2-2] [InfluxDBHttpClient(akka://kamon)] 204 No Content`

Would it be possible to create the database if it does not exist?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
