### ISSUE TITLE
udp is not supported

### ISSUE THREAD

**Issue by cwei-bgl** [kamon-io/Kamon#734]
Hi I follow the configuration protocol = "udp", but it does not seem to work. I looked into the source code. It does not seem to populate protocol configuration in kamon.influxdb.InfluxDBReporter implementation.

With http protocol, when influxdb server can not be connected, I think this should not be reported as error(maybe warning) or at least configurable. As this is app stats information, which is not so critical.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
