### ISSUE TITLE
Cannot specify global tags programatically

### ISSUE THREAD

**Issue by carwynellis** [kamon-io/Kamon#735]
I'd really like to be able to specify global tags programatically by passing them to the InfluxDBReporter constructor. 

It seems that Kamon doesn't support this at the moment. The only way I can set global tags is through config, which doesn't work for my use case.

It's trivial to implement so I'm happy to raise a PR for this provided you think this is the right place to do this?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
