### ISSUE TITLE
Mutliple requests sent after influxdb outage

### ISSUE THREAD

**Issue by carwynellis** [kamon-io/Kamon#736]
We recently experienced some brief downtime with our influxdb instance. When it came back up the influx metrics reporter started sending two requests on each snapshot. One request would fail since it didn't have the correct configuration (missing credentials). The other would succeed.

I've got as far as isolating the cause to okhttp and have worked around it for now by implementing my own reporter that uses a different HTTP client library. I'm not sure what's going on inside okhttp to cause this additional request to get sent but I couldn't isolate it in the debugger.

It's consitently reproducable however, with the following steps
* start an app sending metrics to influxdb
* stop influx db and observe connection errors in the app log
* start influx again and confirm the app is now sending metrics again

At this point in the influxdb log you should see two requests being sent at each reporting interval.

In our case the failing request was not reported in the app log at all suggesting it's happening somewhere in the internals of okhttp.

My new implementation using the http4s client does not exhibit this behaviour which points to something strange going on in okhttp.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
