### ISSUE TITLE
Update okhttp to version 3.14.2

### ISSUE THREAD

**Issue by sebtomba** [kamon-io/Kamon#738]
The `kamon-zipkin` reporter has a dependency on `"io.zipkin.reporter2" % "zipkin-reporter" % "2.7.14"` which has a strict dependency on the newer `okhttp` version `3.14.2`. We are using both Kamon reporters in our project and getting now an
```
org.apache.ivy.plugins.conflict.StrictConflictException: com.squareup.okhttp3#okhttp;3.9.1 (needed by [io.kamon#kamon-influxdb_2.12;2.0.0-RC1]) conflicts with com.squareup.okhttp3#okhttp;3.12.1 (needed by [io.zipkin.reporter2#zipkin-sender-okhttp3;2.7.14])
```

As a workaround we have added  in our `build.sbt` an `exclude("com.squareup.okhttp3", "okhttp")` for the `kamon-influxdb` dependency.

I know it's a lot to ask, but could you update your `okhttp` dependency to `3.14.2` and keep it in sync with the `kamon-zipkin` transitive `okhttp` dependency?

**Comment by bradrust** [comment]
FWIW, I was getting some exceptions relating to HttpHeaders.hasBody which is a removed internal method.   all related to older versions of zipkin-reporter.

I include these dependencies to upgrade the older ones referenced in the kamon dependencies.

  "io.zipkin.reporter2" % "zipkin-reporter" % "2.15.0",
  "io.zipkin.reporter2" % "zipkin-sender-okhttp3" % "2.15.0",

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
