### ISSUE TITLE
Sending interval cannot be set

### ISSUE THREAD

**Issue by jgordijn** [kamon-io/Kamon#740]
In the statsD reporter it is possible to have a different tick interval and flush interval. The tick interval seem to control the interval at which metrics are collected. The flush interval controls the frequency at which the collected info is send to the backend.

The kamon-graphite reporter has a flush-interval (in the reference.conf), but it isn't used by the code.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
