### ISSUE TITLE
UDP support

### ISSUE THREAD

**Issue by dspasojevic** [kamon-io/Kamon#741]
Hi,

We have a separate graphite UDP implementation that borrow heavily from kamon-statsd. Would you be interested in a PR from https://github.com/agiledigital/kamon-graphite ?

Thanks,
-Dan

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
