### ISSUE TITLE
Metric scaling support

### ISSUE THREAD

**Issue by jeanmarc** [kamon-io/Kamon#742]
Hi, I was looking at using kamon-graphite instead of kamon-statsd, but there is no support yet for scaling the metrics. At my company, all time/duration metrics are stored in milliseconds, as opposed to the default nanoseconds of Kamon.
kamon-statsd supports 'time-units' configuration that allows us to scale the metrics properly.

I propose to add the same feature to kamon-graphite and will submit a pull request for this (if that is OK with you).

Regards,

Jean-Marc.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
