### ISSUE TITLE
Getting memory leak, adding snapshot of our analysis

### ISSUE THREAD

**Issue by ashokwaghmare** [kamon-io/Kamon#746]
<img width="1401" alt="screen shot 2018-06-23 at 10 04 09 am" src="https://user-images.githubusercontent.com/4383700/41805735-4d6cad9c-76cd-11e8-96af-77b4e7465e09.png">
<img width="1400" alt="screen shot 2018-06-23 at 10 03 45 am" src="https://user-images.githubusercontent.com/4383700/41805748-58bb9bf4-76cd-11e8-8a4a-1631fb5554bc.png">
<img width="1078" alt="screen shot 2018-06-23 at 10 05 44 am" src="https://user-images.githubusercontent.com/4383700/41805756-61cd0b4c-76cd-11e8-8599-26be3ec890c1.png">

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
