### ISSUE TITLE
Allowing kamon-prometheus PrometheusReporter snapshotAccumulator duration to be configurable

### ISSUE THREAD

**Issue by jip297** [kamon-io/Kamon#748]
_sbt: kamon-prometheus_2.11:1.0.0:jar
Manifest-Version: 1.0
Implementation-Title: kamon-prometheus
Implementation-Version: 1.0.0
Specification-Vendor: io.kamon
Specification-Title: kamon-prometheus
Implementation-Vendor-Id: io.kamon
Specification-Version: 1.0.0
Vcs-Release-Tag: v1.0.0
Implementation-Vendor: io.kamon
Vcs-Release-Hash: 6cc6532d8626ac2cde8b6b1b0733f2be9f95c781_

At the moment the duration of the snapshotAccumaltor is 5 years.

This caused me problems because I had refined gauge metrics that I wanted to delete, but because of the snapshotAccumulator they would still be presented even after having been removed.

As a workaround I used java reflection to overwrite the duration.

Would it be possible to make the duration configurable?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
