### ISSUE TITLE
Allow custom buckets to be applied to metric prefixes / regexes

### ISSUE THREAD

**Issue by jalaziz** [kamon-io/Kamon#750]
The current custom bucket configuration can be a bit tedious if you want to override buckets for a class of related metrics.

It would be nice to support metric name prefixes and possibly even regex expressions when configuring custom buckets. Prefixes should not introduce much of a performance impact with the right lookup data structure and would probably be sufficient for most use cases.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
