### ISSUE TITLE
Allow selecting distribution metrics to be exposed as summaries instead of histograms

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#751]
Take a look [here](https://gitter.im/kamon-io/Kamon?at=5acf18021130fe3d36cb986d) and a bit bellow.

As discussed by @StephenKing and @kodemaniak there are a few metrics that could or maybe even should be exposed as summaries instead of histograms, maybe even gauges. I personally prefer the idea of summaries cause they can tell a bit more about behavior than a simple gauge but I'm open to discuss it :). These changes would be most certainly applied to JVM and System metrics when exposed to Prometheus.

**Comment by chetanmeh** [comment]
> Is it not possible to map range samplers to 3 prometheus gauges, current, max and min?
> This would seem more intuitive in prometheus and a reasonable compromise?

@ivantopo What are your thoughts for above suggestion from @hamishforbes where RangeSampler should be mapped to 3 guages which are cheaper compared to quantiles. Would that be more suitable way for expressing range samples
