### ISSUE TITLE
fi.iki.elonen.NanoHTTPD$Response send: SEVERE: Could not send response to the client

### ISSUE THREAD

**Issue by alexmnyc** [kamon-io/Kamon#754]
Seeing a bunch of these errors in the logs

SEVERE: Could not send response to the client
java.net.SocketException: Broken pipe (Write failed)

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
