### ISSUE TITLE
Update Port, Path and servlet context in Kamon-Prometheus

### ISSUE THREAD

**Issue by dgoel5** [kamon-io/Kamon#756]
I have integrated with Kamon-Prometheus and the application comes up at localhost:9095. I have requirement to use different port and provide path like localhost:8080/metrics. I was able to change the port with config "kamon.prometheus.embedded-server.port = 8080", but did not find any way to provide the path like "/metrics"

As in our platform, we can only have ingress on 8080 port, but we have akka-http running on 8080 port, so to expose the kamon-prometheus metrics, we need to use the same web server running localhost:8080 and register kamon-prometheus metrics in different servlet context. Is it possible, can you please provide us the way to do that

**Comment by KeesCBakker** [comment]
Any updates on this?

**Comment by SimunKaracic** [comment]
The endpoint will now always be `/metrics`, which is the prometheus default.
Feel free to reopen if you see a need to expose additional paths!
