### ISSUE TITLE
Assign operation names to HTTP client requests from config

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#769]
It is possible to assign names to HTTP operations from configuration, but only for the server side. @lacarvalho91 pointed out [on Gitter](https://gitter.im/kamon-io/Kamon?at=5ea269f111ffed12682f260d) that it would be great to have this for the client side as well and indeed, that would be great!

**Comment by lacarvalho91** [comment]
@ivantopo I raised https://github.com/kamon-io/Kamon/pull/771 to address this

**Comment by lacarvalho91** [comment]
@ivantopo I've addressed your comments on the PR, let me know if there's anything else
