### ISSUE TITLE
Fix counter metric documentation

### ISSUE THREAD

**Issue by pgorin** [kamon-io/Kamon#782]
Hi, great work as usual :)
I little issue on Kamon Metrics usage documentation:
https://kamon.io/docs/latest/core/metrics/#counters

In order to increment a counter for example is necessary to use withoutTags after referencing the counter metric. For example:
Kamon.counter("unit-increments").withoutTags()

Thanks again for all the team!
Regards,
Patricio.

**Comment by SimunKaracic** [comment]
Fixed in the latest documentation!
