### ISSUE TITLE
failed to process a metrics tick. java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by elhalouiMed** [kamon-io/Kamon#795]
I'm using kamon for collecting metrics in my application and it's a strong tool for supervising the state of actors, but after many hours of runing , the application shutdown with outOfMemory error caused by kamon. 
here is my configuration 
kamon {
	modules.status-page.enabled = true
	status-page {
	    listen {
	      hostname = "0.0.0.0"
	      port = 5266
	    }
	  }

	instrumentation.akka.filters {
	  actors.track {
	    includes = [ "application/user/**" ]
	  }

	  dispatchers {
	    includes = [ "**" ]
	  }

	  routers {
	    includes = [ "**" ]
	  }
	}
	prometheus {
		start-embedded-http-server = true
		embedded-server {
			hostname = 0.0.0.0
			port = 9095
		}
		buckets {
			default-buckets = [
			10,
			30,
			100,
			300,
			1000,
			3000,
			10000,
			30000,
			100000
			]

			time-buckets = [
			0.005,
			0.01,
			0.025,
			0.05,
			0.075,
			0.1,
			0.25,
			0.5,
			0.75,
			1,
			2.5,
			5,
			7.5,
			10
			]

			information-buckets = [
			512,
			1024,
			2048,
			4096,
			16384,
			65536,
			524288,
			1048576
			]
		}
	}

}

**Comment by ivantopo** [comment]
Hey @elhalouiMed, do you have a heap dump that can tell where the memory is being spent?

I noticed you have this in your configuration:

```
  actors.track {
    includes = [ "application/user/**" ]
  }
```

Tracking every actor individually can produce an insane amount of metrics, which in turn consume memory, and then some more memory will be required for the Prometheus reporter to generate the output. Is there any reason why actor group metrics are not enough to monitor your actors? They are enabled by default and should cover most of the common use cases!

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
