### ISSUE TITLE
Feature: Make it possible to append custom HTTP headers in the response

### ISSUE THREAD

**Issue by pnerg** [kamon-io/Kamon#857]
I'd like to propose a feature to make it possible to append headers to the HTTP response.  
My particular use case is to maintain a set of legacy headers that must be returned from every application.  
Rather than having every application deal with this Kamon could append the header(s) and I can have a single library doing the job.

My thought would be to allow developers to add a custom `HttpServerResponseHeaderGenerator`via the config.  
E.g. in the config:
```
# FQCN to a class implementing the interface below
kamon.instrumentation.akka.http.server.response.header-generator = "foo.bar.ExampleHttpServerResponseHeaderGenerator"
```

The class must implement this interface for rendering custom headers
```
trait HttpServerResponseHeaderGenerator {
  def headers(context:Context):Map[String, String]
}
```
This allows custom code to extract context information or just generate whatever headers it desires
Would be invoked from the `kamon.instrumentation.http.HttpServerInstrumentation` as part of the building of the response

I'll draft a PR to go with this feature request/ticket

**Comment by ivantopo** [comment]
Hey @pnerg, thanks a lot for bringing this up!

Logic is sound and the PR is actually pretty nice. I only had a small comment about where to put the settings but other than that, it looks really good. This will definitely make it to the next release :muscle:

**Comment by pnerg** [comment]
Noticed the 2.1.7 release was made just a before the PR related to this ticket was merged.
Any plan when a 2.8 release will be made?
Just so I know if I should wait or make my own custom delivery from master as I need this feature.

**Comment by SimunKaracic** [comment]
We planned a release for monday. 
Is that ok?
