### ISSUE TITLE
Bring back the JVM class loading metrics

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#860]
I must have left the JVM class loading metrics our of the system metrics when upgrading to Kamon 2.0. Those metrics should be brought back!

For reference, here is the old file: https://github.com/kamon-io/kamon-system-metrics/blob/v1.0.1/src/main/scala/kamon/system/jvm/ClassLoadingMetrics.scala

**Comment by SimunKaracic** [comment]
Fixed in `2.1.9`
