### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Unable to load library 'DiskArbitration'

### ISSUE THREAD

**Issue by oschrenk** [kamon-io/Kamon#871]
I'm trying to setup Kamon 2.1.4 following [Get Started](https://kamon.io/get-started/)

but I am getting

```
[error] Exception in thread "Host Metrics" java.lang.UnsatisfiedLinkError: Unable to load library 'DiskArbitration':
[error] dlopen(libDiskArbitration.dylib, 9): image not found
[error] dlopen(libDiskArbitration.dylib, 9): image not found
[error] Native library (darwin/libDiskArbitration.dylib) not found
...
```
( see full log [here](https://gist.github.com/oschrenk/3198beea6e30f41db76a1545b6ca295a) )

when I run `sbt run` (using `sbt-kanela-runner` `2.0.6`).

My best guess is that this is because I am using macOS 11 Big Sur Beta (work laptop is in repair, and I have to use my private machine) and that I  am hitting https://github.com/oshi/oshi/issues/1289

My current workaround (thanks @liff via gitter) is to disable host metrics and process metrics.

**Comment by SimunKaracic** [comment]
Fixed with version `2.0.8`
