### ISSUE TITLE
Scala Play manual instrumentation

### ISSUE THREAD

**Issue by neboduus** [kamon-io/Kamon#875]
Hi everyone, thanks for this cool open library which can be easily integrated with 3rd party tools. I am using it to send traces from a Scala (2.11.12) Play (2.6) application to a Zipkin Server which has been modified to store data on Google Stackdrive. I've been able to set up the automatic instrumentation using the instructions from the webpage documentation. However, I am not able to set up tha manual instrumentation which would be my objective, because I'd like to trace specific functions from my api. If this would be possible we would like to try it out and then evaluate the possibility of changing Zipkin and Stackdriver with Kamon specific storage systems. Thanks for any possible answer. Bests

**Comment by ivantopo** [comment]
Hey @neboduus! I'm guessing that the main question you have is related to this:

> However, I am not able to set up tha manual instrumentation which would be my objective, because I'd like to trace specific functions from my api.

Did you have any problems creating spans manually? It is definitely possible to mix manual and automatic instrumentation! Please tell us a bit more about the specifics your tried and we'll take it from there.

**Comment by SimunKaracic** [comment]
Closing because user reported on gitter that they were successful in getting manual instrumentation up and running
