### ISSUE TITLE
assembly issues when updating from 2.1.6 to 2.1.8

### ISSUE THREAD

**Issue by fmonniot** [kamon-io/Kamon#889]
Hello there,

My service is distributed as a fat jar, and when I tried to update kamon-bundle from 2.1.6 to 2.1.8, I found out that the bundle is now including several non shaded dependencies which conflict with some of my own. Here is a list of the conflict I had:

- `kamon-bundle_2.12-2.1.8.jar:com/github/benmanes/caffeine`
- `kamon-bundle_2.12-2.1.8.jar:org/checkerframework/framework`

Would it be possible to shade those dependencies ?

**Comment by SimunKaracic** [comment]
I'll get on it!
