### ISSUE TITLE
Missing 'jvm.memory.buffer-pool.usage' metric in 2.x 

### ISSUE THREAD

**Issue by kunalherkal** [kamon-io/Kamon#893]
When we migrated Kamon from 1.x to 2.x, we observed `jvm.memory.buffer-pool.usage` metric is now missing. We were using metrics for `direct` and `mapped` buffer pools. I couldn't find it in the [documentation](https://kamon.io/docs/latest/instrumentation/system/jvm-metrics/), so I assume it is either moved in some other category or it is missing in 2.x.

Is there an other way to get values of this metric in some other way or is this missing in 2.x? And if it is missing in 2.x can it be added soon?

The Kamon dependencies we use:
```
"io.kamon" %% "kamon-bundle" % "2.1.8"
"io.kamon" %% "kamon-influxdb" % "2.1.8"
"io.kamon" %% "kamon-prometheus" % "2.1.8"
"io.kamon" % "kanela-agent" % "1.0.7"
```
Other version details:
```
scalaVersion: 2.12.8, 
sbtVersion: 1.4.2
openjdk version "11.0.2" 2019-01-15
```

**Comment by SimunKaracic** [comment]
We missed those when upgrading  :(
We'll bring them back soon! If you find anything else missing, let me know, all of those metrics should be in kamon 2.x
