### ISSUE TITLE
akka cluster 2.6.12 cluster fails to connect

### ISSUE THREAD

**Issue by fggarcia** [kamon-io/Kamon#935]
Hi @SimunKaracic today i release my app with kamon 2.1.11. I try to upgrade from kamon 2.19 (all my production instances have this version).

When the first deploy node is updated to the new version i have the same issue that #767  

```
2021-02-01T21:05:30.135Z (xxxx) WARN  [][][xxx-akka.actor.default-dispatcher-58] akka.remote.artery.Deserializer - Failed to deserialize message from [unknown] with serializer id [17] and manifest [d]. java.lang.IllegalArgumentException: newPosition < 0: (-548456067 < 0)
```

does it exist any way to deploy without a full cluster restart??

Prev release dependencies:
```
val akkaVersion = "2.6.10"
val akkaHttpVersion = "10.2.2"
val kamonVersion = "2.1.9"
```

new release dependencies:
```
val akkaVersion = "2.6.12"
val akkaHttpVersion = "10.2.3"
val kamonVersion = "2.1.11"
```

**Comment by fggarcia** [comment]
@SimunKaracic @ivantopo 

have any idea?

**Comment by SimunKaracic** [comment]
Since the problem here is the nodes with the old version , I don't think you have any choice other than a full cluster restart :(  

From now on though, you can do rolling restarts
