### ISSUE TITLE
Add support for an OpenTelemetry trace/span reporter

### ISSUE THREAD

**Issue by pnerg** [kamon-io/Kamon#973]
Kamon needs to add support for exporting traces according to the [OpenTelemetry Protocol (OTLP)](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md).
 
This ticket is added as a placeholder as I intend to donate my ongoing implementation [kamon-otel-trace-exporter](https://github.com/pnerg/kamon-otel-trace-exporter) once I have it in decent shape.

**Comment by SimunKaracic** [comment]
We eagerly await your donation, feel free to open a WIP pull request or ask for help!

**Comment by pnerg** [comment]
@SimunKaracic just did an integration test with the exporter and the released w3c context propagation....resulted in #975 :)

Apart from that the code is in working condition. Will make a PR soonish, the only thing I'll leave out is support for TLS.
Think that can come in a later release. Guess there's very few apps actually using TLS for reporting trace data.
