### ISSUE TITLE
RangeSampler reset

### ISSUE THREAD

**Issue by danischroeter** [kamon-io/Kamon#974]
Hi there
I've got an akka actor that manages a queue. The size of the queue is tracked by a RangeSampler using increment/decrement... This works fine normally.
But now when this actor fails and a new queue is created I need to reset this RangeSampler back to 0 when the new actor with a fresh queue is started...
There is no reset() on RangeSampler and I do not know the current value so that I could do a decrement(currentValue).

**Comment by danischroeter** [comment]
from gitter:
> @SimunKaracic 16:16
There's nothing like that currently, but it's simple to add when I get half an hour of time!
SimunKaracic
@SimunKaracic 16:17
You can expect it in your Kamon bundle within a week
@danischroeter 16:51
Thx! That would be awesome. Should I create an issue on github?
@SimunKaracic 17:03
yes please!

**Comment by danischroeter** [comment]
> @SimunKaracic 16:17
> You can expect it in your Kamon bundle within a week
;)

**Comment by SimunKaracic** [comment]
Sorrryyyyyyy, there is some small issue with that, we're working on it!

**Comment by danischroeter** [comment]
@SimunKaracic  Thx! Just wanted to ensure this does not get forgotten.
