### ISSUE TITLE
W3C context propagation hex encodes in capital letters causing failure to read the identifiers

### ISSUE THREAD

**Issue by pnerg** [kamon-io/Kamon#985]
# Issue
When propagating using W3C it hex encodes the identifiers like this:
```
 def idToHex(identifier: Identifier, length: Int): String = {
      val leftPad = (string: String) => "0" * (length - string.length) + string
      leftPad(identifier.bytes.map("%02X" format _).mkString)
    }
```
[SpanPropagation.scala#L105](https://github.com/kamon-io/Kamon/blob/master/core/kamon-core/src/main/scala/kamon/trace/SpanPropagation.scala#L105)

`"%02X"`causes the generated hex to be in capital letters.
According to the [W3C specification](https://www.w3.org/TR/trace-context/#traceparent-header-field-values) the identifiers shall be in lowercase.   
_"HEXDIGLC = DIGIT / "a" / "b" / "c" / "d" / "e" / "f" ; lowercase hex character"_

# Effect
This breaks when the request is received on the other end as Kamon fails to parse the identifier due to being uppercase
E.g.
```
  val identityProvider = Identifier.Scheme.Double

  val s = "2f2b727a4a0dcfd8c0bed5f6209f2694"

  println(identityProvider.traceIdFactory.from(s.toLowerCase).isEmpty)
  println(identityProvider.traceIdFactory.from(s.toLowerCase).string)

  println(identityProvider.traceIdFactory.from(s.toUpperCase).isEmpty)
  println(identityProvider.traceIdFactory.from(s.toUpperCase).string)
```
yields
```
false
2f2b727a4a0dcfd8c0bed5f6209f2694
true

```

# Solution
Change to `leftPad(identifier.bytes.map("%02x" format _).mkString)`
Note the 'x' to dictate lower caps.

**Comment by SimunKaracic** [comment]
Fixed in 2.1.16!
