### ISSUE TITLE
Cannot resolve sbt-kanela-runner-play-2.8 V2.0.9

### ISSUE THREAD

**Issue by Andrurodr** [kamon-io/Kamon#993]
When i tried to download the dependencies i cannot get the sbt-kanela-runner-play-2.8 V2.0.9.
I tried with 2.0.6 and the same thing happened. This is not working since today (12/04/2021)

This is the error log. When ivy tries to get the dependency the response is a 403 Forbidden from the server.
The resource is https://dl.bintray.com/sbt/sbt-plugin-releases/io.kamon/sbt-kanela-runner-play-2.8/scala_2.12/sbt_1.0/2.0.9/ivys/ivy.xml

`[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/kamon-io/sbt-plugins/io.kamon/sbt-kanela-runner-play-2.8/scala_2.12/sbt_1.0/2.0.9/ivys/ivy.xml (Server returned HTTP response code: 403 for URL: https://dl.bintray.com/kamon-io/sbt-plugins/io.kamon/sbt-kanela-runner-play-2.8/scala_2.12/sbt_1.0/2.0.9/ivys/ivy.xml) while downloading https://dl.bintray.com/kamon-io/sbt-plugins/io.kamon/sbt-kanela-runner-play-2.8/scala_2.12/sbt_1.0/2.0.9/ivys/ivy.xml`

`[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/io.kamon/sbt-kanela-runner-play-2.8/scala_2.12/sbt_1.0/2.0.9/ivys/ivy.xml (Server returned HTTP response code: 403 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/io.kamon/sbt-kanela-runner-play-2.8/scala_2.12/sbt_1.0/2.0.9/ivys/ivy.xml) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.kamon/sbt-kanela-runner-play-2.8/scala_2.12/sbt_1.0/2.0.9/ivys/ivy.xml`

`[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/typesafe/ivy-releases/io.kamon/sbt-kanela-runner-play-2.8/scala_2.12/sbt_1.0/2.0.9/ivys/ivy.xml (Server returned HTTP response code: 403 for URL: https://dl.bintray.com/typesafe/ivy-releases/io.kamon/sbt-kanela-runner-play-2.8/scala_2.12/sbt_1.0/2.0.9/ivys/ivy.xml) while downloading https://repo.typesafe.com/typesafe/ivy-releases/io.kamon/sbt-kanela-runner-play-2.8/scala_2.12/sbt_1.0/2.0.9/ivys/ivy.xml`

You can help me with this ? Thanks you !

**Comment by SimunKaracic** [comment]
Explanation here: 
https://github.com/kamon-io/kanela/issues/119

We'll move to different hosting soon!
